// apps/docs/registry/default/components/dropdown/dropdown-15.tsx
'use client'

import { useState } from 'react'
import { MonitorIcon, MoonIcon, SunIcon } from 'lucide-react'

import { Button } from '../../ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '../../ui/dropdown-menu'

type Theme = 'light' | 'dark' | 'system'

export default function Component() {
  const [theme, setTheme] = useState<Theme>('system')

  // For demo purposes, we'll simulate system preference as "light"
  const systemPreference = 'light'
  const displayTheme = theme === 'system' ? systemPreference : theme

  return (
    <div>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button size="icon" variant="outline" aria-label="Select theme">
            {displayTheme === 'light' && <SunIcon size={16} aria-hidden="true" />}
            {displayTheme === 'dark' && <MoonIcon size={16} aria-hidden="true" />}
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent className="min-w-32">
          <DropdownMenuItem onClick={() => setTheme('light')}>
            <SunIcon size={16} className="opacity-60" aria-hidden="true" />
            <span>Light</span>
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => setTheme('dark')}>
            <MoonIcon size={16} className="opacity-60" aria-hidden="true" />
            <span>Dark</span>
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => setTheme('system')}>
            <MonitorIcon size={16} className="opacity-60" aria-hidden="true" />
            <span>System</span>
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  )
}

// apps/docs/registry/default/components/dropdown/dropdown-15.vue
<script setup lang="ts">
import { MonitorIcon, MoonIcon, SunIcon } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';



</script>

<template>
  <div><DropdownMenu><DropdownMenuTrigger as-child><Button size="icon" variant="outline" aria-label="Select theme"><SunIcon v-if="displayTheme === 'light'" :size="16" aria-hidden="true" /><MoonIcon v-if="displayTheme === 'dark'" :size="16" aria-hidden="true" /></Button></DropdownMenuTrigger><DropdownMenuContent class="min-w-32"><DropdownMenuItem @click="setTheme('light')"><SunIcon :size="16" class="opacity-60" aria-hidden="true" /><span>Light</span></DropdownMenuItem><DropdownMenuItem @click="setTheme('dark')"><MoonIcon :size="16" class="opacity-60" aria-hidden="true" /><span>Dark</span></DropdownMenuItem><DropdownMenuItem @click="setTheme('system')"><MonitorIcon :size="16" class="opacity-60" aria-hidden="true" /><span>System</span></DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
</template>
