// apps/docs/registry/default/ui/collapsible.tsx
'use client'

import * as React from 'react'
import { cn, collapsibleConnect, collapsibleMachine } from '@timui/core'
import { mergeProps, normalizeProps, useMachine } from '@zag-js/react'

import { Slot } from './slot'

const CollapsibleContext = React.createContext<{
  api: ReturnType<typeof collapsibleConnect>
} | null>(null)

function useCollapsible() {
  const context = React.useContext(CollapsibleContext)
  if (!context) {
    throw new Error('Collapsible components must be used within Collapsible')
  }
  return context
}

const Collapsible = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & {
    open?: boolean
    defaultOpen?: boolean
    onOpenChange?: (open: boolean) => void
    disabled?: boolean
  }
>(({ className, open, defaultOpen, onOpenChange, disabled, ...props }, ref) => {
  const service = useMachine(collapsibleMachine, {
    id: React.useId(),
    open,
    defaultOpen,
    disabled,
    onOpenChange(details) {
      onOpenChange?.(details.open)
    },
  })
  const api = React.useMemo(() => collapsibleConnect(service, normalizeProps), [service])
  const rootProps = api.getRootProps()
  const mergedProps = mergeProps(rootProps, props)

  return (
    <CollapsibleContext.Provider value={{ api }}>
      <div ref={ref} data-slot="collapsible" {...mergedProps} className={cn(className)} />
    </CollapsibleContext.Provider>
  )
})
Collapsible.displayName = 'Collapsible'

const CollapsibleTrigger = React.forwardRef<
  HTMLButtonElement,
  React.ButtonHTMLAttributes<HTMLButtonElement> & { asChild?: boolean }
>(({ className, asChild = false, ...props }, ref) => {
  const { api } = useCollapsible()
  const Comp = asChild ? Slot : 'button'
  const triggerProps = api.getTriggerProps()

  return (
    <Comp
      ref={ref}
      data-slot="collapsible-trigger"
      {...mergeProps(triggerProps, props)}
      className={cn(className)}
    />
  )
})
CollapsibleTrigger.displayName = 'CollapsibleTrigger'

const CollapsibleContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, children, ...props }, ref) => {
    const { api } = useCollapsible()
    const contentProps = api.getContentProps()
    const mergedProps = mergeProps(contentProps, props)

    return (
      <div
        ref={ref}
        data-slot="collapsible-content"
        className={cn('overflow-hidden', className)}
        {...mergedProps}
      >
        {children}
      </div>
    )
  }
)
CollapsibleContent.displayName = 'CollapsibleContent'

export { Collapsible, CollapsibleContent, CollapsibleTrigger }

// apps/docs/registry/default/vue/collapsible.vue
<script setup lang="ts">
import { computed, provide, type HTMLAttributes } from 'vue'
import { normalizeProps, useMachine } from '@zag-js/vue'
import { collapsibleConnect, collapsibleMachine } from '@timui/core'
import { cn } from '@timui/core'

const props = defineProps<{
  open?: boolean
  defaultOpen?: boolean
  disabled?: boolean
  id?: string
  class?: HTMLAttributes['class']
}>()

const emit = defineEmits(['update:open', 'change'])

const machineProps = computed(() => ({
  id: props.id,
  open: props.open,
  defaultOpen: props.open === undefined ? props.defaultOpen : undefined,
  disabled: props.disabled,
  onOpenChange(details: { open: boolean }) {
    emit('update:open', details.open)
    emit('change', details.open)
  },
}))

const service = useMachine(collapsibleMachine, machineProps)
const api = computed(() => collapsibleConnect(service, normalizeProps))

provide('collapsible', { api })
</script>

<template>
  <div
    v-bind="api.getRootProps()"
    data-slot="collapsible"
    :data-state="api.open ? 'open' : 'closed'"
    :class="cn(props.class)"
  >
    <slot />
  </div>
</template>
