// packages/react/src/components/ui/cropper.tsx
'use client'
'use client'

import { Cropper as CropperPrimitive } from '@origin-space/image-cropper'
import {
  cn,
  cropperCropAreaVariants,
  cropperDescriptionVariants,
  cropperImageVariants,
  cropperRootVariants,
} from '@timui/core'

function Cropper({ className, ...props }: React.ComponentProps<typeof CropperPrimitive.Root>) {
  return (
    <CropperPrimitive.Root
      data-slot="cropper"
      className={cn(cropperRootVariants(), className)}
      {...props}
    />
  )
}

function CropperDescription({
  className,
  ...props
}: React.ComponentProps<typeof CropperPrimitive.Description>) {
  return (
    <CropperPrimitive.Description
      data-slot="cropper-description"
      className={cn(cropperDescriptionVariants(), className)}
      {...props}
    />
  )
}

function CropperImage({
  className,
  ...props
}: React.ComponentProps<typeof CropperPrimitive.Image>) {
  return (
    <CropperPrimitive.Image
      data-slot="cropper-image"
      className={cn(cropperImageVariants(), className)}
      {...props}
    />
  )
}

function CropperCropArea({
  className,
  ...props
}: React.ComponentProps<typeof CropperPrimitive.CropArea>) {
  return (
    <CropperPrimitive.CropArea
      data-slot="cropper-crop-area"
      className={cn(cropperCropAreaVariants(), className)}
      {...props}
    />
  )
}

export { Cropper, CropperDescription, CropperImage, CropperCropArea }

// packages/vue/src/components/ui/cropper/cropper.vue
<script lang="ts">
import { defineComponent, h } from "vue";
import { cn, cropperCropAreaVariants, cropperDescriptionVariants, cropperImageVariants, cropperRootVariants } from "@timui/core";

export const Cropper = defineComponent({
  name: "Cropper",
  inheritAttrs: false,
  props: {
    class: {
      type: String,
      default: undefined,
    },
  },
  setup(props, { attrs, slots }) {
    return () =>
      h(
        "div",
        {
          ...attrs,
          "data-slot": "cropper",
          class: cn(cropperRootVariants(), props.class),
        },
        slots.default?.()
      );
  },
});

export const CropperDescription = defineComponent({
  name: "CropperDescription",
  inheritAttrs: false,
  props: {
    class: {
      type: String,
      default: undefined,
    },
  },
  setup(props, { attrs, slots }) {
    return () =>
      h(
        "p",
        {
          ...attrs,
          "data-slot": "cropper-description",
          class: cn(cropperDescriptionVariants(), props.class),
        },
        slots.default?.()
      );
  },
});

export const CropperImage = defineComponent({
  name: "CropperImage",
  inheritAttrs: false,
  props: {
    class: {
      type: String,
      default: undefined,
    },
  },
  setup(props, { attrs }) {
    return () =>
      h("img", {
        ...attrs,
        "data-slot": "cropper-image",
        class: cn(cropperImageVariants(), props.class),
      });
  },
});

export const CropperCropArea = defineComponent({
  name: "CropperCropArea",
  inheritAttrs: false,
  props: {
    class: {
      type: String,
      default: undefined,
    },
  },
  setup(props, { attrs }) {
    return () =>
      h("div", {
        ...attrs,
        "data-slot": "cropper-crop-area",
        class: cn(cropperCropAreaVariants(), props.class),
      });
  },
});

export default Cropper;
</script>
