// apps/docs/registry/default/components/navbar-components/user-menu.vue
<script setup lang="ts">
import { BoltIcon, BookOpenIcon, Layers2Icon, LogOutIcon, PinIcon, UserPenIcon } from 'lucide-vue-next';
import { Avatar, AvatarFallback, AvatarImage } from '@timui/vue';
import { Button } from '@timui/vue';
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@timui/vue';




</script>

<template>
  <DropdownMenu><DropdownMenuTrigger as-child><Button variant="ghost" class="h-auto p-0 hover:bg-transparent"><Avatar><AvatarImage src="./avatar.jpg" alt="Profile image" /><AvatarFallback>KK</AvatarFallback></Avatar></Button></DropdownMenuTrigger><DropdownMenuContent class="max-w-64" align="end"><DropdownMenuLabel class="flex min-w-0 flex-col"><span class="text-foreground truncate text-sm font-medium">Keith Kennedy</span><span class="text-muted-foreground truncate text-xs font-normal">k.kennedy@ui.timkit.cn
          </span></DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuGroup><DropdownMenuItem><BoltIcon :size="16" class="opacity-60" aria-hidden="true" /><span>Option 1</span></DropdownMenuItem><DropdownMenuItem><Layers2Icon :size="16" class="opacity-60" aria-hidden="true" /><span>Option 2</span></DropdownMenuItem><DropdownMenuItem><BookOpenIcon :size="16" class="opacity-60" aria-hidden="true" /><span>Option 3</span></DropdownMenuItem></DropdownMenuGroup><DropdownMenuSeparator /><DropdownMenuGroup><DropdownMenuItem><PinIcon :size="16" class="opacity-60" aria-hidden="true" /><span>Option 4</span></DropdownMenuItem><DropdownMenuItem><UserPenIcon :size="16" class="opacity-60" aria-hidden="true" /><span>Option 5</span></DropdownMenuItem></DropdownMenuGroup><DropdownMenuSeparator /><DropdownMenuItem><LogOutIcon :size="16" class="opacity-60" aria-hidden="true" /><span>Logout</span></DropdownMenuItem></DropdownMenuContent></DropdownMenu>
</template>

// apps/docs/registry/default/components/navbar-components/user-menu.tsx
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
  Button,
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@timui/react'
import { BoltIcon, BookOpenIcon, Layers2Icon, LogOutIcon, PinIcon, UserPenIcon } from 'lucide-react'

export default function UserMenu() {
  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="ghost" className="h-auto p-0 hover:bg-transparent">
          <Avatar>
            <AvatarImage src="./avatar.jpg" alt="Profile image" />
            <AvatarFallback>KK</AvatarFallback>
          </Avatar>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="max-w-64" align="end">
        <DropdownMenuLabel className="flex min-w-0 flex-col">
          <span className="text-foreground truncate text-sm font-medium">Keith Kennedy</span>
          <span className="text-muted-foreground truncate text-xs font-normal">
            k.kennedy@ui.timkit.cn
          </span>
        </DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuGroup>
          <DropdownMenuItem>
            <BoltIcon size={16} className="opacity-60" aria-hidden="true" />
            <span>Option 1</span>
          </DropdownMenuItem>
          <DropdownMenuItem>
            <Layers2Icon size={16} className="opacity-60" aria-hidden="true" />
            <span>Option 2</span>
          </DropdownMenuItem>
          <DropdownMenuItem>
            <BookOpenIcon size={16} className="opacity-60" aria-hidden="true" />
            <span>Option 3</span>
          </DropdownMenuItem>
        </DropdownMenuGroup>
        <DropdownMenuSeparator />
        <DropdownMenuGroup>
          <DropdownMenuItem>
            <PinIcon size={16} className="opacity-60" aria-hidden="true" />
            <span>Option 4</span>
          </DropdownMenuItem>
          <DropdownMenuItem>
            <UserPenIcon size={16} className="opacity-60" aria-hidden="true" />
            <span>Option 5</span>
          </DropdownMenuItem>
        </DropdownMenuGroup>
        <DropdownMenuSeparator />
        <DropdownMenuItem>
          <LogOutIcon size={16} className="opacity-60" aria-hidden="true" />
          <span>Logout</span>
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
