// apps/docs/registry/default/components/input/input-18.vue
<script setup lang="ts">
import { Input } from '@timui/vue';
import { Label } from '@timui/vue';
import { SelectNative } from '@timui/vue';





const id = 'input-18';

</script>

<template>
  <div class="*:not-first:mt-2"><Label :htmlFor="id">Input with end select</Label><div class="flex rounded-md shadow-xs"><Input :id="id" class="-me-px rounded-e-none shadow-none focus-visible:z-10" placeholder="google" type="text" /><SelectNative class="text-muted-foreground hover:text-foreground w-fit rounded-s-none shadow-none"><option>.com</option><option>.org</option><option>.net</option></SelectNative></div></div>
</template>

// apps/docs/registry/default/components/input/input-18.tsx
import { useId } from 'react'
import { Input, Label, SelectNative } from '@timui/react'

export default function Component() {
  const id = useId()
  return (
    <div className="*:not-first:mt-2">
      <Label htmlFor={id}>Input with end select</Label>
      <div className="flex rounded-md shadow-xs">
        <Input
          id={id}
          className="-me-px rounded-e-none shadow-none focus-visible:z-10"
          placeholder="google"
          type="text"
        />
        <SelectNative className="text-muted-foreground hover:text-foreground w-fit rounded-s-none shadow-none">
          <option>.com</option>
          <option>.org</option>
          <option>.net</option>
        </SelectNative>
      </div>
    </div>
  )
}
