// apps/docs/registry/default/components/dialog/dialog-10.vue
<script setup lang="ts">
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
</script>
<template>
<Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Feedback</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Send us feedback</DialogTitle>
          <DialogDescription>
            Watch 
            <a class="text-foreground hover:underline" href="#">
              tutorials
            </a>
            , read Timkit UI&lsquo;s 
            <a class="text-foreground hover:underline" href="#">
              documentation
            </a>
            , or join our 
            <a class="text-foreground hover:underline" href="#">
              Discord
            </a> 
            for community help.
          </DialogDescription>
        </DialogHeader>
        <form class="space-y-5">
          <Textarea
            id="feedback"
            placeholder="How can we improve Timkit UI?"
            aria-label="Send feedback"
          />
          <div class="flex flex-col sm:flex-row sm:justify-end">
            <Button type="button">Send feedback</Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
</template>

// apps/docs/registry/default/components/dialog/dialog-10.tsx
import { Button } from '../../ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../../ui/dialog'
import { Textarea } from '../../ui/textarea'

export default function Component() {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Feedback</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Send us feedback</DialogTitle>
          <DialogDescription>
            Watch{' '}
            <a className="text-foreground hover:underline" href="#">
              tutorials
            </a>
            , read Timkit UI&lsquo;s{' '}
            <a className="text-foreground hover:underline" href="#">
              documentation
            </a>
            , or join our{' '}
            <a className="text-foreground hover:underline" href="#">
              Discord
            </a>{' '}
            for community help.
          </DialogDescription>
        </DialogHeader>
        <form className="space-y-5">
          <Textarea
            id="feedback"
            placeholder="How can we improve Timkit UI?"
            aria-label="Send feedback"
          />
          <div className="flex flex-col sm:flex-row sm:justify-end">
            <Button type="button">Send feedback</Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  )
}
