// apps/docs/registry/default/components/image-cropper/image-cropper-01.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { ArrowLeftIcon, CircleUserRoundIcon, XIcon, ZoomInIcon, ZoomOutIcon } from 'lucide-vue-next';
import { Button } from '@timui/vue';
import { Cropper, CropperCropArea, CropperDescription, CropperImage } from '@timui/vue';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@timui/vue';
import { Slider } from '@timui/vue';
import { useFileUpload } from '@/registry/default/hooks/use-file-upload-vue';

type Area = { x: number; y: number; width: number; height: number };

const createImage = (url: string): Promise<HTMLImageElement> =>
  new Promise((resolve, reject) => {
    const image = new Image();
    image.addEventListener('load', () => resolve(image));
    image.addEventListener('error', (error) => reject(error));
    image.setAttribute('crossOrigin', 'anonymous');
    image.src = url;
  });

async function getCroppedImg(
  imageSrc: string,
  pixelCrop: Area,
  outputWidth: number = pixelCrop.width,
  outputHeight: number = pixelCrop.height,
): Promise<Blob | null> {
  try {
    const image = await createImage(imageSrc);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');

    if (!ctx) return null;

    canvas.width = outputWidth;
    canvas.height = outputHeight;

    ctx.drawImage(
      image,
      pixelCrop.x,
      pixelCrop.y,
      pixelCrop.width,
      pixelCrop.height,
      0,
      0,
      outputWidth,
      outputHeight,
    );

    return new Promise((resolve) => {
      canvas.toBlob((blob) => resolve(blob), 'image/jpeg');
    });
  } catch (error) {
    console.error('Error in getCroppedImg:', error);
    return null;
  }
}

const [
  { files, isDragging },
  {
    handleDragEnter,
    handleDragLeave,
    handleDragOver,
    handleDrop,
    openFileDialog,
    removeFile,
    getInputProps,
  },
] = useFileUpload({
  accept: 'image/*',
});

const previewUrl = computed(() => files.value[0]?.preview ?? null);
const fileId = computed(() => files.value[0]?.id ?? null);

const finalImageUrl = ref<string | null>(null);
const isDialogOpen = ref(false);
const croppedAreaPixels = ref<Area | null>(null);
const zoom = ref(1);
const previousFileId = ref<string | null>(null);

function setIsDialogOpen(nextOpen: boolean) {
  isDialogOpen.value = nextOpen;
}

function setZoom(nextZoom: number) {
  zoom.value = nextZoom;
}

function handleCropChange(pixels: Area | null) {
  croppedAreaPixels.value = pixels;
}

function handleZoomValueChange(values: number[]) {
  setZoom(values[0] ?? 1);
}

async function handleApply() {
  if (!previewUrl.value || !fileId.value) {
    return;
  }

  let area = croppedAreaPixels.value;

  if (!area) {
    const image = await createImage(previewUrl.value);
    area = {
      x: 0,
      y: 0,
      width: image.width,
      height: image.height,
    };
  }

  const croppedBlob = await getCroppedImg(previewUrl.value, area);
  if (!croppedBlob) {
    isDialogOpen.value = false;
    return;
  }

  const nextFinalImageUrl = URL.createObjectURL(croppedBlob);

  if (finalImageUrl.value?.startsWith('blob:')) {
    URL.revokeObjectURL(finalImageUrl.value);
  }

  finalImageUrl.value = nextFinalImageUrl;
  isDialogOpen.value = false;
}

function handleRemoveFinalImage() {
  if (finalImageUrl.value?.startsWith('blob:')) {
    URL.revokeObjectURL(finalImageUrl.value);
  }
  finalImageUrl.value = null;

  const currentFileId = fileId.value;
  if (currentFileId) {
    removeFile(currentFileId);
  }
}

watch(fileId, (nextFileId) => {
  if (nextFileId && nextFileId !== previousFileId.value) {
    isDialogOpen.value = true;
    croppedAreaPixels.value = null;
    zoom.value = 1;
  }
  previousFileId.value = nextFileId;
});

onBeforeUnmount(() => {
  if (finalImageUrl.value?.startsWith('blob:')) {
    URL.revokeObjectURL(finalImageUrl.value);
  }
});
</script>

<template>
  <div class="flex flex-col items-center gap-2">
    <div class="relative inline-flex">
      <button
        class="border-input hover:bg-accent/50 data-[dragging=true]:bg-accent/50 focus-visible:border-ring focus-visible:ring-ring/50 relative flex size-16 items-center justify-center overflow-hidden rounded-full border border-dashed transition-colors outline-none focus-visible:ring-[3px] has-disabled:pointer-events-none has-disabled:opacity-50 has-[img]:border-none"
        @click="openFileDialog"
        @dragenter="handleDragEnter"
        @dragleave="handleDragLeave"
        @dragover="handleDragOver"
        @drop="handleDrop"
        :data-dragging="isDragging || undefined"
        :aria-label="finalImageUrl ? 'Change image' : 'Upload image'"
      >
        <template v-if="finalImageUrl">
          <img
            class="size-full object-cover"
            :src="finalImageUrl"
            alt="User avatar"
            :width="64"
            :height="64"
            :style="{ objectFit: 'cover' }"
          />
        </template>
        <template v-else>
          <div aria-hidden="true">
            <CircleUserRoundIcon class="size-4 opacity-60" />
          </div>
        </template>
      </button>

      <Button
        v-if="finalImageUrl"
        @click="handleRemoveFinalImage"
        size="icon"
        class="border-background focus-visible:border-background absolute -top-1 -right-1 size-6 rounded-full border-2 shadow-none"
        aria-label="Remove image"
      >
        <XIcon class="size-3.5" />
      </Button>

      <input
        v-bind="getInputProps()"
        class="sr-only"
        aria-label="Upload image file"
        :tabIndex="-1"
      />
    </div>

    <Dialog :open="isDialogOpen" @update:open="setIsDialogOpen">
      <DialogContent class="gap-0 p-0 sm:max-w-140 *:[button]:hidden">
        <DialogDescription class="sr-only">Crop image dialog</DialogDescription>
        <DialogHeader class="contents space-y-0 text-left">
          <DialogTitle class="flex items-center justify-between border-b p-4 text-base">
            <div class="flex items-center gap-2">
              <Button
                type="button"
                variant="ghost"
                size="icon"
                class="-my-1 opacity-60"
                @click="setIsDialogOpen(false)"
                aria-label="Cancel"
              >
                <ArrowLeftIcon aria-hidden="true" />
              </Button>
              <span>Crop image</span>
            </div>
            <Button class="-my-1" @click="handleApply" :disabled="!previewUrl" autoFocus>
              Apply
            </Button>
          </DialogTitle>
        </DialogHeader>

        <Cropper
          v-if="previewUrl"
          class="h-96 sm:h-120"
          :image="previewUrl"
          :zoom="zoom"
          :onCropChange="handleCropChange"
          :onZoomChange="setZoom"
        >
          <CropperDescription />
          <CropperImage />
          <CropperCropArea />
        </Cropper>

        <DialogFooter class="border-t px-4 py-6">
          <div class="mx-auto flex w-full max-w-80 items-center gap-4">
            <ZoomOutIcon class="shrink-0 opacity-60" :size="16" aria-hidden="true" />
            <Slider
              :default-value="[1]"
              :value="[zoom]"
              :min="1"
              :max="3"
              :step="0.1"
              @update:modelValue="handleZoomValueChange"
              aria-label="Zoom slider"
            />
            <ZoomInIcon class="shrink-0 opacity-60" :size="16" aria-hidden="true" />
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>

    <p aria-live="polite" role="region" class="text-muted-foreground mt-2 text-xs">
      Avatar
      <a
        href="https://github.com/origin-space/originui/tree/main/docs/use-file-upload.md"
        class="hover:text-foreground underline"
        target="_blank"
      >
        uploader
      </a>
      with
      <a
        href="https://github.com/origin-space/image-cropper"
        class="hover:text-foreground underline"
        target="_blank"
      >
        cropper
      </a>
    </p>
  </div>
</template>

// apps/docs/registry/default/components/image-cropper/image-cropper-01.tsx
'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import {
  Button,
  Cropper,
  CropperCropArea,
  CropperDescription,
  CropperImage,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Slider,
} from '@timui/react'
import { ArrowLeftIcon, CircleUserRoundIcon, XIcon, ZoomInIcon, ZoomOutIcon } from 'lucide-react'

import { useFileUpload } from '@/registry/default/hooks/use-file-upload'

// Define type for pixel crop area
type Area = { x: number; y: number; width: number; height: number }

// Helper function to create a cropped image blob
const createImage = (url: string): Promise<HTMLImageElement> =>
  new Promise((resolve, reject) => {
    const image = new Image()
    image.addEventListener('load', () => resolve(image))
    image.addEventListener('error', (error) => reject(error))
    image.setAttribute('crossOrigin', 'anonymous') // Needed for canvas Tainted check
    image.src = url
  })

async function getCroppedImg(
  imageSrc: string,
  pixelCrop: Area,
  outputWidth: number = pixelCrop.width, // Optional: specify output size
  outputHeight: number = pixelCrop.height
): Promise<Blob | null> {
  try {
    const image = await createImage(imageSrc)
    const canvas = document.createElement('canvas')
    const ctx = canvas.getContext('2d')

    if (!ctx) {
      return null
    }

    // Set canvas size to desired output size
    canvas.width = outputWidth
    canvas.height = outputHeight

    // Draw the cropped image onto the canvas
    ctx.drawImage(
      image,
      pixelCrop.x,
      pixelCrop.y,
      pixelCrop.width,
      pixelCrop.height,
      0,
      0,
      outputWidth, // Draw onto the output size
      outputHeight
    )

    // Convert canvas to blob
    return new Promise((resolve) => {
      canvas.toBlob((blob) => {
        resolve(blob)
      }, 'image/jpeg') // Specify format and quality if needed
    })
  } catch (error) {
    console.error('Error in getCroppedImg:', error)
    return null
  }
}

export default function Component() {
  const [
    { files, isDragging },
    {
      handleDragEnter,
      handleDragLeave,
      handleDragOver,
      handleDrop,
      openFileDialog,
      removeFile,
      getInputProps,
    },
  ] = useFileUpload({
    accept: 'image/*',
  })

  const previewUrl = files[0]?.preview || null
  const fileId = files[0]?.id

  const [finalImageUrl, setFinalImageUrl] = useState<string | null>(null)
  const [isDialogOpen, setIsDialogOpen] = useState(false)

  // Ref to track the previous file ID to detect new uploads
  const previousFileIdRef = useRef<string | undefined | null>(null)

  // State to store the desired crop area in pixels
  const [croppedAreaPixels, setCroppedAreaPixels] = useState<Area | null>(null)

  // State for zoom level
  const [zoom, setZoom] = useState(1)

  // Callback for Cropper to provide crop data - Wrap with useCallback
  const handleCropChange = useCallback((pixels: Area | null) => {
    setCroppedAreaPixels(pixels)
  }, [])

  const handleApply = async () => {
    // Check if we have the necessary data
    if (!previewUrl || !fileId || !croppedAreaPixels) {
      console.error('Missing data for apply:', {
        previewUrl,
        fileId,
        croppedAreaPixels,
      })
      // Remove file if apply is clicked without crop data?
      if (fileId) {
        removeFile(fileId)
        setCroppedAreaPixels(null)
      }
      return
    }

    try {
      // 1. Get the cropped image blob using the helper
      const croppedBlob = await getCroppedImg(previewUrl, croppedAreaPixels)

      if (!croppedBlob) {
        throw new Error('Failed to generate cropped image blob.')
      }

      // 2. Create a NEW object URL from the cropped blob
      const newFinalUrl = URL.createObjectURL(croppedBlob)

      // 3. Revoke the OLD finalImageUrl if it exists
      if (finalImageUrl) {
        URL.revokeObjectURL(finalImageUrl)
      }

      // 4. Set the final avatar state to the NEW URL
      setFinalImageUrl(newFinalUrl)

      // 5. Close the dialog (don't remove the file yet)
      setIsDialogOpen(false)
    } catch (error) {
      console.error('Error during apply:', error)
      // Close the dialog even if cropping fails
      setIsDialogOpen(false)
    }
  }

  const handleRemoveFinalImage = () => {
    if (finalImageUrl) {
      URL.revokeObjectURL(finalImageUrl)
    }
    setFinalImageUrl(null)
  }

  useEffect(() => {
    const currentFinalUrl = finalImageUrl
    // Cleanup function
    return () => {
      if (currentFinalUrl && currentFinalUrl.startsWith('blob:')) {
        URL.revokeObjectURL(currentFinalUrl)
      }
    }
  }, [finalImageUrl])

  // Effect to open dialog when a *new* file is ready
  useEffect(() => {
    // Check if fileId exists and is different from the previous one
    if (fileId && fileId !== previousFileIdRef.current) {
      setIsDialogOpen(true) // Open dialog for the new file
      setCroppedAreaPixels(null) // Reset crop area for the new file
      setZoom(1) // Reset zoom for the new file
    }
    // Update the ref to the current fileId for the next render
    previousFileIdRef.current = fileId
  }, [fileId]) // Depend only on fileId

  return (
    <div className="flex flex-col items-center gap-2">
      <div className="relative inline-flex">
        {/* Drop area - uses finalImageUrl */}
        <button
          className="border-input hover:bg-accent/50 data-[dragging=true]:bg-accent/50 focus-visible:border-ring focus-visible:ring-ring/50 relative flex size-16 items-center justify-center overflow-hidden rounded-full border border-dashed transition-colors outline-none focus-visible:ring-[3px] has-disabled:pointer-events-none has-disabled:opacity-50 has-[img]:border-none"
          onClick={openFileDialog}
          onDragEnter={handleDragEnter}
          onDragLeave={handleDragLeave}
          onDragOver={handleDragOver}
          onDrop={handleDrop}
          data-dragging={isDragging || undefined}
          aria-label={finalImageUrl ? 'Change image' : 'Upload image'}
        >
          {finalImageUrl ? (
            <img
              className="size-full object-cover"
              src={finalImageUrl}
              alt="User avatar"
              width={64}
              height={64}
              style={{ objectFit: 'cover' }}
            />
          ) : (
            <div aria-hidden="true">
              <CircleUserRoundIcon className="size-4 opacity-60" />
            </div>
          )}
        </button>
        {/* Remove button - depends on finalImageUrl */}
        {finalImageUrl && (
          <Button
            onClick={handleRemoveFinalImage}
            size="icon"
            className="border-background focus-visible:border-background absolute -top-1 -right-1 size-6 rounded-full border-2 shadow-none"
            aria-label="Remove image"
          >
            <XIcon className="size-3.5" />
          </Button>
        )}
        <input
          {...getInputProps()}
          className="sr-only"
          aria-label="Upload image file"
          tabIndex={-1}
        />
      </div>

      {/* Cropper Dialog - Use isDialogOpen for open prop */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="gap-0 p-0 sm:max-w-140 *:[button]:hidden">
          <DialogDescription className="sr-only">Crop image dialog</DialogDescription>
          <DialogHeader className="contents space-y-0 text-left">
            <DialogTitle className="flex items-center justify-between border-b p-4 text-base">
              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  className="-my-1 opacity-60"
                  onClick={() => setIsDialogOpen(false)}
                  aria-label="Cancel"
                >
                  <ArrowLeftIcon aria-hidden="true" />
                </Button>
                <span>Crop image</span>
              </div>
              <Button className="-my-1" onClick={handleApply} disabled={!previewUrl} autoFocus>
                Apply
              </Button>
            </DialogTitle>
          </DialogHeader>
          {previewUrl && (
            <Cropper
              className="h-96 sm:h-120"
              image={previewUrl}
              zoom={zoom}
              onCropChange={handleCropChange}
              onZoomChange={setZoom}
            >
              <CropperDescription />
              <CropperImage />
              <CropperCropArea />
            </Cropper>
          )}
          <DialogFooter className="border-t px-4 py-6">
            <div className="mx-auto flex w-full max-w-80 items-center gap-4">
              <ZoomOutIcon className="shrink-0 opacity-60" size={16} aria-hidden="true" />
              <Slider
                defaultValue={[1]}
                value={[zoom]}
                min={1}
                max={3}
                step={0.1}
                onValueChange={(value) => setZoom(value[0])}
                aria-label="Zoom slider"
              />
              <ZoomInIcon className="shrink-0 opacity-60" size={16} aria-hidden="true" />
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <p aria-live="polite" role="region" className="text-muted-foreground mt-2 text-xs">
        Avatar{' '}
        <a
          href="https://github.com/origin-space/originui/tree/main/docs/use-file-upload.md"
          className="hover:text-foreground underline"
          target="_blank"
        >
          uploader
        </a>{' '}
        with{' '}
        <a
          href="https://github.com/origin-space/image-cropper"
          className="hover:text-foreground underline"
          target="_blank"
        >
          cropper
        </a>
      </p>
    </div>
  )
}
