// apps/docs/registry/default/components/timeline/timeline-10.tsx
import { Timeline, TimelineContent, TimelineItem } from '@timui/react'
import { BookOpenIcon, LucideIcon, MessageCircleIcon, PencilIcon, PlusIcon } from 'lucide-react'

const items: {
  id: number
  user: string
  image: string
  action: ActionType
  date: Date
}[] = [
  {
    id: 1,
    user: 'Matt',
    image: '/avatar-40-02.jpg',
    action: 'post',
    date: new Date(Date.now() - 59000), // 59 seconds ago
  },
  {
    id: 2,
    user: 'Matt',
    image: '/avatar-40-02.jpg',
    action: 'reply',
    date: new Date(Date.now() - 180000), // 3 minutes ago
  },
  {
    id: 3,
    user: 'Matt',
    image: '/avatar-40-02.jpg',
    action: 'edit',
    date: new Date(Date.now() - 300000), // 5 minutes ago
  },
  {
    id: 4,
    user: 'Matt',
    image: '/avatar-40-02.jpg',
    action: 'create',
    date: new Date(Date.now() - 600000), // 10 minutes ago
  },
]

type ActionType = 'post' | 'reply' | 'edit' | 'create'

function getActionIcon(action: ActionType): LucideIcon {
  const icons: Record<ActionType, LucideIcon> = {
    post: BookOpenIcon,
    reply: MessageCircleIcon,
    edit: PencilIcon,
    create: PlusIcon,
  }
  return icons[action]
}

function getActionText(action: ActionType): string {
  const texts: Record<ActionType, string> = {
    post: 'wrote a new post',
    reply: 'replied to a comment',
    edit: 'edited a post',
    create: 'created a new project',
  }
  return texts[action]
}

function getRelativeTimeString(date: Date): string {
  const now = new Date()
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000)

  if (diffInSeconds < 60) {
    return `${diffInSeconds} seconds ago`
  } else if (diffInSeconds < 3600) {
    const minutes = Math.floor(diffInSeconds / 60)
    return `${minutes} ${minutes === 1 ? 'minute' : 'minutes'} ago`
  } else if (diffInSeconds < 86400) {
    const hours = Math.floor(diffInSeconds / 3600)
    return `${hours} ${hours === 1 ? 'hour' : 'hours'} ago`
  } else {
    const days = Math.floor(diffInSeconds / 86400)
    return `${days} ${days === 1 ? 'day' : 'days'} ago`
  }
}

export default function Component() {
  return (
    <div className="space-y-3">
      <div className="text-muted-foreground text-xs font-medium">Activity</div>
      <Timeline>
        {items.map((item) => {
          const ActionIcon = getActionIcon(item.action)
          return (
            <TimelineItem
              key={item.id}
              step={item.id}
              className="m-0! flex-row items-center gap-3 py-2.5!"
            >
              <ActionIcon className="text-muted-foreground/80" size={16} />
              <img src={item.image} alt={item.user} className="size-6 rounded-full" />
              <TimelineContent className="text-foreground">
                <a className="font-medium hover:underline" href="#">
                  {item.user}
                </a>
                <span className="font-normal">
                  {' '}
                  {getActionText(item.action)}{' '}
                  <a className="hover:underline" href="#">
                    {getRelativeTimeString(item.date)}
                  </a>
                </span>
              </TimelineContent>
            </TimelineItem>
          )
        })}
      </Timeline>
    </div>
  )
}

// apps/docs/registry/default/components/timeline/timeline-10.vue
<script setup lang="ts">
import { BookOpenIcon, MessageCircleIcon, PencilIcon, PlusIcon } from 'lucide-vue-next'
import { Timeline } from '@timui/vue'
import { TimelineContent } from '@timui/vue'
import { TimelineItem } from '@timui/vue'

type ActionType = 'post' | 'reply' | 'edit' | 'create'

type ActivityItem = {
  id: number
  user: string
  image: string
  action: ActionType
  date: Date
}

const items: ActivityItem[] = [
  {
    id: 1,
    user: 'Matt',
    image: '/avatar-40-02.jpg',
    action: 'post',
    date: new Date(Date.now() - 59000),
  },
  {
    id: 2,
    user: 'Matt',
    image: '/avatar-40-02.jpg',
    action: 'reply',
    date: new Date(Date.now() - 180000),
  },
  {
    id: 3,
    user: 'Matt',
    image: '/avatar-40-02.jpg',
    action: 'edit',
    date: new Date(Date.now() - 300000),
  },
  {
    id: 4,
    user: 'Matt',
    image: '/avatar-40-02.jpg',
    action: 'create',
    date: new Date(Date.now() - 600000),
  },
]

const iconMap = {
  post: BookOpenIcon,
  reply: MessageCircleIcon,
  edit: PencilIcon,
  create: PlusIcon,
} as const

const textMap: Record<ActionType, string> = {
  post: 'wrote a new post',
  reply: 'replied to a comment',
  edit: 'edited a post',
  create: 'created a new project',
}

const getRelativeTimeString = (date: Date): string => {
  const now = new Date()
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000)

  if (diffInSeconds < 60) {
    return `${diffInSeconds} seconds ago`
  }

  if (diffInSeconds < 3600) {
    const minutes = Math.floor(diffInSeconds / 60)
    return `${minutes} ${minutes === 1 ? 'minute' : 'minutes'} ago`
  }

  if (diffInSeconds < 86400) {
    const hours = Math.floor(diffInSeconds / 3600)
    return `${hours} ${hours === 1 ? 'hour' : 'hours'} ago`
  }

  const days = Math.floor(diffInSeconds / 86400)
  return `${days} ${days === 1 ? 'day' : 'days'} ago`
}
</script>

<template>
  <div class="space-y-3">
    <div class="text-muted-foreground text-xs font-medium">Activity</div>
    <Timeline>
      <TimelineItem
        v-for="item in items"
        :key="item.id"
        :step="item.id"
        class="m-0! flex-row items-center gap-3 py-2.5!"
      >
        <component :is="iconMap[item.action]" class="text-muted-foreground/80" :size="16" />
        <img :src="item.image" :alt="item.user" class="size-6 rounded-full" />
        <TimelineContent class="text-foreground">
          <a class="font-medium hover:underline" href="#">{{ item.user }}</a>
          <span class="font-normal">
            {{ ' ' }}{{ textMap[item.action] }}{{ ' ' }}
            <a class="hover:underline" href="#">{{ getRelativeTimeString(item.date) }}</a>
          </span>
        </TimelineContent>
      </TimelineItem>
    </Timeline>
  </div>
</template>
