// packages/react/src/components/ui/presence.tsx
'use client'

import * as React from 'react'
import { cn } from '@timui/core'
import * as presence from '@zag-js/presence'
import { normalizeProps, useMachine } from '@zag-js/react'

interface PresenceProps extends React.HTMLAttributes<HTMLDivElement> {
  present: boolean
  lazyMount?: boolean
  unmountOnExit?: boolean
}

const Presence = React.forwardRef<HTMLDivElement, PresenceProps>(
  ({ className, present, lazyMount = false, unmountOnExit = false, ...props }, ref) => {
    const service = useMachine(presence.machine as never, {
      present,
    })
    const api = React.useMemo(() => presence.connect(service as never, normalizeProps), [service])

    const isUnmounted = !api.present && !present && unmountOnExit
    const isHidden = !api.present && !present && !unmountOnExit

    if (lazyMount && !api.present && !present) {
      return null
    }

    if (isUnmounted) return null

    return (
      <div
        ref={ref}
        data-slot="presence"
        data-state={present ? 'open' : 'closed'}
        hidden={isHidden}
        className={cn(className)}
        {...props}
      />
    )
  }
)
Presence.displayName = 'Presence'

export { Presence }
export type { PresenceProps }

// registry/vue/lib/presence.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import * as presence from '@zag-js/presence'
import { normalizeProps, useMachine } from '@zag-js/vue'

const props = withDefaults(
  defineProps<{
    present: boolean
    lazyMount?: boolean
    unmountOnExit?: boolean
    asChild?: boolean
  }>(),
  {
    lazyMount: false,
    unmountOnExit: false,
    asChild: false,
  },
)

const emit = defineEmits<{
  'exit-complete': []
}>()

const nodeRef = ref<HTMLElement | null>(null)

const service = useMachine(presence.machine, {
  present: props.present,
  onExitComplete() {
    emit('exit-complete')
  },
})

const api = computed(() => presence.connect(service, normalizeProps))

watch(
  () => nodeRef.value,
  (node) => {
    if (node) {
      api.value.setNode(node)
    }
  },
  { immediate: true },
)

watch(
  () => props.present,
  (present) => {
    api.value.setPresent(present)
  },
  { immediate: true },
)

const unmounted = computed(() => {
  return !api.value.present && !props.present && props.unmountOnExit
})

const hidden = computed(() => {
  if (!api.value.present && !props.present && !props.unmountOnExit) return true
  return false
})

const state = computed(() => (props.present ? 'open' : 'closed'))
</script>

<template>
  <template v-if="unmounted">
    <!-- Unmounted -->
  </template>
  <div
    v-else
    ref="nodeRef"
    :hidden="hidden"
    :data-state="state"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>
