// apps/docs/registry/default/ui/list-box-item.tsx
'use client'

import * as React from 'react'
import { cn, listBoxItemVariants } from '@timui/core'
import { mergeProps } from '@zag-js/react'

import { useListBoxContext } from './list-box/use-list-box-context'

interface ListBoxItemProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'id'> {
  id?: string
  value?: string
  isDisabled?: boolean
  textValue?: string
}

const getTextValue = (node: React.ReactNode): string => {
  if (typeof node === 'string' || typeof node === 'number') return String(node)
  if (Array.isArray(node)) return node.map(getTextValue).join(' ').trim()
  return ''
}

const ListBoxItem = React.forwardRef<HTMLDivElement, ListBoxItemProps>(
  ({ id, value, isDisabled, textValue, className, children, ...props }, ref) => {
    const generatedValue = React.useId()
    const resolvedValue = value ?? id ?? generatedValue
    const textContent = getTextValue(children)
    const resolvedLabel = textValue ?? (textContent || resolvedValue)
    const { api, registerItem, unregisterItem } = useListBoxContext()

    const item = React.useMemo(
      () => ({
        label: resolvedLabel,
        value: resolvedValue,
        disabled: isDisabled,
      }),
      [isDisabled, resolvedLabel, resolvedValue]
    )

    React.useEffect(() => {
      registerItem(item)
      return () => unregisterItem(item.value)
    }, [item, registerItem, unregisterItem])

    const itemState = api.getItemState({ item })
    const mergedItemProps = mergeProps(
      api.getItemProps({ item }),
      props
    ) as React.HTMLAttributes<HTMLDivElement>
    const { className: mergedClassName, ...restItemProps } = mergedItemProps

    return (
      <div
        ref={ref}
        data-slot="list-box-item"
        data-selected={itemState.selected ? 'true' : undefined}
        className={cn(listBoxItemVariants(), className, mergedClassName)}
        {...restItemProps}
      >
        {children}
      </div>
    )
  }
)
ListBoxItem.displayName = 'ListBoxItem'

export { ListBoxItem }

// packages/vue/src/components/ui/list-box-item/list-box-item.vue
<script setup lang="ts">
import { computed, mergeProps, onBeforeUnmount, useAttrs, useId, watch } from 'vue'
import type { HTMLAttributes } from 'vue'
import { cn, listBoxItemVariants, type ListBoxItem } from '@timui/core'

import { useListBoxContext } from '../list-box/use-list-box-context'

defineOptions({
  inheritAttrs: false,
})

const props = defineProps<{
  id?: string
  value?: string
  isDisabled?: boolean
  textValue?: string
  class?: HTMLAttributes['class']
}>()

const attrs = useAttrs()
const generatedId = useId()
const context = useListBoxContext()

const item = computed<ListBoxItem>(() => {
  const value = props.value ?? props.id ?? generatedId
  return {
    value,
    label: props.textValue ?? value,
    disabled: props.isDisabled,
  }
})

watch(
  item,
  (next, prev) => {
    if (prev && prev.value !== next.value) {
      context.unregisterItem(prev.value)
    }
    context.registerItem(next)
  },
  { immediate: true, deep: true }
)

onBeforeUnmount(() => {
  context.unregisterItem(item.value.value)
})

const itemState = computed(() => context.api.value.getItemState({ item: item.value }))
type MergedProps = Record<string, unknown> & { class?: HTMLAttributes['class'] }
const mergedItem = computed(() => {
  const merged = mergeProps(
    context.api.value.getItemProps({ item: item.value }) as MergedProps,
    attrs as MergedProps
  ) as MergedProps
  const mergedClass = merged.class as HTMLAttributes['class']
  const { class: _class, ...restProps } = merged
  return { class: mergedClass, props: restProps as Record<string, unknown> }
})
</script>

<template>
  <div
    v-bind="mergedItem.props"
    data-slot="list-box-item"
    :data-selected="itemState.selected ? 'true' : undefined"
    :class="cn(listBoxItemVariants(), props.class, mergedItem.class)"
  >
    <slot />
  </div>
</template>
