// apps/docs/registry/default/components/popover/popover-04.vue
<script setup lang="ts">
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'
import { Button } from '@/components/ui/button'
</script>
<template>
<Popover>
      <PopoverTrigger asChild>
        <Button variant="outline">Tooltip-like popover</Button>
      </PopoverTrigger>
      <PopoverContent class="max-w-[280px] py-3 shadow-none" side="top">
        <div class="space-y-3">
          <div class="space-y-1">
            <p class="text-[13px] font-medium">Popover with button</p>
            <p class="text-muted-foreground text-xs">
              I am a popover that would like to look like a tooltip. I can&lsquo;t be a tooltip
              because of the interactive element inside me.
            </p>
          </div>
          <Button size="sm" class="h-7 px-2">
            Know more
          </Button>
        </div>
      </PopoverContent>
    </Popover>
</template>

// apps/docs/registry/default/components/popover/popover-04.tsx
import { Button } from '../../ui/button'
import { Popover, PopoverContent, PopoverTrigger } from '../../ui/popover'

export default function Component() {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button variant="outline">Tooltip-like popover</Button>
      </PopoverTrigger>
      <PopoverContent className="max-w-[280px] py-3 shadow-none" side="top">
        <div className="space-y-3">
          <div className="space-y-1">
            <p className="text-[13px] font-medium">Popover with button</p>
            <p className="text-muted-foreground text-xs">
              I am a popover that would like to look like a tooltip. I can&lsquo;t be a tooltip
              because of the interactive element inside me.
            </p>
          </div>
          <Button size="sm" className="h-7 px-2">
            Know more
          </Button>
        </div>
      </PopoverContent>
    </Popover>
  )
}
