// packages/vue/src/components/ui/checkbox/checkbox-tree.vue
<script lang="ts">
import { defineComponent, ref, type PropType, type VNodeChild } from "vue";
import type {
  AssertNoExtraKeys,
  CheckboxTreeNode,
  CheckboxTreeProps as CoreCheckboxTreeProps,
} from "@timui/core";

type CheckboxTreeProps = CoreCheckboxTreeProps<VNodeChild>;
type _CheckboxTreePropsGuard = AssertNoExtraKeys<
  CheckboxTreeProps,
  CoreCheckboxTreeProps<VNodeChild>
>;

export default defineComponent({
  name: "CheckboxTree",
  props: {
    tree: {
      type: Object as () => CheckboxTreeNode,
      required: true,
    },
    renderNode: {
      type: Function as PropType<
        (props: {
          node: CheckboxTreeNode;
          isChecked: boolean | "indeterminate";
          onCheckedChange: () => void;
          children: VNodeChild[] | undefined;
        }) => VNodeChild
      >,
      required: true,
    },
  },
  setup(props) {
    const checkedNodes = ref(new Set<string>());

    const initializeCheckedNodes = (node: CheckboxTreeNode) => {
      if (node.defaultChecked) checkedNodes.value.add(node.id);
      node.children?.forEach(initializeCheckedNodes);
    };

    initializeCheckedNodes(props.tree);

    const isChecked = (node: CheckboxTreeNode): boolean | "indeterminate" => {
      if (!node.children?.length) return checkedNodes.value.has(node.id);

      const childrenChecked = node.children.map((child) => isChecked(child));
      if (childrenChecked.every((status) => status === true)) return true;
      if (childrenChecked.some((status) => status === true || status === "indeterminate")) {
        return "indeterminate";
      }
      return false;
    };

    const handleCheck = (node: CheckboxTreeNode) => {
      const next = new Set(checkedNodes.value);

      const toggleNode = (current: CheckboxTreeNode, check: boolean) => {
        if (check) next.add(current.id);
        else next.delete(current.id);
        current.children?.forEach((child) => toggleNode(child, check));
      };

      const currentStatus = isChecked(node);
      const nextCheck = currentStatus !== true;
      toggleNode(node, nextCheck);

      checkedNodes.value = next;
    };

    const renderTreeNode = (node: CheckboxTreeNode): VNodeChild => {
      const children = node.children?.map(renderTreeNode);
      return props.renderNode({
        node,
        isChecked: isChecked(node),
        onCheckedChange: () => handleCheck(node),
        children,
      });
    };

    return () => renderTreeNode(props.tree);
  },
});
</script>

// packages/react/src/components/ui/checkbox-tree.tsx
/**
 * IMPORTANT: This component was built for demo purposes only and has not been tested in production.
 * It serves as a proof of concept for a checkbox tree implementation.
 * If you're interested in collaborating to create a more robust, production-ready
 * headless component, your contributions are welcome!
 */

'use client'

import React, { useCallback, useMemo, useState } from 'react'
import type {
  AssertNoExtraKeys,
  CheckboxTreeNode,
  CheckboxTreeProps as CoreCheckboxTreeProps,
} from '@timui/core'

type CheckboxTreeProps = CoreCheckboxTreeProps<React.ReactNode>
type _CheckboxTreePropsGuard = AssertNoExtraKeys<
  CheckboxTreeProps,
  CoreCheckboxTreeProps<React.ReactNode>
>

function useCheckboxTree(initialTree: CheckboxTreeNode) {
  const initialCheckedNodes = useMemo(() => {
    const checkedSet = new Set<string>()
    const initializeCheckedNodes = (node: CheckboxTreeNode) => {
      if (node.defaultChecked) {
        checkedSet.add(node.id)
      }
      node.children?.forEach(initializeCheckedNodes)
    }
    initializeCheckedNodes(initialTree)
    return checkedSet
  }, [initialTree])

  const [checkedNodes, setCheckedNodes] = useState<Set<string>>(initialCheckedNodes)

  const isChecked = useCallback(
    (node: CheckboxTreeNode): boolean | 'indeterminate' => {
      if (!node.children) {
        return checkedNodes.has(node.id)
      }

      const childrenChecked = node.children.map((child) => isChecked(child))
      if (childrenChecked.every((status) => status === true)) {
        return true
      }
      if (childrenChecked.some((status) => status === true || status === 'indeterminate')) {
        return 'indeterminate'
      }
      return false
    },
    [checkedNodes]
  )

  const handleCheck = useCallback(
    (node: CheckboxTreeNode) => {
      const newCheckedNodes = new Set(checkedNodes)

      const toggleNode = (n: CheckboxTreeNode, check: boolean) => {
        if (check) {
          newCheckedNodes.add(n.id)
        } else {
          newCheckedNodes.delete(n.id)
        }
        n.children?.forEach((child) => toggleNode(child, check))
      }

      const currentStatus = isChecked(node)
      const newCheck = currentStatus !== true

      toggleNode(node, newCheck)
      setCheckedNodes(newCheckedNodes)
    },
    [checkedNodes, isChecked]
  )

  return { isChecked, handleCheck }
}

export function CheckboxTree({ tree, renderNode }: CheckboxTreeProps) {
  const { isChecked, handleCheck } = useCheckboxTree(tree)

  const renderTreeNode = (node: CheckboxTreeNode): React.ReactNode => {
    const children = node.children?.map(renderTreeNode)

    return renderNode({
      node,
      isChecked: isChecked(node),
      onCheckedChange: () => handleCheck(node),
      children,
    }) as React.ReactNode
  }

  return renderTreeNode(tree)
}
