// packages/vue/packages/vue/src/components/advanced/date-picker/date-picker.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { AssertNoExtraKeys, DatePickerVueProps } from '@timui/core'
import {
  cn,
  datePickerContentVariants,
  datePickerRootVariants,
  datePickerTriggerButtonVariants,
  datePickerTriggerIconVariants,
  datePickerTriggerLabelEmptyVariants,
  datePickerTriggerLabelVariants,
  datePickerTriggerVariants,
} from '@timui/core'
import Button from './button.vue'
import Calendar from './calendar.vue'
import Popover from './popover.vue'
import PopoverTrigger from './popover-trigger.vue'
import PopoverContent from './popover-content.vue'

type DatePickerProps = DatePickerVueProps & {
  class?: string
  triggerClass?: string
  contentClass?: string
}
type _DatePickerPropsGuard = AssertNoExtraKeys<
  DatePickerProps,
  DatePickerVueProps & {
    class?: string
    triggerClass?: string
    contentClass?: string
  }
>

const props = withDefaults(defineProps<DatePickerProps>(), {
  mode: 'single',
  placeholder: 'Date',
})

type DatePickerValue = DatePickerProps['modelValue']
type RangeValue = { from?: Date; to?: Date } | undefined

const emit = defineEmits(['update:modelValue', 'change'])

const internalValue = ref<DatePickerValue>(props.modelValue ?? props.defaultValue)
const calendarValue = computed(() =>
  props.mode === 'range'
    ? (internalValue.value as RangeValue)
    : internalValue.value instanceof Date
      ? internalValue.value
      : undefined
)

watch(
  () => props.modelValue,
  (val) => {
    if (val !== undefined) internalValue.value = val
  }
)

watch(
  () => [props.mode, internalValue.value] as const,
  ([mode, value]) => {
    if (mode === 'single' && value && !(value instanceof Date)) {
      const next = (value as RangeValue)?.from
      if (next !== value) setValue(next)
      return
    }
    if (mode === 'range' && value instanceof Date) {
      setValue({ from: value, to: undefined })
    }
  }
)

const setValue = (next: DatePickerValue) => {
  internalValue.value = next
  emit('update:modelValue', next)
  emit('change', next)
}

const formatDate = (date: Date) =>
  new Intl.DateTimeFormat('en-US', { month: 'short', day: '2-digit', year: 'numeric' }).format(
    date
  )

const label = computed(() => {
  const selected = internalValue.value
  if (props.mode === 'range') {
    if (!selected || !(selected as RangeValue)?.from) return ''
    const range = selected as Exclude<RangeValue, undefined>
    if (range.from && range.to) return `${formatDate(range.from)} - ${formatDate(range.to)}`
    if (range.from) return formatDate(range.from)
    return ''
  }
  return selected instanceof Date ? formatDate(selected) : ''
})
</script>

<template>
  <div data-slot="date-picker" :class="cn(datePickerRootVariants(), props.class)">
    <Popover>
      <PopoverTrigger as-child :class="datePickerTriggerVariants()">
        <Button
          variant="outline"
          size="sm"
          :class="cn(datePickerTriggerButtonVariants(), props.triggerClass)"
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            :class="datePickerTriggerIconVariants()"
            aria-hidden="true"
          >
            <rect x="3" y="4" width="18" height="18" rx="2" />
            <path d="M8 2v4" />
            <path d="M16 2v4" />
            <path d="M3 10h18" />
          </svg>
          <span :class="cn(datePickerTriggerLabelVariants(), !label && datePickerTriggerLabelEmptyVariants())">
            {{ label || props.placeholder }}
          </span>
        </Button>
      </PopoverTrigger>
      <PopoverContent
        data-slot="date-picker-content"
        align="start"
        :class="cn(datePickerContentVariants(), props.contentClass)"
      >
        <Calendar
          :mode="props.mode"
          :model-value="calendarValue"
          @update:model-value="setValue"
        />
      </PopoverContent>
    </Popover>
  </div>
</template>

// packages/react/src/components/ui/date-picker.tsx
'use client'

import * as React from 'react'
import {
  cn,
  datePickerContentVariants,
  datePickerRootVariants,
  datePickerTriggerButtonVariants,
  datePickerTriggerIconVariants,
  datePickerTriggerLabelEmptyVariants,
  datePickerTriggerLabelVariants,
  datePickerTriggerVariants,
} from '@timui/core'

import { Button } from './button'
import { Calendar } from './calendar'
import type { CalendarRangeValue } from './calendar'
import { Popover, PopoverContent, PopoverTrigger } from './popover'

type DatePickerMode = 'single' | 'range'

type DatePickerValue = Date | CalendarRangeValue | undefined

interface DatePickerProps {
  mode?: DatePickerMode
  value?: DatePickerValue
  defaultValue?: DatePickerValue
  onValueChange?: (value: DatePickerValue) => void
  placeholder?: string
  className?: string
  triggerClassName?: string
  contentClassName?: string
  calendarProps?: Omit<React.ComponentProps<typeof Calendar>, 'mode' | 'selected' | 'onSelect'>
}

const formatSingle = (value: Date) =>
  new Intl.DateTimeFormat('en-US', { month: 'short', day: '2-digit', year: 'numeric' }).format(
    value
  )
const formatRange = (value: CalendarRangeValue) => {
  if (value.from && value.to) {
    return `${formatSingle(value.from)} - ${formatSingle(value.to)}`
  }
  if (value.from) {
    return formatSingle(value.from)
  }
  return ''
}

function DatePicker({
  mode = 'single',
  value,
  defaultValue,
  onValueChange,
  placeholder = 'Date',
  className,
  triggerClassName,
  contentClassName,
  calendarProps,
}: DatePickerProps) {
  const isControlled = value !== undefined
  const [uncontrolled, setUncontrolled] = React.useState<DatePickerValue>(defaultValue)
  const selected = isControlled ? value : uncontrolled
  const calendarSelected =
    mode === 'range'
      ? (selected as CalendarRangeValue | undefined)
      : selected instanceof Date
        ? selected
        : undefined

  const handleChange = React.useCallback(
    (next: DatePickerValue) => {
      if (!isControlled) setUncontrolled(next)
      onValueChange?.(next)
    },
    [isControlled, onValueChange]
  )

  const label = React.useMemo(() => {
    if (mode === 'range') {
      return selected && typeof selected === 'object' && 'from' in selected
        ? formatRange(selected as CalendarRangeValue)
        : ''
    }
    return selected instanceof Date ? formatSingle(selected) : ''
  }, [mode, selected])

  React.useEffect(() => {
    if (mode === 'single' && selected && typeof selected === 'object' && 'from' in selected) {
      const next = selected.from ?? undefined
      if (next !== selected.from) handleChange(next)
      return
    }
    if (mode === 'range' && selected instanceof Date) {
      handleChange({ from: selected, to: undefined })
    }
  }, [mode, selected, handleChange])

  return (
    <div data-slot="date-picker" className={cn(datePickerRootVariants(), className)}>
      <Popover>
        <PopoverTrigger
          asChild
          data-slot="date-picker-trigger"
          className={datePickerTriggerVariants()}
        >
          <Button
            variant="outline"
            size="sm"
            className={cn(datePickerTriggerButtonVariants(), triggerClassName)}
          >
            <svg
              width={16}
              height={16}
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className={datePickerTriggerIconVariants()}
              aria-hidden="true"
            >
              <rect x="3" y="4" width="18" height="18" rx="2" />
              <path d="M8 2v4" />
              <path d="M16 2v4" />
              <path d="M3 10h18" />
            </svg>
            <span
              className={cn(
                datePickerTriggerLabelVariants(),
                !label && datePickerTriggerLabelEmptyVariants()
              )}
            >
              {label || placeholder}
            </span>
          </Button>
        </PopoverTrigger>
        <PopoverContent
          data-slot="date-picker-content"
          className={cn(datePickerContentVariants(), contentClassName)}
          align="start"
        >
          <Calendar
            mode={mode}
            selected={calendarSelected as never}
            onSelect={(next) => handleChange(next as DatePickerValue)}
            {...calendarProps}
          />
        </PopoverContent>
      </Popover>
    </div>
  )
}

export { DatePicker }
export type { DatePickerProps, DatePickerMode, DatePickerValue }
