// packages/vue/src/components/ui/number-field/number-field.vue
<script setup lang="ts">
import { computed, watch, useAttrs, useId } from 'vue'
import { normalizeProps, useMachine } from '@zag-js/vue'
import {
  cn,
  numberFieldConnect,
  numberFieldMachine,
  type NumberFieldMachine,
} from '@timui/core'
import type { Machine as ZagMachine, MachineSchema as ZagMachineSchema } from '@zag-js/core'
import type { HTMLAttributes } from 'vue'
import { NumberFieldProvider } from './use-number-field-context'

defineOptions({
  inheritAttrs: false,
})

type NumberFieldProps = {
  id?: string
  modelValue?: number | string
  defaultValue?: number | string
  min?: number
  max?: number
  minValue?: number | string
  maxValue?: number | string
  step?: number
  formatOptions?: Intl.NumberFormatOptions
  inputMode?: 'text' | 'tel' | 'numeric' | 'decimal'
  allowMouseWheel?: boolean
  allowOverflow?: boolean
  clampValueOnBlur?: boolean
  focusInputOnChange?: boolean
  disabled?: boolean
  readOnly?: boolean
  required?: boolean
  invalid?: boolean
  class?: HTMLAttributes['class']
}

const props = withDefaults(defineProps<NumberFieldProps>(), {
  step: 1,
})

const emit = defineEmits<{
  (e: 'update:modelValue', value?: number): void
  (e: 'change', value?: number): void
}>()

const attrs = useAttrs()
const generatedId = useId()

const toNumber = (value?: number | string) => {
  if (value === undefined || value === null || value === '') return undefined
  const num = typeof value === 'string' ? Number(value) : value
  return Number.isFinite(num) ? num : undefined
}

const machineProps = computed(() => {
  const resolvedMin = props.min ?? toNumber(props.minValue)
  const resolvedMax = props.max ?? toNumber(props.maxValue)
  const controlledValue =
    props.modelValue !== undefined ? String(props.modelValue) : undefined
  const defaultValue =
    props.modelValue === undefined && props.defaultValue !== undefined
      ? String(props.defaultValue)
      : undefined

  return {
    id: props.id ?? generatedId,
    value: controlledValue,
    defaultValue,
    min: resolvedMin,
    max: resolvedMax,
    step: props.step,
    formatOptions: props.formatOptions,
    inputMode: props.inputMode,
    allowMouseWheel: props.allowMouseWheel,
    allowOverflow: props.allowOverflow,
    clampValueOnBlur: props.clampValueOnBlur,
    focusInputOnChange: props.focusInputOnChange,
    disabled: props.disabled,
    readOnly: props.readOnly,
    required: props.required,
    invalid: props.invalid,
    onValueChange(details: { value: string; valueAsNumber: number }) {
      const next = Number.isFinite(details.valueAsNumber) ? details.valueAsNumber : undefined
      emit('update:modelValue', next)
      emit('change', next)
    },
  }
})

type InferMachineSchema<T> = T extends ZagMachine<infer S> ? S : ZagMachineSchema
type NumberFieldSchema = InferMachineSchema<NumberFieldMachine>

const service = useMachine<NumberFieldSchema>(numberFieldMachine, machineProps)
const api = computed(() => numberFieldConnect(service, normalizeProps))

watch(
  () => props.modelValue,
  (next) => {
    const numeric = toNumber(next)
    if (numeric !== undefined && api.value?.valueAsNumber !== numeric) {
      api.value?.setValue(numeric)
    }
  }
)

NumberFieldProvider(api)

const rootProps = computed(() => {
  const baseProps = api.value?.getRootProps?.() ?? {}
  return {
    ...baseProps,
    ...attrs,
    class: cn(props.class, (attrs.class as string) || ''),
    'data-slot': 'number-field',
  }
})
</script>

<template>
  <div v-bind="rootProps">
    <slot />
  </div>
</template>

// packages/react/src/components/ui/number-field.tsx
'use client'

import * as React from 'react'
import {
  cn,
  numberFieldConnect,
  numberFieldMachine,
  type NumberFieldApi,
  type NumberFieldFocusChangeDetails,
  type NumberFieldInputMode,
  type NumberFieldIntlTranslations,
  type NumberFieldMachine,
  type NumberFieldValueChangeDetails,
  type NumberFieldValueInvalidDetails,
} from '@timui/core'
import type { Machine as ZagMachine, MachineSchema as ZagMachineSchema } from '@zag-js/core'
import { mergeProps, normalizeProps, useMachine } from '@zag-js/react'

import { Slot } from './slot'

type NumberFieldProps = Omit<
  React.HTMLAttributes<HTMLDivElement>,
  'defaultValue' | 'onChange' | 'value'
> & {
  id?: string
  value?: number | string
  defaultValue?: number | string
  min?: number
  max?: number
  minValue?: number | string
  maxValue?: number | string
  step?: number
  formatOptions?: Intl.NumberFormatOptions
  inputMode?: NumberFieldInputMode
  allowMouseWheel?: boolean
  allowOverflow?: boolean
  clampValueOnBlur?: boolean
  focusInputOnChange?: boolean
  disabled?: boolean
  readOnly?: boolean
  required?: boolean
  invalid?: boolean
  name?: string
  form?: string
  dir?: 'ltr' | 'rtl'
  locale?: string
  translations?: NumberFieldIntlTranslations
  spinOnPress?: boolean
  onValueChange?: (value?: number) => void
  onChange?: (value?: number) => void
  onValueInvalid?: (details: NumberFieldValueInvalidDetails) => void
  onFocusChange?: (details: NumberFieldFocusChangeDetails) => void
  onValueCommit?: (details: NumberFieldValueChangeDetails) => void
}

const NumberFieldContext = React.createContext<NumberFieldApi | null>(null)

type InferMachineSchema<T> = T extends ZagMachine<infer S> ? S : ZagMachineSchema
type NumberFieldSchema = InferMachineSchema<NumberFieldMachine>

const useNumberFieldContext = () => {
  const context = React.useContext(NumberFieldContext)
  if (!context) {
    throw new Error('NumberField subcomponents must be used within <NumberField>')
  }
  return context
}

const toNumber = (value?: number | string) => {
  if (value === undefined || value === null || value === '') return undefined
  const num = typeof value === 'string' ? Number(value) : value
  return Number.isFinite(num) ? num : undefined
}

const toStringValue = (value?: number | string) => {
  if (value === undefined || value === null || value === '') return undefined
  return String(value)
}

const NumberField = React.forwardRef<HTMLDivElement, NumberFieldProps>(
  (
    {
      className,
      id,
      value,
      defaultValue,
      min,
      max,
      minValue,
      maxValue,
      step = 1,
      formatOptions,
      inputMode,
      allowMouseWheel,
      allowOverflow,
      clampValueOnBlur,
      focusInputOnChange,
      disabled,
      readOnly,
      required,
      invalid,
      name,
      form,
      dir,
      locale,
      translations,
      spinOnPress,
      onValueChange,
      onChange,
      onValueInvalid,
      onFocusChange,
      onValueCommit,
      ...props
    },
    ref
  ) => {
    const generatedId = React.useId()
    const resolvedMin = min ?? toNumber(minValue)
    const resolvedMax = max ?? toNumber(maxValue)
    const controlledValue = toStringValue(value)
    const uncontrolledDefaultValue =
      value === undefined ? toStringValue(defaultValue) : undefined

    const service = useMachine<NumberFieldSchema>(numberFieldMachine, {
      id: id ?? generatedId,
      value: controlledValue,
      defaultValue: uncontrolledDefaultValue,
      min: resolvedMin,
      max: resolvedMax,
      step,
      formatOptions,
      inputMode,
      allowMouseWheel,
      allowOverflow,
      clampValueOnBlur,
      focusInputOnChange,
      disabled,
      readOnly,
      required,
      invalid,
      name,
      form,
      dir,
      locale,
      translations,
      spinOnPress,
      onValueInvalid,
      onFocusChange,
      onValueCommit,
      onValueChange(details: NumberFieldValueChangeDetails) {
        const next = Number.isFinite(details.valueAsNumber) ? details.valueAsNumber : undefined
        onValueChange?.(next)
        onChange?.(next)
      },
    })

    const api = React.useMemo(() => numberFieldConnect(service, normalizeProps), [service])
    const rootProps = api.getRootProps()
    const mergedProps = mergeProps(rootProps, props) as React.HTMLAttributes<HTMLDivElement>
    const { className: mergedClassName, ...restProps } = mergedProps

    return (
      <NumberFieldContext.Provider value={api}>
        <div
          ref={ref}
          data-slot="number-field"
          className={cn(className, mergedClassName)}
          {...restProps}
        />
      </NumberFieldContext.Provider>
    )
  }
)
NumberField.displayName = 'NumberField'

type NumberFieldControlProps = React.ComponentPropsWithoutRef<'div'> & {
  asChild?: boolean
}

const NumberFieldControl = React.forwardRef<HTMLDivElement, NumberFieldControlProps>(
  ({ asChild = false, className, ...props }, ref) => {
    const api = useNumberFieldContext()
    const Comp = asChild ? Slot : 'div'
    const controlProps = api.getControlProps()
    const mergedProps = mergeProps(controlProps, props) as React.HTMLAttributes<HTMLDivElement>
    const { className: mergedClassName, ...restProps } = mergedProps

    return (
      <Comp
        ref={ref}
        data-slot="number-field-control"
        className={cn(className, mergedClassName)}
        {...restProps}
      />
    )
  }
)
NumberFieldControl.displayName = 'NumberFieldControl'

type NumberFieldInputProps = React.ComponentPropsWithoutRef<'input'> & {
  asChild?: boolean
}

const NumberFieldInput = React.forwardRef<HTMLInputElement, NumberFieldInputProps>(
  ({ asChild = false, className, ...props }, ref) => {
    const api = useNumberFieldContext()
    const Comp = asChild ? Slot : 'input'
    const inputProps = api.getInputProps()
    const mergedProps = mergeProps(inputProps, props) as React.InputHTMLAttributes<HTMLInputElement>
    const { className: mergedClassName, ...restProps } = mergedProps

    return (
      <Comp
        ref={ref}
        data-slot="number-field-input"
        className={cn(className, mergedClassName)}
        {...restProps}
      />
    )
  }
)
NumberFieldInput.displayName = 'NumberFieldInput'

type NumberFieldIncrementProps = React.ComponentPropsWithoutRef<'button'> & {
  asChild?: boolean
}

const NumberFieldIncrement = React.forwardRef<HTMLButtonElement, NumberFieldIncrementProps>(
  ({ asChild = false, className, type, ...props }, ref) => {
    const api = useNumberFieldContext()
    const Comp = asChild ? Slot : 'button'
    const incrementProps = api.getIncrementTriggerProps()
    const mergedProps = mergeProps(incrementProps, props) as React.ButtonHTMLAttributes<HTMLButtonElement>
    const { className: mergedClassName, type: mergedType, ...restProps } = mergedProps

    return (
      <Comp
        ref={ref}
        data-slot="number-field-increment"
        className={cn(className, mergedClassName)}
        type={asChild ? type : (type ?? mergedType ?? 'button')}
        {...restProps}
      />
    )
  }
)
NumberFieldIncrement.displayName = 'NumberFieldIncrement'

type NumberFieldDecrementProps = React.ComponentPropsWithoutRef<'button'> & {
  asChild?: boolean
}

const NumberFieldDecrement = React.forwardRef<HTMLButtonElement, NumberFieldDecrementProps>(
  ({ asChild = false, className, type, ...props }, ref) => {
    const api = useNumberFieldContext()
    const Comp = asChild ? Slot : 'button'
    const decrementProps = api.getDecrementTriggerProps()
    const mergedProps = mergeProps(decrementProps, props) as React.ButtonHTMLAttributes<HTMLButtonElement>
    const { className: mergedClassName, type: mergedType, ...restProps } = mergedProps

    return (
      <Comp
        ref={ref}
        data-slot="number-field-decrement"
        className={cn(className, mergedClassName)}
        type={asChild ? type : (type ?? mergedType ?? 'button')}
        {...restProps}
      />
    )
  }
)
NumberFieldDecrement.displayName = 'NumberFieldDecrement'

export { NumberField, NumberFieldControl, NumberFieldInput, NumberFieldIncrement, NumberFieldDecrement }
