// packages/vue/src/components/ui/switch/switch.vue
<script setup lang="ts">
import { computed, type HTMLAttributes } from 'vue'
import { normalizeProps, useMachine } from '@zag-js/vue'
import type { AssertNoExtraKeys, SwitchVueProps } from '@timui/core'
import { switchConnect, switchMachine } from '@timui/core'
import { cn, switchRootVariants, switchThumbVariants, switchVariants } from '@timui/core'

import { useSwitch } from './use-switch'

type SwitchProps = SwitchVueProps & { class?: HTMLAttributes['class'] }
type _SwitchPropsGuard = AssertNoExtraKeys<SwitchProps, SwitchProps>

const props = defineProps<SwitchProps>()

const emit = defineEmits(['update:modelValue', 'change'])

const api = useSwitch(props, emit)
const rootProps = computed(() => api.value?.getRootProps?.() ?? {})
const controlProps = computed(() => api.value?.getControlProps?.() ?? {})
const thumbProps = computed(() => api.value?.getThumbProps?.() ?? {})
const hiddenInputProps = computed(() => api.value?.getHiddenInputProps?.() ?? {})
</script>

<template>
  <label
    v-bind="rootProps"
    data-slot="switch-root"
    :class="cn(switchRootVariants(), rootProps.class)"
  >
    <button
      v-bind="controlProps"
      type="button"
      data-slot="switch"
      :class="cn(switchVariants(), controlProps.class, props.class)"
    >
      <span
        v-bind="thumbProps"
        data-slot="switch-thumb"
        :class="cn(switchThumbVariants(), thumbProps.class)"
      />
    </button>
    <input v-bind="hiddenInputProps" />
  </label>
</template>

// packages/react/src/components/ui/switch.tsx
'use client'

import * as React from 'react'
import type { SwitchProps as CoreSwitchProps } from '@timui/core'
import {
  cn,
  createTimEvent,
  switchConnect,
  switchMachine,
  switchRootVariants,
  switchThumbVariants,
  switchVariants,
} from '@timui/core'
import { mergeProps } from '@zag-js/react'

import { useSwitch } from './switch/use-switch'

type SwitchProps = CoreSwitchProps &
  Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, keyof CoreSwitchProps>

const Switch = React.forwardRef<HTMLButtonElement, SwitchProps>(
  (
    {
      className,
      checked,
      defaultChecked,
      required,
      onCheckedChange,
      value = 'on',
      disabled,
      name,
      id,
      ...props
    },
    ref
  ) => {
    const api = useSwitch({
      id,
      checked,
      defaultChecked,
      required,
      onCheckedChange,
      value: value ?? 'on',
      disabled,
      name,
    })
    const rootProps = api.getRootProps()
    const controlProps = api.getControlProps()
    const thumbProps = api.getThumbProps()
    const hiddenInputProps = api.getHiddenInputProps()
    const mergedControlProps = mergeProps(controlProps, props)
    const { className: controlClassName, ...controlRest } = mergedControlProps

    return (
      <label
        {...rootProps}
        data-slot="switch-root"
        className={cn(switchRootVariants(), rootProps.className)}
      >
        <button
          {...controlRest}
          ref={ref}
          type="button"
          data-slot="switch"
          className={cn(switchVariants(), controlClassName, className)}
        >
          <span
            {...thumbProps}
            data-slot="switch-thumb"
            className={cn(switchThumbVariants(), thumbProps.className)}
          />
        </button>
        <input {...hiddenInputProps} />
      </label>
    )
  }
)
Switch.displayName = 'Switch'

export { Switch }
