// apps/docs/registry/default/vue/tabs.vue
<script setup lang="ts">
import { computed, provide, type HTMLAttributes } from "vue";
import { normalizeProps, useMachine } from "@zag-js/vue";
import { tabsConnect, tabsMachine } from "@timui/core";
import { cn } from "@timui/core";

const props = defineProps<{
  modelValue?: string;
  value?: string;
  defaultValue?: string;
  id?: string;
  orientation?: "horizontal" | "vertical";
  activationMode?: "manual" | "automatic";
  loopFocus?: boolean;
  composite?: boolean;
  deselectable?: boolean;
  class?: HTMLAttributes["class"];
}>();

const emit = defineEmits(["update:modelValue", "change", "focusChange"]);

const machineProps = computed(() => {
  const value = props.value ?? props.modelValue ?? null;
  return {
    id: props.id,
    value,
    defaultValue: value == null ? props.defaultValue ?? null : undefined,
    orientation: props.orientation,
    activationMode: props.activationMode,
    loopFocus: props.loopFocus,
    composite: props.composite,
    deselectable: props.deselectable,
    onValueChange(details: { value: string }) {
      emit("update:modelValue", details.value);
      emit("change", details.value);
    },
    onFocusChange(details: { focusedValue: string }) {
      emit("focusChange", details.focusedValue);
    },
  };
});

const service = useMachine(tabsMachine, machineProps);
const api = computed(() => tabsConnect(service, normalizeProps));

provide("tabs", { api });
</script>

<template>
  <div v-bind="api.getRootProps()" data-slot="tabs" :class="cn(props.class)">
    <slot />
  </div>
</template>

// packages/react/src/components/ui/tabs.tsx
'use client'

import * as React from 'react'
import { cn, tabsContentVariants, tabsListVariants, tabsTriggerVariants } from '@timui/core'
import { mergeProps } from '@zag-js/react'

import { Slot } from './slot'
import { useTabs, type UseTabsProps } from './tabs/use-tabs'
import { TabsProvider, useTabsContext } from './tabs/use-tabs-context'

const Tabs = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & {
    value?: string
    defaultValue?: string
    onValueChange?: (value: string) => void
    onFocusChange?: (value: string) => void
    orientation?: 'horizontal' | 'vertical'
    activationMode?: 'manual' | 'automatic'
    loopFocus?: boolean
    composite?: boolean
    deselectable?: boolean
    id?: string
  }
>(
  (
    {
      className,
      value,
      defaultValue,
      onValueChange,
      onFocusChange,
      orientation,
      activationMode,
      loopFocus,
      composite,
      deselectable,
      id,
      ...props
    },
    ref
  ) => {
    const api = useTabs({
      value,
      defaultValue,
      onValueChange,
      onFocusChange,
      orientation,
      activationMode,
      loopFocus,
      composite,
      deselectable,
      id,
    })
    const rootProps = api.getRootProps()
    const mergedProps = mergeProps(rootProps, props) as React.HTMLAttributes<HTMLDivElement>
    const { className: mergedClassName, ...restProps } = mergedProps

    return (
      <TabsProvider value={api}>
        <div ref={ref} data-slot="tabs" className={cn(className, mergedClassName)} {...restProps} />
      </TabsProvider>
    )
  }
)
Tabs.displayName = 'Tabs'

const TabsList = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => {
    const api = useTabsContext()
    const listProps = api.getListProps()
    const mergedProps = mergeProps(listProps, props) as React.HTMLAttributes<HTMLDivElement>
    const { className: mergedClassName, ...restProps } = mergedProps
    return (
      <div
        ref={ref}
        data-slot="tabs-list"
        className={cn(tabsListVariants(), className, mergedClassName)}
        {...restProps}
      />
    )
  }
)
TabsList.displayName = 'TabsList'

const TabsTrigger = React.forwardRef<
  HTMLButtonElement,
  React.ButtonHTMLAttributes<HTMLButtonElement> & { value: string; asChild?: boolean }
>(({ className, value, asChild = false, ...props }, ref) => {
  const api = useTabsContext()
  const Comp = asChild ? Slot : 'button'
  const triggerProps = api.getTriggerProps({ value, disabled: props.disabled })
  const mergedProps = mergeProps(
    triggerProps,
    props
  ) as React.ButtonHTMLAttributes<HTMLButtonElement>
  const { className: mergedClassName, type: mergedType, ...restProps } = mergedProps
  const finalType = asChild ? mergedType : (mergedType ?? 'button')

  return (
    <Comp
      ref={ref}
      data-slot="tabs-trigger"
      type={finalType}
      className={cn(tabsTriggerVariants(), className, mergedClassName)}
      {...restProps}
    />
  )
})
TabsTrigger.displayName = 'TabsTrigger'

const TabsContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & { value: string }
>(({ className, value, ...props }, ref) => {
  const api = useTabsContext()
  const isSelected = api.value === value

  if (!isSelected) return null

  const contentProps = api.getContentProps({ value })
  const mergedProps = mergeProps(contentProps, props) as React.HTMLAttributes<HTMLDivElement>
  const { className: mergedClassName, ...restProps } = mergedProps

  return (
    <div
      ref={ref}
      data-slot="tabs-content"
      role="tabpanel"
      data-state={isSelected ? 'active' : 'inactive'}
      className={cn(tabsContentVariants(), className, mergedClassName)}
      {...restProps}
    />
  )
})
TabsContent.displayName = 'TabsContent'

export { Tabs, TabsList, TabsTrigger, TabsContent }
