// packages/vue/src/components/ui/textarea/textarea.vue
<script setup lang="ts">
import type { AssertNoExtraKeys, TextareaVueProps, TextInputValueChangeEvent } from "@timui/core";
import { cn, textareaVariants, createTimEvent } from "@timui/core";
import { computed, type HTMLAttributes, useId } from "vue";

type TextareaProps = TextareaVueProps & { class?: HTMLAttributes["class"] };
type _TextareaPropsGuard = AssertNoExtraKeys<
  TextareaProps,
  TextareaVueProps & { class?: HTMLAttributes["class"] }
>;

const props = defineProps<TextareaProps>();

const emits = defineEmits<{
  (e: "update:modelValue", payload: string | number): void;
  (e: "valueChange", event: TextInputValueChangeEvent): void;
}>();

const modelValue = computed({
  get: () => props.modelValue,
  set: (value) => {
    emits("update:modelValue", value as string | number);
  },
});

const generatedId = useId()
const textareaId = computed(() => props.id ?? generatedId)

const handleChange = (event: Event) => {
  const target = event.target as HTMLTextAreaElement
  if (props.onValueChange) {
    props.onValueChange(createTimEvent('change', textareaId.value, { value: target.value }))
  }
  emits('valueChange', createTimEvent('change', textareaId.value, { value: target.value }))
}
</script>

<template>
  <textarea
    v-model="modelValue"
    data-slot="textarea"
    :id="textareaId"
    :class="cn(textareaVariants(), props.class)"
    @input="handleChange"
  />
</template>

// packages/react/src/components/ui/textarea.tsx
'use client'

import * as React from 'react'
import type { TextareaProps as CoreTextareaProps } from '@timui/core'
import { cn, textareaVariants, createTimEvent } from '@timui/core'

type TextareaProps = CoreTextareaProps &
  Omit<React.ComponentProps<'textarea'>, keyof CoreTextareaProps>

function Textarea({ className, id, onValueChange, onChange, ...props }: TextareaProps) {
  const generatedId = React.useId()
  const textareaId = id ?? generatedId
  const handleChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    onChange?.(event)
    onValueChange?.(createTimEvent('change', textareaId, { value: event.target.value }))
  }

  return (
    <textarea
      data-slot="textarea"
      className={cn(textareaVariants(), className)}
      onChange={handleChange}
      {...props}
    />
  )
}
Textarea.displayName = 'Textarea'

export { Textarea }
