// packages/vue/src/components/ui/toggle/toggle-group.vue
<script lang="ts">
import { type ToggleVariants } from '@timui/core'
</script>

<script setup lang="ts">
import { cn, toggleGroupVariants } from '@timui/core'
import { computed, type HTMLAttributes } from 'vue'
import { provideToggleGroupContext, type ToggleGroupContextValue } from './use-toggle-group-context'
import { useToggleGroup } from './use-toggle-group'

const props = withDefaults(
  defineProps<{
    id?: string
    class?: HTMLAttributes['class']
    variant?: ToggleGroupContextValue['variant']
    size?: ToggleGroupContextValue['size']
    type?: 'single' | 'multiple'
    modelValue?: string | string[]
    value?: string | string[]
    defaultValue?: string | string[]
    disabled?: boolean
    loop?: boolean
  }>(),
  {
    type: 'single',
    variant: 'default',
    size: 'default',
  },
)

const emit = defineEmits(['update:modelValue', 'change'])

const toArray = (value?: string | string[] | null) => {
  if (value == null) return undefined
  return Array.isArray(value) ? value : value === '' ? [] : [value]
}

const api = useToggleGroup({
  id: props.id,
  multiple: props.type === 'multiple',
  disabled: props.disabled,
  loop: props.loop,
  value: toArray(props.value ?? props.modelValue),
  defaultValue: toArray(props.value ?? props.modelValue) === undefined ? toArray(props.defaultValue) : undefined,
  onValueChange(value: string[]) {
    const nextValue = props.type === 'multiple' ? value : value[0] || ''
    emit('update:modelValue', nextValue)
    emit('change', nextValue)
  },
})

provideToggleGroupContext({
  variant: props.variant,
  size: props.size,
  api,
  type: props.type,
  disabled: props.disabled,
})
</script>

<template>
  <div
    v-bind="api.getRootProps()"
    data-slot="toggle-group"
    :class="cn(toggleGroupVariants(), props.class)"
    role="group"
  >
    <slot />
  </div>
</template>

// packages/react/src/components/ui/toggle-group.tsx
'use client'

import * as React from 'react'
import { cn, toggleGroupVariants, toggleVariants, type ToggleVariants } from '@timui/core'
import { mergeProps } from '@zag-js/react'

import { useToggleGroup } from './toggle-group/use-toggle-group'
import { ToggleGroupProvider, useToggleGroupContext } from './toggle-group/use-toggle-group-context'

// Context is imported from ./toggle-group/use-toggle-group-context

const ToggleGroup = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> &
    ToggleVariants & {
      type: 'single' | 'multiple'
      value?: string | string[]
      defaultValue?: string | string[]
      onValueChange?: (value: string | string[]) => void
      disabled?: boolean
      loop?: boolean
    }
>(
  (
    {
      className,
      variant,
      size,
      children,
      id,
      type,
      value,
      defaultValue,
      onValueChange,
      disabled,
      loop,
      ...props
    },
    ref
  ) => {
    const api = useToggleGroup({
      id,
      multiple: type === 'multiple',
      value,
      defaultValue,
      onValueChange,
      disabled,
      loop,
    })
    const rootProps = api.getRootProps()
    const mergedProps = mergeProps(rootProps, props) as React.HTMLAttributes<HTMLDivElement>
    const { className: mergedClassName, ...restProps } = mergedProps

    return (
      <ToggleGroupProvider
        value={{
          api,
          size,
          variant,
          type,
          disabled,
        }}
      >
        <div
          ref={ref}
          data-slot="toggle-group"
          role="group"
          className={cn(toggleGroupVariants(), className, mergedClassName)}
          {...restProps}
        >
          {children}
        </div>
      </ToggleGroupProvider>
    )
  }
)
ToggleGroup.displayName = 'ToggleGroup'

const ToggleGroupItem = React.forwardRef<
  HTMLButtonElement,
  React.ButtonHTMLAttributes<HTMLButtonElement> & { value: string }
>(({ className, children, value, ...props }, ref) => {
  const context = useToggleGroupContext()
  const api = context.api
  const itemState = api?.getItemState?.({ value, disabled: props.disabled }) ?? {
    pressed: false,
    disabled: false,
  }
  const itemProps = api?.getItemProps?.({ value, disabled: props.disabled }) ?? {}
  const mergedProps = mergeProps(itemProps, props)
  const { className: mergedClassName, ...restProps } = mergedProps

  return (
    <button
      ref={ref}
      data-slot="toggle-group-item"
      type="button"
      data-state={itemState.pressed ? 'on' : 'off'}
      className={cn(
        toggleVariants({ variant: context?.variant, size: context?.size }),
        className,
        mergedClassName
      )}
      {...restProps}
    >
      {children}
    </button>
  )
})
ToggleGroupItem.displayName = 'ToggleGroupItem'

export { ToggleGroup, ToggleGroupItem }
