// packages/vue/src/components/ui/toggle/toggle.vue
<script setup lang="ts">
import { cn, toggleVariants, type ToggleVariants } from '@timui/core'
import { computed, type HTMLAttributes } from 'vue'
import { useToggle } from './use-toggle'

const props = withDefaults(
  defineProps<{
    class?: HTMLAttributes['class']
    variant?: ToggleVariants['variant']
    size?: ToggleVariants['size']
    pressed?: boolean
    modelValue?: boolean
    defaultPressed?: boolean
    disabled?: boolean
    onPressedChange?: (pressed: boolean) => void
  }>(),
  {
    variant: 'default',
    size: 'default',
    disabled: false,
  },
)

const emit = defineEmits(['update:pressed', 'update:modelValue', 'pressedChange', 'change'])

const api = useToggle({
  pressed: props.pressed ?? props.modelValue,
  defaultPressed: (props.pressed ?? props.modelValue) === undefined ? props.defaultPressed : undefined,
  disabled: props.disabled,
  onPressedChange: (next: boolean) => {
    props.onPressedChange?.(next)
    emit('update:pressed', next)
    emit('update:modelValue', next)
    emit('pressedChange', next)
    emit('change', next)
  },
})

const computedClass = computed(() =>
  cn(toggleVariants({ variant: props.variant, size: props.size }), props.class),
)
</script>

<template>
  <button
    v-bind="api.getRootProps()"
    type="button"
    data-slot="toggle"
    :data-state="api.pressed ? 'on' : 'off'"
    :aria-pressed="api.pressed"
    :class="computedClass"
  >
    <slot />
  </button>
</template>

// packages/react/src/components/ui/toggle.tsx
'use client'

import * as React from 'react'
import { cn, toggleVariants, type ToggleVariants } from '@timui/core'
import { mergeProps } from '@zag-js/react'

import { useToggle } from './toggle/use-toggle'

const Toggle = React.forwardRef<
  HTMLButtonElement,
  React.ButtonHTMLAttributes<HTMLButtonElement> &
    ToggleVariants & {
      pressed?: boolean
      defaultPressed?: boolean
      onPressedChange?: (pressed: boolean) => void
    }
>(({ className, pressed, defaultPressed, onPressedChange, variant, size, ...props }, ref) => {
  const api = useToggle({
    pressed,
    defaultPressed,
    disabled: props.disabled,
    onPressedChange,
  })
  const rootProps = api.getRootProps()
  const mergedProps = mergeProps(rootProps, props)
  const { className: mergedClassName, ...restProps } = mergedProps

  return (
    <button
      ref={ref}
      data-slot="toggle"
      data-state={api.pressed ? 'on' : 'off'}
      aria-pressed={api.pressed}
      type="button"
      className={cn(toggleVariants({ variant, size, className }), mergedClassName)}
      {...restProps}
    />
  )
})
Toggle.displayName = 'Toggle'

export { Toggle }
