// packages/react/src/components/ui/multiselect.tsx
'use client'

import * as React from 'react'
import { useEffect } from 'react'
import type {
  AssertNoExtraKeys,
  MultiselectProps as CoreMultiselectProps,
  MultiselectOption,
} from '@timui/core'
import {
  cn,
  multiselectClearButtonVariants,
  multiselectCommandVariants,
  multiselectContainerVariants,
  multiselectDropdownVariants,
  multiselectEmptyVariants,
  multiselectGroupVariants,
  multiselectInputVariants,
  multiselectListVariants,
  multiselectTagRemoveVariants,
  multiselectTagVariants,
} from '@timui/core'
import { Command as CommandPrimitive, useCommandState } from 'cmdk'
import { XIcon } from 'lucide-react'

import { Command, CommandGroup, CommandItem, CommandList } from './command'

export type Option = MultiselectOption
interface GroupOption {
  [key: string]: Option[]
}

type MultipleSelectorProps = CoreMultiselectProps & {
  onChange?: (options: Option[]) => void
  loadingIndicator?: React.ReactNode
  emptyIndicator?: React.ReactNode
  className?: string
  badgeClassName?: string
  commandProps?: React.ComponentPropsWithoutRef<typeof Command>
  inputProps?: Omit<
    React.ComponentPropsWithoutRef<typeof CommandPrimitive.Input>,
    'value' | 'placeholder' | 'disabled'
  >
}
type _MultipleSelectorPropsGuard = AssertNoExtraKeys<
  MultipleSelectorProps,
  CoreMultiselectProps & {
    onChange?: (options: Option[]) => void
    loadingIndicator?: React.ReactNode
    emptyIndicator?: React.ReactNode
    className?: string
    badgeClassName?: string
    commandProps?: React.ComponentPropsWithoutRef<typeof Command>
    inputProps?: Omit<
      React.ComponentPropsWithoutRef<typeof CommandPrimitive.Input>,
      'value' | 'placeholder' | 'disabled'
    >
  }
>

export interface MultipleSelectorRef {
  selectedValue: Option[]
  input: HTMLInputElement
  focus: () => void
  reset: () => void
}

export function useDebounce<T>(value: T, delay?: number): T {
  const [debouncedValue, setDebouncedValue] = React.useState<T>(value)

  useEffect(() => {
    const timer = setTimeout(() => setDebouncedValue(value), delay || 500)

    return () => {
      clearTimeout(timer)
    }
  }, [value, delay])

  return debouncedValue
}

function transToGroupOption(options: Option[], groupBy?: string) {
  if (options.length === 0) {
    return {}
  }
  if (!groupBy) {
    return {
      '': options,
    }
  }

  const groupOption: GroupOption = {}
  options.forEach((option) => {
    const key = (option[groupBy] as string) || ''
    if (!groupOption[key]) {
      groupOption[key] = []
    }
    groupOption[key].push(option)
  })
  return groupOption
}

function removePickedOption(groupOption: GroupOption, picked: Option[]) {
  if (picked.length === 0) {
    return groupOption
  }

  const pickedValues = new Set(picked.map((item) => item.value))
  const next: GroupOption = {}
  for (const [key, value] of Object.entries(groupOption)) {
    next[key] = value.filter((val) => !pickedValues.has(val.value))
  }
  return next
}

function isOptionsExist(groupOption: GroupOption, targetOption: Option[]) {
  if (targetOption.length === 0) {
    return false
  }
  const targetValues = new Set(targetOption.map((item) => item.value))
  for (const [, value] of Object.entries(groupOption)) {
    if (value.some((option) => targetValues.has(option.value))) {
      return true
    }
  }
  return false
}

const CommandEmpty = ({
  className,
  ...props
}: React.ComponentProps<typeof CommandPrimitive.Empty>) => {
  const render = useCommandState((state) => state.filtered.count === 0)

  if (!render) return null

  return (
    <div
      className={cn(multiselectEmptyVariants(), className)}
      cmdk-empty=""
      role="presentation"
      {...props}
    />
  )
}

CommandEmpty.displayName = 'CommandEmpty'

export const MultipleSelector = ({
  value,
  onChange,
  onValueChange,
  placeholder,
  defaultOptions: arrayDefaultOptions = [],
  options: arrayOptions,
  delay,
  onSearch,
  onSearchSync,
  loadingIndicator,
  emptyIndicator,
  maxSelected = Number.MAX_SAFE_INTEGER,
  onMaxSelected,
  hidePlaceholderWhenSelected,
  disabled,
  groupBy,
  className,
  badgeClassName,
  selectFirstItem = true,
  creatable = false,
  triggerSearchOnFocus = false,
  commandProps,
  inputProps,
  hideClearAllButton = false,
}: MultipleSelectorProps) => {
  const emitValueChange = React.useCallback(
    (next: Option[]) => {
      onValueChange?.(next)
      onChange?.(next)
    },
    [onChange, onValueChange]
  )

  const inputRef = React.useRef<HTMLInputElement>(null)
  const [open, setOpen] = React.useState(false)
  const [onScrollbar, setOnScrollbar] = React.useState(false)
  const [isLoading, setIsLoading] = React.useState(false)
  const dropdownRef = React.useRef<HTMLDivElement>(null) // Added this

  const [selected, setSelected] = React.useState<Option[]>(value || [])
  const [options, setOptions] = React.useState<GroupOption>(
    transToGroupOption(arrayDefaultOptions, groupBy)
  )
  const [inputValue, setInputValue] = React.useState('')
  const debouncedSearchTerm = useDebounce(inputValue, delay || 500)
  const selectedValueSet = React.useMemo(
    () => new Set(selected.map((item) => item.value)),
    [selected]
  )

  const handleClickOutside = React.useCallback((event: MouseEvent | TouchEvent) => {
    if (
      dropdownRef.current &&
      !dropdownRef.current.contains(event.target as Node) &&
      inputRef.current &&
      !inputRef.current.contains(event.target as Node)
    ) {
      setOpen(false)
      inputRef.current.blur()
    }
  }, [])

  const handleUnselect = React.useCallback(
    (option: Option) => {
      const newOptions = selected.filter((s) => s.value !== option.value)
      setSelected(newOptions)
      emitValueChange(newOptions)
    },
    [emitValueChange, selected]
  )

  const handleKeyDown = React.useCallback(
    (e: React.KeyboardEvent<HTMLDivElement>) => {
      const input = inputRef.current
      if (input) {
        if (e.key === 'Delete' || e.key === 'Backspace') {
          if (input.value === '' && selected.length > 0) {
            const lastSelectOption = selected[selected.length - 1]
            // If last item is fixed, we should not remove it.
            if (!lastSelectOption.fixed) {
              handleUnselect(selected[selected.length - 1])
            }
          }
        }
        // This is not a default behavior of the <input /> field
        if (e.key === 'Escape') {
          input.blur()
        }
      }
    },
    [handleUnselect, selected]
  )

  useEffect(() => {
    if (open) {
      document.addEventListener('mousedown', handleClickOutside)
      document.addEventListener('touchend', handleClickOutside)
    } else {
      document.removeEventListener('mousedown', handleClickOutside)
      document.removeEventListener('touchend', handleClickOutside)
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside)
      document.removeEventListener('touchend', handleClickOutside)
    }
  }, [handleClickOutside, open])

  useEffect(() => {
    if (value) {
      setSelected(value)
    }
  }, [value])

  useEffect(() => {
    /** If `onSearch` is provided, do not trigger options updated. */
    if (!arrayOptions || onSearch) {
      return
    }
    setOptions(transToGroupOption(arrayOptions, groupBy))
  }, [arrayOptions, groupBy, onSearch])

  useEffect(() => {
    /** sync search */

    const doSearchSync = () => {
      const res = onSearchSync?.(debouncedSearchTerm)
      setOptions(transToGroupOption(res || [], groupBy))
    }

    const exec = async () => {
      if (!onSearchSync || !open) return
      if (triggerSearchOnFocus || debouncedSearchTerm) {
        doSearchSync()
      }
    }

    void exec()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [debouncedSearchTerm, groupBy, open, triggerSearchOnFocus])

  useEffect(() => {
    /** async search */
    let active = true

    const doSearch = async () => {
      setIsLoading(true)
      const res = await onSearch?.(debouncedSearchTerm)
      if (!active) return
      setOptions(transToGroupOption(res || [], groupBy))
      setIsLoading(false)
    }

    const exec = async () => {
      if (!onSearch || !open) return
      if (triggerSearchOnFocus || debouncedSearchTerm) {
        await doSearch()
      }
    }

    void exec()
    return () => {
      active = false
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [debouncedSearchTerm, groupBy, open, triggerSearchOnFocus])

  const creatableNode = React.useMemo(() => {
    if (!creatable) return undefined
    if (
      isOptionsExist(options, [{ value: inputValue, label: inputValue }]) ||
      selectedValueSet.has(inputValue)
    ) {
      return undefined
    }

    const shouldShow =
      (!onSearch && inputValue.length > 0) ||
      (onSearch && debouncedSearchTerm.length > 0 && !isLoading)

    if (!shouldShow) return undefined

    return (
      <CommandItem
        value={inputValue}
        className="cursor-pointer"
        onMouseDown={(e) => {
          e.preventDefault()
          e.stopPropagation()
        }}
        onSelect={(value: string) => {
          if (selected.length >= maxSelected) {
            onMaxSelected?.(selected.length)
            return
          }
          setInputValue('')
          const newOptions = [...selected, { value, label: value }]
          setSelected(newOptions)
          emitValueChange(newOptions)
        }}
      >
        {`Create "${inputValue}"`}
      </CommandItem>
    )
  }, [
    creatable,
    debouncedSearchTerm.length,
    emitValueChange,
    inputValue,
    isLoading,
    maxSelected,
    onMaxSelected,
    onSearch,
    options,
    selected,
    selectedValueSet,
  ])

  const emptyNode = React.useMemo(() => {
    if (!emptyIndicator) return undefined

    if (onSearch && !creatable && Object.keys(options).length === 0) {
      return (
        <CommandItem value="-" disabled>
          {emptyIndicator}
        </CommandItem>
      )
    }

    return <CommandEmpty>{emptyIndicator}</CommandEmpty>
  }, [creatable, emptyIndicator, onSearch, options])

  const selectables = React.useMemo<GroupOption>(
    () => removePickedOption(options, selected),
    [options, selected]
  )
  const selectableEntries = React.useMemo(() => Object.entries(selectables), [selectables])
  const fixedSelected = React.useMemo(() => selected.filter((item) => item.fixed), [selected])

  /** Avoid Creatable Selector freezing or lagging when paste a long string. */
  const commandFilter = React.useMemo(() => {
    if (commandProps?.filter) return commandProps.filter
    if (!creatable) return undefined
    return (value: string, search: string) => {
      return value.toLowerCase().includes(search.toLowerCase()) ? 1 : -1
    }
  }, [creatable, commandProps?.filter])

  return (
    <Command
      ref={dropdownRef}
      {...commandProps}
      onKeyDown={(e) => {
        handleKeyDown(e)
        commandProps?.onKeyDown?.(e)
      }}
      className={cn(multiselectCommandVariants(), commandProps?.className)}
      shouldFilter={
        commandProps?.shouldFilter !== undefined ? commandProps.shouldFilter : !onSearch
      } // When onSearch is provided, we don&lsquo;t want to filter the options. You can still override it.
      filter={commandFilter}
    >
      <div
        className={cn(
          multiselectContainerVariants(),
          {
            'p-1': selected.length !== 0,
            'cursor-text': !disabled && selected.length !== 0,
          },
          !hideClearAllButton && 'pe-9',
          className
        )}
        onClick={() => {
          if (disabled) return
          inputRef?.current?.focus()
        }}
      >
        <div className="flex flex-wrap gap-1">
          {selected.map((option) => {
            return (
              <div
                key={option.value}
                className={cn(multiselectTagVariants(), badgeClassName)}
                data-fixed={option.fixed}
                data-disabled={disabled || undefined}
              >
                {option.label}
                <button
                  className={multiselectTagRemoveVariants()}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      handleUnselect(option)
                    }
                  }}
                  onMouseDown={(e) => {
                    e.preventDefault()
                    e.stopPropagation()
                  }}
                  onClick={() => handleUnselect(option)}
                  aria-label="Remove"
                >
                  <XIcon size={14} aria-hidden="true" />
                </button>
              </div>
            )
          })}
          {/* Avoid having the "Search" Icon */}
          <CommandPrimitive.Input
            {...inputProps}
            ref={inputRef}
            value={inputValue}
            disabled={disabled}
            onValueChange={(value) => {
              setInputValue(value)
              inputProps?.onValueChange?.(value)
            }}
            onBlur={(event) => {
              if (!onScrollbar) {
                setOpen(false)
              }
              inputProps?.onBlur?.(event)
            }}
            onFocus={(event) => {
              setOpen(true)
              inputProps?.onFocus?.(event)
            }}
            placeholder={hidePlaceholderWhenSelected && selected.length !== 0 ? '' : placeholder}
            className={cn(
              multiselectInputVariants(),
              {
                'w-full': hidePlaceholderWhenSelected,
                'px-3 py-2': selected.length === 0,
                'ml-1': selected.length !== 0,
              },
              inputProps?.className
            )}
          />
          <button
            type="button"
            onClick={() => {
              setSelected(fixedSelected)
              emitValueChange(fixedSelected)
            }}
            className={cn(
              multiselectClearButtonVariants(),
              (hideClearAllButton ||
                disabled ||
                selected.length < 1 ||
                fixedSelected.length === selected.length) &&
                'hidden'
            )}
            aria-label="Clear all"
          >
            <XIcon size={16} aria-hidden="true" />
          </button>
        </div>
      </div>
      <div className="relative">
        <div
          className={cn(
            multiselectDropdownVariants(),
            'data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
            !open && 'hidden'
          )}
          data-state={open ? 'open' : 'closed'}
        >
          {open && (
            <CommandList
              className={multiselectListVariants()}
              onMouseLeave={() => {
                setOnScrollbar(false)
              }}
              onMouseEnter={() => {
                setOnScrollbar(true)
              }}
              onMouseUp={() => {
                inputRef?.current?.focus()
              }}
            >
              {isLoading ? (
                <>{loadingIndicator}</>
              ) : (
                <>
                  {emptyNode}
                  {creatableNode}
                  {!selectFirstItem && <CommandItem value="-" className="hidden" />}
                  {selectableEntries.map(([key, dropdowns]) => (
                    <CommandGroup key={key} heading={key} className={multiselectGroupVariants()}>
                      <>
                        {dropdowns.map((option) => {
                          return (
                            <CommandItem
                              key={option.value}
                              value={option.value}
                              disabled={option.disable}
                              onMouseDown={(e) => {
                                e.preventDefault()
                                e.stopPropagation()
                              }}
                              onSelect={() => {
                                if (selected.length >= maxSelected) {
                                  onMaxSelected?.(selected.length)
                                  return
                                }
                                setInputValue('')
                                const newOptions = [...selected, option]
                                setSelected(newOptions)
                                emitValueChange(newOptions)
                              }}
                              className={cn(
                                'cursor-pointer',
                                option.disable &&
                                  'pointer-events-none cursor-not-allowed opacity-50'
                              )}
                            >
                              {option.label}
                            </CommandItem>
                          )
                        })}
                      </>
                    </CommandGroup>
                  ))}
                </>
              )}
            </CommandList>
          )}
        </div>
      </div>
    </Command>
  )
}

MultipleSelector.displayName = 'MultipleSelector'
export default MultipleSelector

// packages/vue/src/components/ui/multiselect/multiselect.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, useId, watch, type Component, type VNodeChild } from "vue";
import {
  cn,
  multiselectClearButtonVariants,
  multiselectCommandVariants,
  multiselectContainerVariants,
  multiselectDropdownVariants,
  multiselectGroupVariants,
  multiselectInputVariants,
  multiselectListVariants,
  multiselectTagRemoveVariants,
  multiselectTagVariants,
} from "@timui/core";
import { XIcon } from "lucide-vue-next";
import Command from "../command/command.vue";
import CommandEmpty from "../command/command-empty.vue";
import CommandGroup from "../command/command-group.vue";
import CommandItem from "../command/command-item.vue";
import CommandList from "../command/command-list.vue";
import CommandInput from "../command/command-input.vue";
import type { AssertNoExtraKeys, MultiselectOption, MultiselectVueProps, ComboboxApi } from "@timui/core";

export type Option = MultiselectOption;

interface GroupOption {
  [key: string]: Option[];
}

type MultiselectProps = MultiselectVueProps & {
  class?: string;
  badgeClass?: string;
  loadingIndicator?: Component | VNodeChild;
  emptyIndicator?: Component | VNodeChild;
};
type _MultiselectPropsGuard = AssertNoExtraKeys<
  MultiselectProps,
  MultiselectVueProps & {
    class?: string;
    badgeClass?: string;
    loadingIndicator?: Component | VNodeChild;
    emptyIndicator?: Component | VNodeChild;
  }
>;

const props = defineProps<MultiselectProps>();

const emit = defineEmits(["update:modelValue", "change"]);

const inputRef = ref<{ inputEl?: HTMLInputElement | null } | null>(null);
const listId = `multiselect-list-${useId()}`;
type CommandExpose = { rootEl?: HTMLElement | null; api?: ComboboxApi };
const dropdownRef = ref<CommandExpose | null>(null);
const open = ref(false);
const onScrollbar = ref(false);
const isLoading = ref(false);

const selected = ref<Option[]>(props.modelValue ?? []);
const options = ref<GroupOption>({});
const inputValue = ref("");

const maxSelected = computed(() => props.maxSelected ?? Number.MAX_SAFE_INTEGER);
const selectFirstItem = computed(() => props.selectFirstItem ?? true);

const transToGroupOption = (list: Option[] = [], groupBy?: string): GroupOption => {
  if (list.length === 0) return {};
  if (!groupBy) return { "": list };
  const groupOption: GroupOption = {};
  list.forEach((option) => {
    const key = (option[groupBy] as string) || "";
    if (!groupOption[key]) groupOption[key] = [];
    groupOption[key].push(option);
  });
  return groupOption;
};

const removePickedOption = (groupOption: GroupOption, picked: Option[]) => {
  if (picked.length === 0) return groupOption;
  const pickedValues = new Set(picked.map((item) => item.value));
  const next: GroupOption = {};
  for (const [key, value] of Object.entries(groupOption)) {
    next[key] = value.filter((val) => !pickedValues.has(val.value));
  }
  return next;
};

const isOptionsExist = (groupOption: GroupOption, targetOption: Option[]) => {
  if (targetOption.length === 0) return false;
  const targetValues = new Set(targetOption.map((item) => item.value));
  for (const [, value] of Object.entries(groupOption)) {
    if (value.some((option) => targetValues.has(option.value))) {
      return true;
    }
  }
  return false;
};

const debouncedSearchTerm = ref("");
let debounceTimer: number | null = null;
watch(
  () => inputValue.value,
  (val) => {
    if (debounceTimer) window.clearTimeout(debounceTimer);
    debounceTimer = window.setTimeout(() => {
      debouncedSearchTerm.value = val;
    }, props.delay ?? 500);
  }
);

watch(
  () => props.modelValue,
  (val) => {
    if (val) selected.value = val;
  }
);

watch(
  () => props.options,
  (val) => {
    if (!val || props.onSearch) return;
    options.value = transToGroupOption(val, props.groupBy);
  }
);

watch(
  () => props.defaultOptions,
  (val) => {
    if (!props.options && !props.onSearch) {
      options.value = transToGroupOption(val ?? [], props.groupBy);
    }
  },
  { immediate: true }
);

watch(
  () => [debouncedSearchTerm.value, open.value, props.groupBy],
  async () => {
    if (!props.onSearchSync || !open.value) return;
    if (props.triggerSearchOnFocus || debouncedSearchTerm.value) {
      const res = props.onSearchSync?.(debouncedSearchTerm.value) ?? [];
      options.value = transToGroupOption(res, props.groupBy);
    }
  }
);

watch(
  () => [debouncedSearchTerm.value, open.value, props.groupBy],
  async () => {
    if (!props.onSearch || !open.value) return;
    if (props.triggerSearchOnFocus || debouncedSearchTerm.value) {
      isLoading.value = true;
      const res = (await props.onSearch?.(debouncedSearchTerm.value)) ?? [];
      options.value = transToGroupOption(res, props.groupBy);
      isLoading.value = false;
    }
  }
);

const selectables = computed(() => removePickedOption(options.value, selected.value));
const flatSelectables = computed(() =>
  Object.values(selectables.value).flat().filter((item) => !item.disable)
);
const selectedValueSet = computed(() => new Set(selected.value.map((item) => item.value)));
const fixedSelected = computed(() => selected.value.filter((item) => item.fixed));
const isClearAllHidden = computed(
  () =>
    !!props.hideClearAllButton ||
    !!props.disabled ||
    selected.value.length < 1 ||
    fixedSelected.value.length === selected.value.length
);

const setSelected = (next: Option[]) => {
  selected.value = next;
  emit("update:modelValue", next);
  emit("change", next);
};

const handleUnselect = (option: Option) => {
  setSelected(selected.value.filter((s) => s.value !== option.value));
};

const getInputEl = () => inputRef.value?.inputEl ?? null;

const handleClickOutside = (event: MouseEvent | TouchEvent) => {
  const rootEl = dropdownRef.value?.rootEl ?? null;
  if (
    rootEl &&
    !rootEl.contains(event.target as Node) &&
    getInputEl() &&
    !getInputEl()?.contains(event.target as Node)
  ) {
    open.value = false;
    getInputEl()?.blur();
  }
};

watch(open, (isOpen) => {
  if (isOpen) {
    document.addEventListener("mousedown", handleClickOutside);
    document.addEventListener("touchend", handleClickOutside);
    return;
  }

  document.removeEventListener("mousedown", handleClickOutside);
  document.removeEventListener("touchend", handleClickOutside);
});

onBeforeUnmount(() => {
  if (debounceTimer) window.clearTimeout(debounceTimer);
  document.removeEventListener("mousedown", handleClickOutside);
  document.removeEventListener("touchend", handleClickOutside);
});

const creatableItem = computed(() => {
  if (!props.creatable) return undefined;
  if (
    isOptionsExist(options.value, [{ value: inputValue.value, label: inputValue.value }]) ||
    selectedValueSet.value.has(inputValue.value)
  ) {
    return undefined;
  }
  if (!props.onSearch && inputValue.value.length > 0) return inputValue.value;
  if (props.onSearch && debouncedSearchTerm.value.length > 0 && !isLoading.value) {
    return inputValue.value;
  }
  return undefined;
});

const emptyIndicatorIsComponent = computed(() => {
  const value = props.emptyIndicator;
  return typeof value === "object" || typeof value === "function";
});

const createOption = (value: string): Option => ({ value, label: value });
const addCreatableItem = () => {
  const value = creatableItem.value;
  if (!value) return;
  if (selected.value.length >= maxSelected.value) {
    props.onMaxSelected?.(selected.value.length);
    return;
  }
  inputValue.value = "";
  const next = [...selected.value, createOption(value)];
  setSelected(next);
};

const onInputValueChange = (value: string) => {
  inputValue.value = value;
};

const onKeyDown = (event: KeyboardEvent) => {
  if (event.key === "Delete" || event.key === "Backspace") {
    if (inputValue.value === "" && selected.value.length > 0) {
      const last = selected.value[selected.value.length - 1];
      if (!last.fixed) handleUnselect(last);
    }
  }
  if (event.key === "Escape") {
    getInputEl()?.blur();
  }
};

const getCommandApi = () => dropdownRef.value?.api ?? null;
const highlightFirst = () => {
  const api = getCommandApi();
  const first = flatSelectables.value[0];
  if (api && first) api.setHighlightValue(first.value);
};
const highlightLast = () => {
  const api = getCommandApi();
  const last = flatSelectables.value[flatSelectables.value.length - 1];
  if (api && last) api.setHighlightValue(last.value);
};

const onInputKeyDown = (event: KeyboardEvent) => {
  if (event.key === "Home") {
    event.preventDefault();
    if (!open.value) {
      inputValue.value = "";
      return;
    }
    highlightFirst();
    return;
  }
  if (event.key === "End") {
    event.preventDefault();
    if (open.value) {
      highlightLast();
      return;
    }
    openDropdown();
    return;
  }
  if (event.key === "PageDown" || event.key === "PageUp") {
    openDropdown();
    if (event.key === "PageDown") highlightLast();
    else highlightFirst();
    return;
  }
  if (event.key === "ArrowDown" || event.key === "ArrowUp") {
    openDropdown();
  }
  onKeyDown(event);
};

const openDropdown = () => {
  if (props.disabled) return;
  open.value = true;
  getInputEl()?.focus();
  if (props.triggerSearchOnFocus) {
    props.onSearch?.(debouncedSearchTerm.value);
  }
};
</script>

<template>
  <Command
    ref="dropdownRef"
    :class="multiselectCommandVariants()"
    @keydown="onKeyDown"
  >
    <div
      :class="
        cn(
          multiselectContainerVariants(),
          {
            'p-1': selected.length !== 0,
            'cursor-text': !props.disabled && selected.length !== 0,
          },
          !props.hideClearAllButton && 'pe-9',
          props.class
        )
      "
      @focusin="openDropdown"
      @focusout="() => { if (!onScrollbar) open = false }"
      @click="openDropdown"
    >
      <div class="flex flex-wrap gap-1">
        <div
          v-for="option in selected"
          :key="option.value"
          :class="
            cn(
              multiselectTagVariants(),
              props.badgeClass
            )
          "
          :data-fixed="option.fixed"
          :data-disabled="props.disabled || undefined"
        >
          {{ option.label }}
          <button
            :class="multiselectTagRemoveVariants()"
            type="button"
            @mousedown.prevent.stop
            @click="handleUnselect(option)"
          >
            <XIcon :size="14" aria-hidden="true" />
          </button>
        </div>
        <CommandInput
          ref="inputRef"
          :on-value-change="onInputValueChange"
          :list-id="listId"
          :expanded="open"
          :placeholder="props.hidePlaceholderWhenSelected && selected.length !== 0 ? '' : props.placeholder"
          :class="
            cn(
              multiselectInputVariants(),
              {
                'w-full': props.hidePlaceholderWhenSelected,
                'px-3 py-2': selected.length === 0,
                'ml-1': selected.length !== 0,
              }
            )
          "
          @focus="openDropdown"
          @blur="() => { if (!onScrollbar) open = false }"
          @keydown="onInputKeyDown"
        />
        <button
          type="button"
          :class="
            cn(
              multiselectClearButtonVariants(),
              isClearAllHidden && 'hidden'
            )
          "
          aria-label="Clear all"
          @click="
            () => {
              setSelected(fixedSelected);
            }
          "
        >
          <XIcon :size="16" aria-hidden="true" />
        </button>
      </div>
    </div>
    <div class="relative">
      <div
        :class="
          cn(
            multiselectDropdownVariants(),
            'data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
            !open && 'hidden'
          )
        "
        :data-state="open ? 'open' : 'closed'"
      >
        <CommandList
          v-if="open"
          :id="listId"
          :class="multiselectListVariants()"
          @mouseleave="onScrollbar = false"
          @mouseenter="onScrollbar = true"
          @mouseup="() => getInputEl()?.focus()"
        >
          <template v-if="isLoading">
            <component :is="props.loadingIndicator" />
          </template>
          <template v-else>
            <CommandEmpty v-if="props.emptyIndicator">
              <component v-if="emptyIndicatorIsComponent" :is="props.emptyIndicator" />
              <span v-else>{{ props.emptyIndicator }}</span>
            </CommandEmpty>
            <CommandItem
              v-if="creatableItem"
              :value="creatableItem"
              class="cursor-pointer"
              @mousedown.prevent.stop
              @click="addCreatableItem"
            >
              Create "{{ creatableItem }}"
            </CommandItem>
            <CommandItem v-if="!selectFirstItem" value="-" class="hidden" />
            <CommandGroup
              v-for="(dropdowns, key) in selectables"
              :key="key"
              :heading="key"
              :class="multiselectGroupVariants()"
            >
              <CommandItem
                v-for="option in dropdowns"
                :key="option.value"
                :value="option.value"
                :disabled="option.disable"
                class="cursor-pointer"
                @mousedown.prevent.stop
                @click="
                  () => {
                    if (selected.length >= maxSelected) {
                      props.onMaxSelected?.(selected.length);
                      return;
                    }
                    inputValue = '';
                    const next = [...selected, option];
                    setSelected(next);
                  }
                "
              >
                {{ option.label }}
              </CommandItem>
            </CommandGroup>
          </template>
        </CommandList>
      </div>
    </div>
  </Command>
</template>
