// apps/docs/registry/default/components/calendar-date-picker/calendar-date-picker-19.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { ScrollArea } from '@/components/ui/scroll-area';



</script>

<template>
  <div><div class="rounded-md border"><div class="flex max-sm:flex-col"><Calendar mode="single" :selected="date" :onSelect="(newDate) => {
              if (newDate) {
                setDate(newDate)
                setTime(null)
              }
            }" class="p-2 sm:pe-5" :disabled="[
              { before: today }, // Dates before today
            ]" /><div class="relative w-full max-sm:h-48 sm:w-40"><div class="absolute inset-0 py-4 max-sm:border-t"><ScrollArea class="h-full sm:border-s"><div class="space-y-3"><div class="flex h-5 shrink-0 items-center px-5"><p class="text-sm font-medium">{{ format(date, 'EEEE, d') }}</p></div><div class="grid gap-1.5 px-5 max-sm:grid-cols-2"><Button v-for="({ time: timeSlot, available }, index) in timeSlots" :key="index" :key="timeSlot" :variant="time === timeSlot ? 'default' : 'outline'" size="sm" class="w-full" @click="setTime(timeSlot)" :disabled="!available">{{ timeSlot }}</Button></div></div></ScrollArea></div></div></div></div><p class="text-muted-foreground mt-4 text-center text-xs" role="region" aria-live="polite">Appointment picker -{{ ' ' }}<a class="hover:text-foreground underline" href="https://daypicker.dev/" target="_blank" rel="noopener nofollow">React DayPicker
        </a></p></div>
</template>

// apps/docs/registry/default/components/calendar-date-picker/calendar-date-picker-19.tsx
'use client'

import { useState } from 'react'
import { format } from 'date-fns'

import { Button } from '../../ui/button'
import { Calendar } from '../../ui/calendar'
import { ScrollArea } from '../../ui/scroll-area'

export default function Component() {
  const today = new Date()
  const [date, setDate] = useState<Date>(today)
  const [time, setTime] = useState<string | null>(null)

  // Mock time slots data
  const timeSlots = [
    { time: '09:00', available: false },
    { time: '09:30', available: false },
    { time: '10:00', available: true },
    { time: '10:30', available: true },
    { time: '11:00', available: true },
    { time: '11:30', available: true },
    { time: '12:00', available: false },
    { time: '12:30', available: true },
    { time: '13:00', available: true },
    { time: '13:30', available: true },
    { time: '14:00', available: true },
    { time: '14:30', available: false },
    { time: '15:00', available: false },
    { time: '15:30', available: true },
    { time: '16:00', available: true },
    { time: '16:30', available: true },
    { time: '17:00', available: true },
    { time: '17:30', available: true },
  ]

  return (
    <div>
      <div className="rounded-md border">
        <div className="flex max-sm:flex-col">
          <Calendar
            mode="single"
            selected={date}
            onSelect={(newDate) => {
              if (newDate) {
                setDate(newDate)
                setTime(null)
              }
            }}
            className="p-2 sm:pe-5"
            disabled={[
              { before: today }, // Dates before today
            ]}
          />
          <div className="relative w-full max-sm:h-48 sm:w-40">
            <div className="absolute inset-0 py-4 max-sm:border-t">
              <ScrollArea className="h-full sm:border-s">
                <div className="space-y-3">
                  <div className="flex h-5 shrink-0 items-center px-5">
                    <p className="text-sm font-medium">{format(date, 'EEEE, d')}</p>
                  </div>
                  <div className="grid gap-1.5 px-5 max-sm:grid-cols-2">
                    {timeSlots.map(({ time: timeSlot, available }) => (
                      <Button
                        key={timeSlot}
                        variant={time === timeSlot ? 'default' : 'outline'}
                        size="sm"
                        className="w-full"
                        onClick={() => setTime(timeSlot)}
                        disabled={!available}
                      >
                        {timeSlot}
                      </Button>
                    ))}
                  </div>
                </div>
              </ScrollArea>
            </div>
          </div>
        </div>
      </div>
      <p
        className="text-muted-foreground mt-4 text-center text-xs"
        role="region"
        aria-live="polite"
      >
        Appointment picker -{' '}
        <a
          className="hover:text-foreground underline"
          href="https://daypicker.dev/"
          target="_blank"
          rel="noopener nofollow"
        >
          React DayPicker
        </a>
      </p>
    </div>
  )
}
