// apps/docs/registry/default/vue/date-picker.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { cn } from '@timui/core'
import { Button } from './button.vue'
import { Calendar } from './calendar.vue'
import { Popover } from './popover.vue'
import { PopoverTrigger } from './popover-trigger.vue'
import { PopoverContent } from './popover-content.vue'

type DatePickerMode = 'single' | 'range'

type RangeValue = { from?: Date; to?: Date } | undefined

type DatePickerValue = Date | RangeValue | undefined

const props = withDefaults(
  defineProps<{
    modelValue?: DatePickerValue
    defaultValue?: DatePickerValue
    mode?: DatePickerMode
    placeholder?: string
    class?: string
    triggerClass?: string
    contentClass?: string
  }>(),
  {
    mode: 'single',
    placeholder: 'Date',
  }
)

const emit = defineEmits(['update:modelValue', 'change'])

const internalValue = ref<DatePickerValue>(props.modelValue ?? props.defaultValue)

watch(
  () => props.modelValue,
  (val) => {
    if (val !== undefined) internalValue.value = val
  }
)

const setValue = (next: DatePickerValue) => {
  internalValue.value = next
  emit('update:modelValue', next)
  emit('change', next)
}

const formatDate = (date: Date) =>
  new Intl.DateTimeFormat('en-US', { month: 'short', day: '2-digit', year: 'numeric' }).format(
    date
  )

const label = computed(() => {
  const selected = internalValue.value
  if (props.mode === 'range') {
    if (!selected || !(selected as RangeValue)?.from) return ''
    const range = selected as RangeValue
    if (range.from && range.to) return `${formatDate(range.from)} - ${formatDate(range.to)}`
    if (range.from) return formatDate(range.from)
    return ''
  }
  return selected instanceof Date ? formatDate(selected) : ''
})
</script>

<template>
  <div data-slot="date-picker" :class="cn('w-full', props.class)">
    <Popover>
      <PopoverTrigger as-child class="w-full">
        <Button
          variant="outline"
          size="sm"
          :class="cn('bg-background border-input w-full justify-between px-3 text-sm font-normal outline-offset-0 outline-none focus-visible:outline-[3px]', props.triggerClass)"
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="text-muted-foreground/80 -ms-1 shrink-0"
            aria-hidden="true"
          >
            <rect x="3" y="4" width="18" height="18" rx="2" />
            <path d="M8 2v4" />
            <path d="M16 2v4" />
            <path d="M3 10h18" />
          </svg>
          <span :class="cn('truncate', !label && 'font-medium')">{{ label || props.placeholder }}</span>
        </Button>
      </PopoverTrigger>
      <PopoverContent
        data-slot="date-picker-content"
        align="start"
        :class="cn('w-auto p-2', props.contentClass)"
      >
        <Calendar
          :mode="props.mode"
          :model-value="internalValue"
          @update:model-value="setValue"
        />
      </PopoverContent>
    </Popover>
  </div>
</template>

// apps/docs/registry/default/ui/date-picker.tsx
'use client'

import * as React from 'react'
import { cn } from '@timui/core'
import { format } from 'date-fns'
import type { DateRange, OnSelectHandler } from 'react-day-picker'

import { Button } from './button'
import { Calendar } from './calendar'
import { Popover, PopoverContent, PopoverTrigger } from './popover'

type DatePickerMode = 'single' | 'range'

type DatePickerValue = Date | DateRange | undefined

interface DatePickerProps {
  mode?: DatePickerMode
  value?: DatePickerValue
  defaultValue?: DatePickerValue
  onValueChange?: (value: DatePickerValue) => void
  placeholder?: string
  className?: string
  triggerClassName?: string
  contentClassName?: string
  calendarProps?: Omit<CalendarProps, 'mode' | 'selected' | 'onSelect'>
}

type CalendarProps = React.ComponentProps<typeof Calendar>

const formatSingle = (value: Date) => format(value, 'LLL dd, y')
const formatRange = (value: DateRange) => {
  if (value.from && value.to) {
    return `${format(value.from, 'LLL dd, y')} - ${format(value.to, 'LLL dd, y')}`
  }
  if (value.from) {
    return format(value.from, 'LLL dd, y')
  }
  return ''
}

function DatePicker({
  mode = 'single',
  value,
  defaultValue,
  onValueChange,
  placeholder = 'Date',
  className,
  triggerClassName,
  contentClassName,
  calendarProps,
}: DatePickerProps) {
  const isControlled = value !== undefined
  const [uncontrolled, setUncontrolled] = React.useState<DatePickerValue>(defaultValue)
  const selected = isControlled ? value : uncontrolled

  const handleChange = React.useCallback(
    (next: DatePickerValue) => {
      if (!isControlled) setUncontrolled(next)
      onValueChange?.(next)
    },
    [isControlled, onValueChange]
  )

  const handleSelect = React.useCallback<OnSelectHandler<DatePickerValue>>(
    (next) => handleChange(next),
    [handleChange]
  )

  const label = React.useMemo(() => {
    if (mode === 'range') {
      return selected && typeof selected === 'object' && 'from' in selected
        ? formatRange(selected as DateRange)
        : ''
    }
    return selected instanceof Date ? formatSingle(selected) : ''
  }, [mode, selected])

  return (
    <div data-slot="date-picker" className={cn('w-full', className)}>
      <Popover>
        <PopoverTrigger asChild data-slot="date-picker-trigger" className="w-full">
          <Button
            variant="outline"
            size="sm"
            className={cn(
              'bg-background border-input w-full justify-between px-3 text-sm font-normal outline-offset-0 outline-none focus-visible:outline-[3px]',
              triggerClassName
            )}
          >
            <svg
              width={16}
              height={16}
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="text-muted-foreground/80 -ms-1 shrink-0"
              aria-hidden="true"
            >
              <rect x="3" y="4" width="18" height="18" rx="2" />
              <path d="M8 2v4" />
              <path d="M16 2v4" />
              <path d="M3 10h18" />
            </svg>
            <span className={cn('truncate', !label && 'font-medium')}>{label || placeholder}</span>
          </Button>
        </PopoverTrigger>
        <PopoverContent
          data-slot="date-picker-content"
          className={cn('w-auto p-2', contentClassName)}
          align="start"
        >
          <Calendar
            mode={mode}
            selected={selected as never}
            onSelect={handleSelect}
            {...calendarProps}
          />
        </PopoverContent>
      </Popover>
    </div>
  )
}

export { DatePicker }
export type { DatePickerProps, DatePickerMode, DatePickerValue }
