// apps/docs/registry/default/vue/slider.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import type { AssertNoExtraKeys, SliderVueProps } from "@timui/core";
import { sliderConnect, sliderMachine } from "@timui/core";
import { normalizeProps, useMachine } from "@zag-js/vue";
import { cn } from "@timui/core";
import type { HTMLAttributes } from "vue";

type SliderProps = SliderVueProps & { class?: HTMLAttributes["class"] };
type _SliderPropsGuard = AssertNoExtraKeys<SliderProps, SliderProps>;

const props = defineProps<SliderProps>();

const emit = defineEmits(["update:modelValue", "change", "commit"]);
const generatedId = useId();

const machineProps = computed(() => ({
  id: props.id ?? generatedId,
  value: props.modelValue ?? props.value,
  defaultValue:
    props.modelValue === undefined && props.value === undefined
      ? props.defaultValue
      : undefined,
  min: props.min ?? 0,
  max: props.max ?? 100,
  step: props.step ?? 1,
  disabled: props.disabled,
  onValueChange(details: any) {
    emit("update:modelValue", details.value);
    emit("change", details.value);
  },
  onValueCommit(details: any) {
    emit("commit", details.value);
  },
}));

const service = useMachine(sliderMachine, machineProps);
const api = computed(() => sliderConnect(service, normalizeProps));
const rootProps = computed(() => api.value?.getRootProps?.() ?? {});
const controlProps = computed(() => api.value?.getControlProps?.() ?? {});
const trackProps = computed(() => api.value?.getTrackProps?.() ?? {});
const rangeProps = computed(() => api.value?.getRangeProps?.() ?? {});

const getThumbProps = (index: number) =>
  api.value?.getThumbProps?.({ index }) ?? {};
const getHiddenInputProps = (index: number) =>
  api.value?.getHiddenInputProps?.({ index }) ?? {};

const thumbPropsList = computed(() =>
  (api.value?.value ?? []).map((_, index) => getThumbProps(index))
);
const hiddenInputPropsList = computed(() =>
  (api.value?.value ?? []).map((_, index) => getHiddenInputProps(index))
);
</script>

<template>
  <div
    v-bind="rootProps"
    data-slot="slider"
    :class="
      cn(
        'relative flex w-full touch-none select-none items-center data-[disabled=true]:opacity-50',
        props.class
      )
    "
  >
    <div
      v-bind="controlProps"
      data-slot="slider-control"
      :class="
        cn(
          'relative flex w-full touch-none select-none items-center data-[orientation=vertical]:h-full data-[orientation=vertical]:min-h-44 data-[orientation=vertical]:w-auto data-[orientation=vertical]:flex-col',
          controlProps.class
        )
      "
    >
      <div
        v-bind="trackProps"
        data-slot="slider-track"
        :class="cn('relative h-2 w-full grow overflow-hidden rounded-full bg-secondary', trackProps.class)"
      >
        <div
          v-bind="rangeProps"
          data-slot="slider-range"
          :class="cn('absolute h-full bg-primary', rangeProps.class)"
        />
      </div>
      <template v-for="(thumbProps, index) in thumbPropsList" :key="index">
        <div
          v-bind="thumbProps"
          data-slot="slider-thumb"
          :class="
            cn(
              'absolute block h-5 w-5 rounded-full border-2 border-primary bg-background ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
              thumbProps.class
            )
          "
        />
        <input v-bind="hiddenInputPropsList[index] ?? {}" />
      </template>
    </div>
  </div>
</template>

// apps/docs/registry/default/ui/slider.tsx
'use client'

import * as React from 'react'
import { cn, sliderConnect, sliderMachine } from '@timui/core'
import { mergeProps, normalizeProps, useMachine } from '@zag-js/react'

const Slider = React.forwardRef<
  HTMLDivElement,
  Omit<React.HTMLAttributes<HTMLDivElement>, 'value' | 'defaultValue'> & {
    value?: number[]
    defaultValue?: number[]
    min?: number
    max?: number
    step?: number
    orientation?: 'horizontal' | 'vertical'
    showTooltip?: boolean
    tooltipContent?: (value: number) => string
    onValueChange?: (value: number[]) => void
    onValueCommit?: (value: number[]) => void
    disabled?: boolean
  }
>(
  (
    {
      className,
      value,
      defaultValue,
      min = 0,
      max = 100,
      step = 1,
      orientation = 'horizontal',
      showTooltip: _showTooltip,
      tooltipContent: _tooltipContent,
      onValueChange,
      onValueCommit,
      disabled,
      ...props
    },
    ref
  ) => {
    void _showTooltip
    void _tooltipContent

    const service = useMachine(sliderMachine, {
      id: React.useId(),
      value,
      defaultValue,
      min,
      max,
      step,
      orientation,
      disabled,
      onValueChange(details) {
        onValueChange?.(details.value)
      },
      onValueChangeEnd(details) {
        onValueCommit?.(details.value)
      },
    })
    const api = React.useMemo(() => sliderConnect(service, normalizeProps), [service])

    const rootProps = api.getRootProps()
    const controlProps = api.getControlProps()
    const trackProps = api.getTrackProps()
    const rangeProps = api.getRangeProps()
    const mergedRootProps = mergeProps(
      rootProps,
      props as React.HTMLAttributes<HTMLDivElement>
    ) as React.HTMLAttributes<HTMLDivElement>
    const { className: rootClassName, ...rootRest } = mergedRootProps as {
      className?: string
    }

    return (
      <div
        {...(rootRest as React.HTMLAttributes<HTMLDivElement>)}
        ref={ref}
        data-slot="slider"
        className={cn(
          'relative flex w-full touch-none select-none items-center data-[disabled]:opacity-50 data-[orientation=vertical]:h-full data-[orientation=vertical]:min-h-44 data-[orientation=vertical]:w-auto data-[orientation=vertical]:flex-col',
          rootClassName,
          className
        )}
      >
        <div
          {...controlProps}
          data-slot="slider-control"
          className={cn(
            'relative flex w-full touch-none select-none items-center data-[orientation=vertical]:h-full data-[orientation=vertical]:min-h-44 data-[orientation=vertical]:w-auto data-[orientation=vertical]:flex-col',
            controlProps.className
          )}
        >
          <div
            {...trackProps}
            data-slot="slider-track"
            className={cn(
              'bg-secondary relative grow overflow-hidden rounded-full data-[orientation=horizontal]:h-2 data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-2',
              trackProps.className
            )}
          >
            <div
              {...rangeProps}
              data-slot="slider-range"
              className={cn(
                'bg-primary absolute data-[orientation=horizontal]:h-full data-[orientation=vertical]:w-full',
                rangeProps.className
              )}
            />
          </div>
          {api.value.map((_, index) => {
            const thumbProps = api.getThumbProps({ index })
            const hiddenInputProps = api.getHiddenInputProps({ index })
            return (
              <React.Fragment key={index}>
                <div
                  {...thumbProps}
                  data-slot="slider-thumb"
                  className={cn(
                    'border-primary bg-background ring-ring/50 block size-5 shrink-0 rounded-full border-2 shadow-sm transition-[color,box-shadow] outline-none hover:ring-4 focus-visible:ring-4 disabled:pointer-events-none disabled:opacity-50',
                    thumbProps.className
                  )}
                />
                <input {...hiddenInputProps} />
              </React.Fragment>
            )
          })}
        </div>
      </div>
    )
  }
)

Slider.displayName = 'Slider'

export { Slider }
