// apps/docs/registry/default/vue/multiselect.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { cn } from "@/lib/utils";
import { XIcon } from "lucide-vue-next";
import Command from "./command.vue";
import CommandEmpty from "./command-empty.vue";
import CommandGroup from "./command-group.vue";
import CommandItem from "./command-item.vue";
import CommandList from "./command-list.vue";
import CommandInput from "./command-input.vue";

export interface Option {
  value: string;
  label: string;
  disable?: boolean;
  fixed?: boolean;
  [key: string]: string | boolean | undefined;
}

interface GroupOption {
  [key: string]: Option[];
}

const props = defineProps<{
  modelValue?: Option[];
  defaultOptions?: Option[];
  options?: Option[];
  placeholder?: string;
  loadingIndicator?: any;
  emptyIndicator?: any;
  delay?: number;
  triggerSearchOnFocus?: boolean;
  onSearch?: (value: string) => Promise<Option[]>;
  onSearchSync?: (value: string) => Option[];
  maxSelected?: number;
  onMaxSelected?: (maxLimit: number) => void;
  hidePlaceholderWhenSelected?: boolean;
  disabled?: boolean;
  groupBy?: string;
  class?: string;
  badgeClass?: string;
  selectFirstItem?: boolean;
  creatable?: boolean;
  hideClearAllButton?: boolean;
}>();

const emit = defineEmits(["update:modelValue", "change"]);

const inputRef = ref<{ inputEl?: HTMLInputElement | null } | null>(null);
const listId = `multiselect-list-${Math.random().toString(36).slice(2)}`;
const dropdownRef = ref<{ rootEl?: HTMLElement | null } | null>(null);
const open = ref(false);
const onScrollbar = ref(false);
const isLoading = ref(false);

const selected = ref<Option[]>(props.modelValue ?? []);
const options = ref<GroupOption>({});
const inputValue = ref("");

const maxSelected = computed(() => props.maxSelected ?? Number.MAX_SAFE_INTEGER);
const selectFirstItem = computed(() => props.selectFirstItem ?? true);

const transToGroupOption = (list: Option[] = [], groupBy?: string): GroupOption => {
  if (list.length === 0) return {};
  if (!groupBy) return { "": list };
  const groupOption: GroupOption = {};
  list.forEach((option) => {
    const key = (option[groupBy] as string) || "";
    if (!groupOption[key]) groupOption[key] = [];
    groupOption[key].push(option);
  });
  return groupOption;
};

const removePickedOption = (groupOption: GroupOption, picked: Option[]) => {
  const clone = JSON.parse(JSON.stringify(groupOption)) as GroupOption;
  for (const [key, value] of Object.entries(clone)) {
    clone[key] = value.filter((val) => !picked.find((p) => p.value === val.value));
  }
  return clone;
};

const isOptionsExist = (groupOption: GroupOption, targetOption: Option[]) => {
  for (const [, value] of Object.entries(groupOption)) {
    if (value.some((option) => targetOption.find((p) => p.value === option.value))) {
      return true;
    }
  }
  return false;
};

const debouncedSearchTerm = ref("");
let debounceTimer: number | null = null;
watch(
  () => inputValue.value,
  (val) => {
    if (debounceTimer) window.clearTimeout(debounceTimer);
    debounceTimer = window.setTimeout(() => {
      debouncedSearchTerm.value = val;
    }, props.delay ?? 500);
  }
);

watch(
  () => props.modelValue,
  (val) => {
    if (val) selected.value = val;
  }
);

watch(
  () => props.options,
  (val) => {
    if (!val || props.onSearch) return;
    options.value = transToGroupOption(val, props.groupBy);
  },
  { deep: true }
);

watch(
  () => props.defaultOptions,
  (val) => {
    if (!props.options && !props.onSearch) {
      options.value = transToGroupOption(val ?? [], props.groupBy);
    }
  },
  { deep: true, immediate: true }
);

watch(
  () => [debouncedSearchTerm.value, open.value, props.groupBy],
  async () => {
    if (!props.onSearchSync || !open.value) return;
    if (props.triggerSearchOnFocus || debouncedSearchTerm.value) {
      const res = props.onSearchSync?.(debouncedSearchTerm.value) ?? [];
      options.value = transToGroupOption(res, props.groupBy);
    }
  }
);

watch(
  () => [debouncedSearchTerm.value, open.value, props.groupBy],
  async () => {
    if (!props.onSearch || !open.value) return;
    if (props.triggerSearchOnFocus || debouncedSearchTerm.value) {
      isLoading.value = true;
      const res = (await props.onSearch?.(debouncedSearchTerm.value)) ?? [];
      options.value = transToGroupOption(res, props.groupBy);
      isLoading.value = false;
    }
  }
);

const selectables = computed(() => removePickedOption(options.value, selected.value));
const flatSelectables = computed(() =>
  Object.values(selectables.value).flat().filter((item) => !item.disable)
);

const handleUnselect = (option: Option) => {
  const next = selected.value.filter((s) => s.value !== option.value);
  selected.value = next;
  emit("update:modelValue", next);
  emit("change", next);
};

const getInputEl = () => inputRef.value?.inputEl ?? null;

const handleClickOutside = (event: MouseEvent | TouchEvent) => {
  const rootEl = dropdownRef.value?.rootEl ?? null;
  if (
    rootEl &&
    !rootEl.contains(event.target as Node) &&
    getInputEl() &&
    !getInputEl()?.contains(event.target as Node)
  ) {
    open.value = false;
    getInputEl()?.blur();
  }
};

onMounted(() => {
  document.addEventListener("mousedown", handleClickOutside);
  document.addEventListener("touchend", handleClickOutside);
});

onBeforeUnmount(() => {
  document.removeEventListener("mousedown", handleClickOutside);
  document.removeEventListener("touchend", handleClickOutside);
});

const creatableItem = computed(() => {
  if (!props.creatable) return undefined;
  if (
    isOptionsExist(options.value, [{ value: inputValue.value, label: inputValue.value }]) ||
    selected.value.find((s) => s.value === inputValue.value)
  ) {
    return undefined;
  }
  if (!props.onSearch && inputValue.value.length > 0) return inputValue.value;
  if (props.onSearch && debouncedSearchTerm.value.length > 0 && !isLoading.value) {
    return inputValue.value;
  }
  return undefined;
});

const emptyItem = computed(() => {
  if (!props.emptyIndicator) return undefined;
  if (props.onSearch && !props.creatable && Object.keys(options.value).length === 0) {
    return props.emptyIndicator;
  }
  return props.emptyIndicator;
});

const emptyIndicatorIsComponent = computed(() => {
  const value = emptyItem.value;
  return typeof value === "object" || typeof value === "function";
});

const onInputValueChange = (value: string) => {
  inputValue.value = value;
};

const onKeyDown = (event: KeyboardEvent) => {
  if (event.key === "Delete" || event.key === "Backspace") {
    if (inputValue.value === "" && selected.value.length > 0) {
      const last = selected.value[selected.value.length - 1];
      if (!last.fixed) handleUnselect(last);
    }
  }
  if (event.key === "Escape") {
    getInputEl()?.blur();
  }
};

const getCommandApi = () => dropdownRef.value?.api?.value ?? null;
const highlightFirst = () => {
  const api = getCommandApi();
  const first = flatSelectables.value[0];
  if (api && first) api.setHighlightValue(first.value);
};
const highlightLast = () => {
  const api = getCommandApi();
  const last = flatSelectables.value[flatSelectables.value.length - 1];
  if (api && last) api.setHighlightValue(last.value);
};

const onInputKeyDown = (event: KeyboardEvent) => {
  if (event.key === "Home") {
    event.preventDefault();
    if (!open.value) {
      inputValue.value = "";
      return;
    }
    highlightFirst();
    return;
  }
  if (event.key === "End") {
    event.preventDefault();
    if (open.value) {
      highlightLast();
      return;
    }
    openDropdown();
    return;
  }
  if (event.key === "PageDown" || event.key === "PageUp") {
    openDropdown();
    if (event.key === "PageDown") highlightLast();
    else highlightFirst();
    return;
  }
  if (event.key === "ArrowDown" || event.key === "ArrowUp") {
    openDropdown();
  }
  onKeyDown(event);
};

const setSelected = (next: Option[]) => {
  selected.value = next;
  emit("update:modelValue", next);
  emit("change", next);
};

const openDropdown = () => {
  if (props.disabled) return;
  open.value = true;
  getInputEl()?.focus();
  if (props.triggerSearchOnFocus) {
    props.onSearch?.(debouncedSearchTerm.value);
  }
};
</script>

<template>
  <Command
    ref="dropdownRef"
    class="h-auto overflow-visible bg-transparent"
    @keydown="onKeyDown"
  >
    <div
      :class="
        cn(
          'border-input focus-within:border-ring focus-within:ring-ring/50 has-aria-invalid:ring-destructive/20 dark:has-aria-invalid:ring-destructive/40 has-aria-invalid:border-destructive relative min-h-[38px] rounded-md border text-sm transition-[color,box-shadow] outline-none focus-within:ring-[3px] has-disabled:pointer-events-none has-disabled:cursor-not-allowed has-disabled:opacity-50',
          {
            'p-1': selected.length !== 0,
            'cursor-text': !props.disabled && selected.length !== 0,
          },
          !props.hideClearAllButton && 'pe-9',
          props.class
        )
      "
      @focusin="openDropdown"
      @focusout="() => { if (!onScrollbar) open = false }"
      @click="openDropdown"
    >
      <div class="flex flex-wrap gap-1">
        <div
          v-for="option in selected"
          :key="option.value"
          :class="
            cn(
              'animate-fadeIn bg-background text-secondary-foreground hover:bg-background relative inline-flex h-7 cursor-default items-center rounded-md border ps-2 pe-7 pl-2 text-xs font-medium transition-all disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 data-fixed:pe-2',
              props.badgeClass
            )
          "
          :data-fixed="option.fixed"
          :data-disabled="props.disabled || undefined"
        >
          {{ option.label }}
          <button
            class="text-muted-foreground/80 hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 absolute -inset-y-px -end-px flex size-7 items-center justify-center rounded-e-md border border-transparent p-0 outline-hidden transition-[color,box-shadow] outline-none focus-visible:ring-[3px]"
            type="button"
            @mousedown.prevent.stop
            @click="handleUnselect(option)"
          >
            <XIcon :size="14" aria-hidden="true" />
          </button>
        </div>
        <CommandInput
          ref="inputRef"
          :on-value-change="onInputValueChange"
          :list-id="listId"
          :expanded="open"
          :placeholder="props.hidePlaceholderWhenSelected && selected.length !== 0 ? '' : props.placeholder"
          :class="
            cn(
              'placeholder:text-muted-foreground/70 flex-1 bg-transparent outline-hidden disabled:cursor-not-allowed',
              {
                'w-full': props.hidePlaceholderWhenSelected,
                'px-3 py-2': selected.length === 0,
                'ml-1': selected.length !== 0,
              }
            )
          "
          @focus="openDropdown"
          @blur="() => { if (!onScrollbar) open = false }"
          @keydown="onInputKeyDown"
        />
        <button
          type="button"
          :class="
            cn(
              'text-muted-foreground/80 hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 absolute end-0 top-0 flex size-9 items-center justify-center rounded-md border border-transparent transition-[color,box-shadow] outline-none focus-visible:ring-[3px]',
              (props.hideClearAllButton ||
                props.disabled ||
                selected.length < 1 ||
                selected.filter((s) => s.fixed).length === selected.length) &&
                'hidden'
            )
          "
          aria-label="Clear all"
          @click="
            () => {
              const next = selected.filter((s) => s.fixed);
              setSelected(next);
            }
          "
        >
          <XIcon :size="16" aria-hidden="true" />
        </button>
      </div>
    </div>
    <div class="relative">
      <div
        :class="
          cn(
            'border-input absolute top-2 z-10 w-full overflow-hidden rounded-md border',
            'data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
            !open && 'hidden'
          )
        "
        :data-state="open ? 'open' : 'closed'"
      >
        <CommandList
          v-if="open"
          :id="listId"
          class="bg-popover text-popover-foreground shadow-lg outline-hidden"
          @mouseleave="onScrollbar = false"
          @mouseenter="onScrollbar = true"
          @mouseup="() => getInputEl()?.focus()"
        >
          <template v-if="isLoading">
            <component :is="props.loadingIndicator" />
          </template>
          <template v-else>
            <CommandEmpty v-if="props.emptyIndicator">
              <component v-if="emptyIndicatorIsComponent" :is="emptyItem" />
              <span v-else>{{ emptyItem }}</span>
            </CommandEmpty>
            <CommandItem
              v-if="creatableItem"
              :value="creatableItem"
              class="cursor-pointer"
              @mousedown.prevent.stop
              @click="
                () => {
                  if (selected.length >= maxSelected) {
                    props.onMaxSelected?.(selected.length);
                    return;
                  }
                  inputValue = '';
                  const next = [...selected, { value: creatableItem, label: creatableItem }];
                  setSelected(next);
                }
              "
            >
              Create "{{ creatableItem }}"
            </CommandItem>
            <CommandItem v-if="!selectFirstItem" value="-" class="hidden" />
            <CommandGroup
              v-for="(dropdowns, key) in selectables"
              :key="key"
              :heading="key"
              class="h-full overflow-auto"
            >
              <CommandItem
                v-for="option in dropdowns"
                :key="option.value"
                :value="option.value"
                :disabled="option.disable"
                class="cursor-pointer"
                @mousedown.prevent.stop
                @click="
                  () => {
                    if (selected.length >= maxSelected) {
                      props.onMaxSelected?.(selected.length);
                      return;
                    }
                    inputValue = '';
                    const next = [...selected, option];
                    setSelected(next);
                  }
                "
              >
                {{ option.label }}
              </CommandItem>
            </CommandGroup>
          </template>
        </CommandList>
      </div>
    </div>
  </Command>
</template>

// registry/react/ui/multiselect.tsx
'use client'

import * as React from 'react'
import { Command as CommandPrimitive, useCommandState } from 'cmdk'

import { cva } from '../lib/cva'
import { cn } from '../lib/utils'
import { Command, CommandGroup, CommandItem, CommandList } from './command'

// Variants
const multiselectCommandVariants = cva('h-auto overflow-visible bg-transparent')
const multiselectContainerVariants = cva(
  'border-input focus-within:border-ring focus-within:ring-ring/50 has-aria-invalid:ring-destructive/20 dark:has-aria-invalid:ring-destructive/40 has-aria-invalid:border-destructive relative min-h-[38px] rounded-md border text-sm transition-[color,box-shadow] outline-none focus-within:ring-[3px] has-disabled:pointer-events-none has-disabled:cursor-not-allowed has-disabled:opacity-50'
)
const multiselectTagVariants = cva(
  'animate-fadeIn bg-background text-secondary-foreground hover:bg-background relative inline-flex h-7 cursor-default items-center rounded-md border ps-2 pe-7 pl-2 text-xs font-medium transition-all disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 data-fixed:pe-2'
)
const multiselectTagRemoveVariants = cva(
  'text-muted-foreground/80 hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 absolute -inset-y-px -end-px flex size-7 items-center justify-center rounded-e-md border border-transparent p-0 outline-hidden transition-[color,box-shadow] outline-none focus-visible:ring-[3px]'
)
const multiselectInputVariants = cva(
  'placeholder:text-muted-foreground/70 flex-1 bg-transparent outline-hidden disabled:cursor-not-allowed'
)
const multiselectClearButtonVariants = cva(
  'text-muted-foreground/80 hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 absolute end-0 top-0 flex size-9 items-center justify-center rounded-md border border-transparent transition-[color,box-shadow] outline-none focus-visible:ring-[3px]'
)
const multiselectDropdownVariants = cva(
  'border-input absolute top-2 z-10 w-full overflow-hidden rounded-md border'
)
const multiselectListVariants = cva('bg-popover text-popover-foreground shadow-lg outline-hidden')
const multiselectEmptyVariants = cva('px-2 py-4 text-center text-sm')
const multiselectGroupVariants = cva('h-full overflow-auto')

export interface Option {
  value: string
  label: string
  disable?: boolean
  fixed?: boolean
  [key: string]: string | boolean | undefined
}

interface GroupOption {
  [key: string]: Option[]
}

interface MultipleSelectorProps {
  value?: Option[]
  defaultOptions?: Option[]
  options?: Option[]
  placeholder?: string
  loadingIndicator?: React.ReactNode
  emptyIndicator?: React.ReactNode
  delay?: number
  triggerSearchOnFocus?: boolean
  onSearch?: (value: string) => Promise<Option[]>
  onSearchSync?: (value: string) => Option[]
  onChange?: (options: Option[]) => void
  onValueChange?: (options: Option[]) => void // Duplicate of onChange for consistency?
  maxSelected?: number
  onMaxSelected?: (maxLimit: number) => void
  hidePlaceholderWhenSelected?: boolean
  disabled?: boolean
  groupBy?: string
  className?: string
  badgeClassName?: string
  selectFirstItem?: boolean
  creatable?: boolean
  commandProps?: React.ComponentPropsWithoutRef<typeof Command>
  inputProps?: Omit<
    React.ComponentPropsWithoutRef<typeof CommandPrimitive.Input>,
    'value' | 'placeholder' | 'disabled'
  >
  hideClearAllButton?: boolean
}

export interface MultipleSelectorRef {
  selectedValue: Option[]
  input: HTMLInputElement
  focus: () => void
  reset: () => void
}

function useDebounce<T>(value: T, delay?: number): T {
  const [debouncedValue, setDebouncedValue] = React.useState<T>(value)

  React.useEffect(() => {
    const timer = setTimeout(() => setDebouncedValue(value), delay || 500)

    return () => {
      clearTimeout(timer)
    }
  }, [value, delay])

  return debouncedValue
}

function transToGroupOption(options: Option[], groupBy?: string) {
  if (options.length === 0) {
    return {}
  }
  if (!groupBy) {
    return {
      '': options,
    }
  }

  const groupOption: GroupOption = {}
  options.forEach((option) => {
    const key = (option[groupBy] as string) || ''
    if (!groupOption[key]) {
      groupOption[key] = []
    }
    groupOption[key].push(option)
  })
  return groupOption
}

function removePickedOption(groupOption: GroupOption, picked: Option[]) {
  const cloneOption = JSON.parse(JSON.stringify(groupOption)) as GroupOption

  for (const [key, value] of Object.entries(cloneOption)) {
    cloneOption[key] = value.filter((val) => !picked.find((p) => p.value === val.value))
  }
  return cloneOption
}

function isOptionsExist(groupOption: GroupOption, targetOption: Option[]) {
  for (const [, value] of Object.entries(groupOption)) {
    if (value.some((option) => targetOption.find((p) => p.value === option.value))) {
      return true
    }
  }
  return false
}

const CommandEmpty = ({
  className,
  ...props
}: React.ComponentProps<typeof CommandPrimitive.Empty>) => {
  const render = useCommandState((state) => state.filtered.count === 0)

  if (!render) return null

  return (
    <div
      className={cn(multiselectEmptyVariants(), className)}
      cmdk-empty=""
      role="presentation"
      {...props}
    />
  )
}
CommandEmpty.displayName = 'CommandEmpty'

const MultipleSelector = React.forwardRef<MultipleSelectorRef, MultipleSelectorProps>(
  (
    {
      value,
      onChange,
      onValueChange,
      placeholder,
      defaultOptions: arrayDefaultOptions = [],
      options: arrayOptions,
      delay,
      onSearch,
      onSearchSync,
      loadingIndicator,
      emptyIndicator,
      maxSelected = Number.MAX_SAFE_INTEGER,
      onMaxSelected,
      hidePlaceholderWhenSelected,
      disabled,
      groupBy,
      className,
      badgeClassName,
      selectFirstItem = true,
      creatable = false,
      triggerSearchOnFocus = false,
      commandProps,
      inputProps,
      hideClearAllButton = false,
    },
    ref
  ) => {
    const emitValueChange = React.useCallback(
      (next: Option[]) => {
        onValueChange?.(next)
        onChange?.(next)
      },
      [onChange, onValueChange]
    )

    const inputRef = React.useRef<HTMLInputElement>(null)
    const [open, setOpen] = React.useState(false)
    const [onScrollbar, setOnScrollbar] = React.useState(false)
    const [isLoading, setIsLoading] = React.useState(false)
    const dropdownRef = React.useRef<HTMLDivElement>(null)

    const [selected, setSelected] = React.useState<Option[]>(value || [])
    const [options, setOptions] = React.useState<GroupOption>(
      transToGroupOption(arrayDefaultOptions, groupBy)
    )
    const [inputValue, setInputValue] = React.useState('')
    const debouncedSearchTerm = useDebounce(inputValue, delay || 500)

    React.useImperativeHandle(
      ref,
      () => ({
        selectedValue: [...selected],
        input: inputRef.current as HTMLInputElement,
        focus: () => inputRef.current?.focus(),
        reset: () => {
          setSelected([])
          emitValueChange([])
        },
      }),
      [selected, emitValueChange]
    )

    const handleClickOutside = (event: MouseEvent | TouchEvent) => {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node) &&
        inputRef.current &&
        !inputRef.current.contains(event.target as Node)
      ) {
        setOpen(false)
        inputRef.current.blur()
      }
    }

    const handleUnselect = React.useCallback(
      (option: Option) => {
        const newOptions = selected.filter((s) => s.value !== option.value)
        setSelected(newOptions)
        emitValueChange(newOptions)
      },
      [emitValueChange, selected]
    )

    const handleKeyDown = React.useCallback(
      (e: React.KeyboardEvent<HTMLDivElement>) => {
        const input = inputRef.current
        if (input) {
          if (e.key === 'Delete' || e.key === 'Backspace') {
            if (input.value === '' && selected.length > 0) {
              const lastSelectOption = selected[selected.length - 1]
              if (!lastSelectOption.fixed) {
                handleUnselect(selected[selected.length - 1])
              }
            }
          }
          if (e.key === 'Escape') {
            input.blur()
          }
        }
      },
      [handleUnselect, selected]
    )

    React.useEffect(() => {
      if (open) {
        document.addEventListener('mousedown', handleClickOutside)
        document.addEventListener('touchend', handleClickOutside)
      } else {
        document.removeEventListener('mousedown', handleClickOutside)
        document.removeEventListener('touchend', handleClickOutside)
      }

      return () => {
        document.removeEventListener('mousedown', handleClickOutside)
        document.removeEventListener('touchend', handleClickOutside)
      }
    }, [open])

    React.useEffect(() => {
      if (value) {
        setSelected(value)
      }
    }, [value])

    React.useEffect(() => {
      if (!arrayOptions || onSearch) {
        return
      }
      const newOption = transToGroupOption(arrayOptions || [], groupBy)
      if (JSON.stringify(newOption) !== JSON.stringify(options)) {
        setOptions(newOption)
      }
    }, [arrayDefaultOptions, arrayOptions, groupBy, onSearch, options])

    React.useEffect(() => {
      const doSearchSync = () => {
        const res = onSearchSync?.(debouncedSearchTerm)
        setOptions(transToGroupOption(res || [], groupBy))
      }

      const exec = async () => {
        if (!onSearchSync || !open) return

        if (triggerSearchOnFocus) {
          doSearchSync()
        }

        if (debouncedSearchTerm) {
          doSearchSync()
        }
      }

      void exec()
    }, [debouncedSearchTerm, groupBy, open, triggerSearchOnFocus, onSearchSync])

    React.useEffect(() => {
      const doSearch = async () => {
        setIsLoading(true)
        const res = await onSearch?.(debouncedSearchTerm)
        setOptions(transToGroupOption(res || [], groupBy))
        setIsLoading(false)
      }

      const exec = async () => {
        if (!onSearch || !open) return

        if (triggerSearchOnFocus) {
          await doSearch()
        }

        if (debouncedSearchTerm) {
          await doSearch()
        }
      }

      void exec()
    }, [debouncedSearchTerm, groupBy, open, triggerSearchOnFocus, onSearch])

    const CreatableItem = () => {
      if (!creatable) return undefined
      if (
        isOptionsExist(options, [{ value: inputValue, label: inputValue }]) ||
        selected.find((s) => s.value === inputValue)
      ) {
        return undefined
      }

      const Item = (
        <CommandItem
          value={inputValue}
          className="cursor-pointer"
          onMouseDown={(e) => {
            e.preventDefault()
            e.stopPropagation()
          }}
          onSelect={(value: string) => {
            if (selected.length >= maxSelected) {
              onMaxSelected?.(selected.length)
              return
            }
            setInputValue('')
            const newOptions = [...selected, { value, label: value }]
            setSelected(newOptions)
            emitValueChange(newOptions)
          }}
        >
          {`Create "${inputValue}"`}
        </CommandItem>
      )

      if (!onSearch && inputValue.length > 0) {
        return Item
      }

      if (onSearch && debouncedSearchTerm.length > 0 && !isLoading) {
        return Item
      }

      return undefined
    }

    const EmptyItem = React.useCallback(() => {
      if (!emptyIndicator) return undefined

      if (onSearch && !creatable && Object.keys(options).length === 0) {
        return (
          <CommandItem value="-" disabled>
            {emptyIndicator}
          </CommandItem>
        )
      }

      return <CommandEmpty>{emptyIndicator}</CommandEmpty>
    }, [creatable, emptyIndicator, onSearch, options])

    const selectables = React.useMemo<GroupOption>(
      () => removePickedOption(options, selected),
      [options, selected]
    )

    const commandFilter = React.useCallback(() => {
      if (commandProps?.filter) {
        return commandProps.filter
      }

      if (creatable) {
        return (value: string, search: string) => {
          return value.toLowerCase().includes(search.toLowerCase()) ? 1 : -1
        }
      }
      return undefined
    }, [creatable, commandProps?.filter])

    return (
      <Command
        ref={dropdownRef}
        {...commandProps}
        onKeyDown={(e) => {
          handleKeyDown(e)
          commandProps?.onKeyDown?.(e)
        }}
        className={cn(multiselectCommandVariants(), commandProps?.className)}
        shouldFilter={
          commandProps?.shouldFilter !== undefined ? commandProps.shouldFilter : !onSearch
        }
        filter={commandFilter()}
      >
        <div
          className={cn(
            multiselectContainerVariants(),
            {
              'p-1': selected.length !== 0,
              'cursor-text': !disabled && selected.length !== 0,
            },
            !hideClearAllButton && 'pe-9',
            className
          )}
          onClick={() => {
            if (disabled) return
            inputRef?.current?.focus()
          }}
        >
          <div className="flex flex-wrap gap-1">
            {selected.map((option) => {
              return (
                <div
                  key={option.value}
                  className={cn(multiselectTagVariants(), badgeClassName)}
                  data-fixed={option.fixed}
                  data-disabled={disabled || undefined}
                >
                  {option.label}
                  <button
                    className={multiselectTagRemoveVariants()}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        handleUnselect(option)
                      }
                    }}
                    onMouseDown={(e) => {
                      e.preventDefault()
                      e.stopPropagation()
                    }}
                    onClick={() => handleUnselect(option)}
                    aria-label="Remove"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="14"
                      height="14"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      aria-hidden="true"
                    >
                      <path d="M18 6 6 18" />
                      <path d="m6 6 12 12" />
                    </svg>
                  </button>
                </div>
              )
            })}
            <CommandPrimitive.Input
              {...inputProps}
              ref={inputRef}
              value={inputValue}
              disabled={disabled}
              onValueChange={(value) => {
                setInputValue(value)
                inputProps?.onValueChange?.(value)
              }}
              onBlur={(event) => {
                if (!onScrollbar) {
                  setOpen(false)
                }
                inputProps?.onBlur?.(event)
              }}
              onFocus={(event) => {
                setOpen(true)
                if (triggerSearchOnFocus) {
                  onSearch?.(debouncedSearchTerm)
                }
                inputProps?.onFocus?.(event)
              }}
              placeholder={hidePlaceholderWhenSelected && selected.length !== 0 ? '' : placeholder}
              className={cn(
                multiselectInputVariants(),
                {
                  'w-full': hidePlaceholderWhenSelected,
                  'px-3 py-2': selected.length === 0,
                  'ml-1': selected.length !== 0,
                },
                inputProps?.className
              )}
            />
            <button
              type="button"
              onClick={() => {
                setSelected(selected.filter((s) => s.fixed))
                emitValueChange(selected.filter((s) => s.fixed))
              }}
              className={cn(
                multiselectClearButtonVariants(),
                (hideClearAllButton ||
                  disabled ||
                  selected.length < 1 ||
                  selected.filter((s) => s.fixed).length === selected.length) &&
                  'hidden'
              )}
              aria-label="Clear all"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <path d="M18 6 6 18" />
                <path d="m6 6 12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div className="relative">
          <div
            className={cn(
              multiselectDropdownVariants(),
              'data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
              !open && 'hidden'
            )}
            data-state={open ? 'open' : 'closed'}
          >
            {open && (
              <CommandList
                className={multiselectListVariants()}
                onMouseLeave={() => {
                  setOnScrollbar(false)
                }}
                onMouseEnter={() => {
                  setOnScrollbar(true)
                }}
                onMouseUp={() => {
                  inputRef?.current?.focus()
                }}
              >
                {isLoading ? (
                  <>{loadingIndicator}</>
                ) : (
                  <>
                    {EmptyItem()}
                    {CreatableItem()}
                    {!selectFirstItem && <CommandItem value="-" className="hidden" />}
                    {Object.entries(selectables).map(([key, dropdowns]) => (
                      <CommandGroup key={key} heading={key} className={multiselectGroupVariants()}>
                        <>
                          {dropdowns.map((option) => {
                            return (
                              <CommandItem
                                key={option.value}
                                value={option.value}
                                disabled={option.disable}
                                onMouseDown={(e) => {
                                  e.preventDefault()
                                  e.stopPropagation()
                                }}
                                onSelect={() => {
                                  if (selected.length >= maxSelected) {
                                    onMaxSelected?.(selected.length)
                                    return
                                  }
                                  setInputValue('')
                                  const newOptions = [...selected, option]
                                  setSelected(newOptions)
                                  emitValueChange(newOptions)
                                }}
                                className={cn(
                                  'cursor-pointer',
                                  option.disable &&
                                    'pointer-events-none cursor-not-allowed opacity-50'
                                )}
                              >
                                {option.label}
                              </CommandItem>
                            )
                          })}
                        </>
                      </CommandGroup>
                    ))}
                  </>
                )}
              </CommandList>
            )}
          </div>
        </div>
      </Command>
    )
  }
)

MultipleSelector.displayName = 'MultipleSelector'
export default MultipleSelector
