// apps/docs/registry/default/components/notification/notification-21.tsx
'use client'

import { toast } from 'sonner'

import { Button } from '../../ui/button'

export default function Component() {
  return (
    <Button
      variant="outline"
      onClick={() => {
        toast('Your request was completed!', {
          description: 'It was a long journey, but we made it!',
          action: {
            label: 'Undo',
            onClick: () => console.log('Undo'),
          },
        })
      }}
    >
      Show sonner
    </Button>
  )
}

// apps/docs/registry/default/components/notification/notification-21.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';



</script>

<template>
  <Button variant="outline" @click="{
        toast('Your request was completed!', {
          description: 'It was a long journey, but we made it!',
          action: {
            label: 'Undo',
            onClick: () => console.log('Undo'),
          },
        })
      }">Show sonner
    </Button>
</template>
