// packages/react/src/components/ui/slider.tsx
'use client'

import * as React from 'react'
import type { AssertNoExtraKeys, SliderProps as CoreSliderProps } from '@timui/core'
import {
  cn,
  createTimEvent,
  sliderConnect,
  sliderMachine,
  sliderRangeVariants,
  sliderRootVariants,
  sliderThumbVariants,
  sliderTrackVariants,
} from '@timui/core'
import { mergeProps } from '@zag-js/react'

import { useSlider } from './slider/use-slider'

type SliderProps = CoreSliderProps & {
  showTooltip?: boolean
  tooltipContent?: (value: number) => string
} & Omit<React.HTMLAttributes<HTMLDivElement>, keyof CoreSliderProps | 'showTooltip'>

const Slider = React.forwardRef<HTMLDivElement, SliderProps>(
  (
    {
      className,
      value,
      defaultValue,
      min = 0,
      max = 100,
      step = 1,
      showTooltip: _showTooltip,
      tooltipContent: _tooltipContent,
      onValueChange,
      onValueChangeEnd,
      disabled,
      id,
      ...props
    },
    ref
  ) => {
    void _showTooltip
    void _tooltipContent
    const api = useSlider({
      id,
      value,
      defaultValue,
      min,
      max,
      step,
      disabled,
      onValueChange,
      onValueChangeEnd,
    })
    const rootProps = api.getRootProps()
    const controlProps = api.getControlProps()
    const trackProps = api.getTrackProps()
    const rangeProps = api.getRangeProps()
    const mergedRootProps = mergeProps(
      rootProps,
      props as React.HTMLAttributes<HTMLDivElement>
    ) as React.HTMLAttributes<HTMLDivElement>
    const { className: rootClassName, ...rootRest } = mergedRootProps as {
      className?: string
    }

    return (
      <div
        {...(rootRest as React.HTMLAttributes<HTMLDivElement>)}
        ref={ref}
        data-slot="slider"
        className={cn(sliderRootVariants(), rootClassName, className)}
      >
        <div
          {...controlProps}
          data-slot="slider-control"
          className={cn(
            'relative flex w-full touch-none items-center select-none data-[orientation=vertical]:h-full data-[orientation=vertical]:min-h-44 data-[orientation=vertical]:w-auto data-[orientation=vertical]:flex-col',
            controlProps.className
          )}
        >
          <div
            {...trackProps}
            data-slot="slider-track"
            className={cn(sliderTrackVariants(), trackProps.className)}
          >
            <div
              {...rangeProps}
              data-slot="slider-range"
              className={cn(sliderRangeVariants(), rangeProps.className)}
            />
          </div>
          {api.value.map((_, index) => {
            const thumbProps = api.getThumbProps({ index })
            const hiddenInputProps = api.getHiddenInputProps({ index })
            return (
              <React.Fragment key={index}>
                <div
                  {...thumbProps}
                  data-slot="slider-thumb"
                  className={cn(sliderThumbVariants(), thumbProps.className)}
                />
                <input {...hiddenInputProps} />
              </React.Fragment>
            )
          })}
        </div>
      </div>
    )
  }
)
Slider.displayName = 'Slider'

export { Slider }

// packages/vue/src/components/ui/slider/slider.vue
<script setup lang="ts">
import { computed } from "vue";
import type { AssertNoExtraKeys, SliderVueProps } from "@timui/core";
import { sliderConnect, sliderMachine } from "@timui/core";
import { normalizeProps, useMachine } from "@zag-js/vue";
import {
  cn,
  sliderRangeVariants,
  sliderRootVariants,
  sliderThumbVariants,
  sliderTrackVariants,
} from "@timui/core";
import type { HTMLAttributes } from "vue";

import { useSlider } from "./use-slider";

type SliderProps = SliderVueProps & { class?: HTMLAttributes["class"] };
type _SliderPropsGuard = AssertNoExtraKeys<SliderProps, SliderProps>;

const props = defineProps<SliderProps>();

const emit = defineEmits(["update:modelValue", "change", "commit"]);

const api = useSlider(props, emit);
const rootProps = computed(() => api.value?.getRootProps?.() ?? {});
const controlProps = computed(() => api.value?.getControlProps?.() ?? {});
const trackProps = computed(() => api.value?.getTrackProps?.() ?? {});
const rangeProps = computed(() => api.value?.getRangeProps?.() ?? {});

const getThumbProps = (index: number) =>
  api.value?.getThumbProps?.({ index }) ?? {};
const getHiddenInputProps = (index: number) =>
  api.value?.getHiddenInputProps?.({ index }) ?? {};

const thumbPropsList = computed(() =>
  (api.value?.value ?? []).map((_, index) => getThumbProps(index))
);
const hiddenInputPropsList = computed(() =>
  (api.value?.value ?? []).map((_, index) => getHiddenInputProps(index))
);
</script>

<template>
  <div
    v-bind="rootProps"
    data-slot="slider"
    :class="cn(sliderRootVariants(), props.class)"
  >
    <div
      v-bind="controlProps"
      data-slot="slider-control"
      :class="
        cn(
          'relative flex w-full touch-none items-center select-none data-[orientation=vertical]:h-full data-[orientation=vertical]:min-h-44 data-[orientation=vertical]:w-auto data-[orientation=vertical]:flex-col',
          controlProps.class
        )
      "
    >
      <div
        v-bind="trackProps"
        data-slot="slider-track"
        :class="cn(sliderTrackVariants(), trackProps.class)"
      >
        <div
          v-bind="rangeProps"
          data-slot="slider-range"
          :class="cn(sliderRangeVariants(), rangeProps.class)"
        />
      </div>
      <template v-for="(thumbProps, index) in thumbPropsList" :key="index">
        <div
          v-bind="thumbProps"
          data-slot="slider-thumb"
          :class="cn(sliderThumbVariants(), thumbProps.class)"
        />
        <input v-bind="hiddenInputPropsList[index] ?? {}" />
      </template>
    </div>
  </div>
</template>
