// apps/docs/registry/default/components/select/select-30.tsx
import { useId, useMemo } from 'react'
import { Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@timui/react'

export default function Component() {
  const id = useId()

  const timezones = Intl.supportedValuesOf('timeZone')

  const formattedTimezones = useMemo(() => {
    return timezones
      .map((timezone) => {
        const formatter = new Intl.DateTimeFormat('en', {
          timeZone: timezone,
          timeZoneName: 'shortOffset',
        })
        const parts = formatter.formatToParts(new Date())
        const offset = parts.find((part) => part.type === 'timeZoneName')?.value || ''
        const modifiedOffset = offset === 'GMT' ? 'GMT+0' : offset

        return {
          value: timezone,
          label: `(${modifiedOffset}) ${timezone.replace(/_/g, ' ')}`,
          numericOffset: parseInt(offset.replace('GMT', '').replace('+', '') || '0'),
        }
      })
      .sort((a, b) => a.numericOffset - b.numericOffset)
  }, [timezones])

  return (
    <div className="*:not-first:mt-2">
      <Label htmlFor={id}>Timezone select</Label>
      <Select defaultValue="Europe/London">
        <SelectTrigger id={id}>
          <SelectValue placeholder="Select timezone" />
        </SelectTrigger>
        <SelectContent>
          {formattedTimezones.map(({ value, label }) => (
            <SelectItem key={value} value={value}>
              {label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
    </div>
  )
}

// apps/docs/registry/default/components/select/select-30.vue
<script setup lang="ts">
import { Label } from '@timui/vue';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@timui/vue';

const id = 'select-30';
const timezones = Intl.supportedValuesOf('timeZone');
const formattedTimezones = timezones
  .map((timezone) => {
    const formatter = new Intl.DateTimeFormat('en', {
      timeZone: timezone,
      timeZoneName: 'shortOffset',
    });
    const parts = formatter.formatToParts(new Date());
    const offset = parts.find((part) => part.type === 'timeZoneName')?.value || '';
    const modifiedOffset = offset === 'GMT' ? 'GMT+0' : offset;

    return {
      value: timezone,
      label: `(${modifiedOffset}) ${timezone.replace(/_/g, ' ')}`,
      numericOffset: parseInt(offset.replace('GMT', '').replace('+', '') || '0'),
    };
  })
  .sort((a, b) => a.numericOffset - b.numericOffset);

</script>

<template>
  <div class="*:not-first:mt-2"><Label :htmlFor="id">Timezone select</Label><Select default-value="Europe/London"><SelectTrigger :id="id"><SelectValue placeholder="Select timezone" /></SelectTrigger><SelectContent><SelectItem v-for="({ value, label }, index) in formattedTimezones" :key="value" :value="value">{{ label }}</SelectItem></SelectContent></Select></div>
</template>
