// apps/docs/registry/default/components/select/select-17.vue
<script setup lang="ts">
import { ClockIcon } from 'lucide-vue-next';
import { Label } from '@timui/vue';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@timui/vue';





const id = 'select-17';

</script>

<template>
  <div class="*:not-first:mt-2"><Label :htmlFor="id">Select with icon</Label><Select default-value="1"><SelectTrigger :id="id" class="relative ps-9"><div class="text-muted-foreground/80 pointer-events-none absolute inset-y-0 start-0 flex items-center justify-center ps-3 group-has-[select[disabled]]:opacity-50"><ClockIcon :size="16" aria-hidden="true" /></div><SelectValue placeholder="Select time" /></SelectTrigger><SelectContent><SelectItem value="1">00:00 AM - 11:59 PM</SelectItem><SelectItem value="2">01:00 AM - 12:59 PM</SelectItem><SelectItem value="3">02:00 AM - 01:59 PM</SelectItem><SelectItem value="4">03:00 AM - 02:59 PM</SelectItem></SelectContent></Select></div>
</template>

// apps/docs/registry/default/components/select/select-17.tsx
import { useId } from 'react'
import { Label, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@timui/react'
import { ClockIcon } from 'lucide-react'

export default function Component() {
  const id = useId()
  return (
    <div className="*:not-first:mt-2">
      <Label htmlFor={id}>Select with icon</Label>
      <Select defaultValue="1">
        <SelectTrigger id={id} className="relative ps-9">
          <div className="text-muted-foreground/80 pointer-events-none absolute inset-y-0 start-0 flex items-center justify-center ps-3 group-has-[select[disabled]]:opacity-50">
            <ClockIcon size={16} aria-hidden="true" />
          </div>
          <SelectValue placeholder="Select time" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="1">00:00 AM - 11:59 PM</SelectItem>
          <SelectItem value="2">01:00 AM - 12:59 PM</SelectItem>
          <SelectItem value="3">02:00 AM - 01:59 PM</SelectItem>
          <SelectItem value="4">03:00 AM - 02:59 PM</SelectItem>
        </SelectContent>
      </Select>
    </div>
  )
}
