// apps/docs/registry/default/components/avatar/avatar-03.tsx
import { Avatar, AvatarFallback } from '@timui/react'

export default function Component() {
  return (
    <Avatar>
      <AvatarFallback>
        <svg
          className="size-4 opacity-60"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <circle cx="12" cy="8" r="4" />
          <path d="M20 21a8 8 0 0 0-16 0" />
        </svg>
      </AvatarFallback>
    </Avatar>
  )
}

// apps/docs/registry/default/components/avatar/avatar-03.vue
<script setup lang="ts">
import { Avatar, AvatarFallback } from '@timui/vue';




</script>

<template>
  <Avatar><AvatarFallback><svg class="size-4 opacity-60" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="4" /><path d="M20 21a8 8 0 0 0-16 0" /></svg></AvatarFallback></Avatar>
</template>
