// apps/docs/registry/default/components/stepper/stepper-09.tsx
'use client'

import { useState } from 'react'
import { Button, Stepper, StepperIndicator, StepperItem, StepperTrigger } from '@timui/react'

const steps = [1, 2, 3, 4]

export default function Component() {
  const [currentStep, setCurrentStep] = useState(1)

  return (
    <div className="mx-auto max-w-xl space-y-8 text-center">
      <div className="space-y-3">
        <Stepper value={currentStep} onValueChange={setCurrentStep}>
          {steps.map((step) => (
            <StepperItem key={step} step={step} className="flex-1">
              <StepperTrigger className="w-full flex-col items-start gap-2" asChild>
                <StepperIndicator asChild className="bg-border h-2 w-full rounded-none">
                  <span className="sr-only">{step}</span>
                </StepperIndicator>
              </StepperTrigger>
            </StepperItem>
          ))}
        </Stepper>
        <div className="text-muted-foreground text-sm font-medium tabular-nums">
          Step {currentStep} of {steps.length}
        </div>
      </div>
      <div className="flex justify-center space-x-4">
        <Button
          variant="outline"
          className="w-32"
          onClick={() => setCurrentStep((prev) => prev - 1)}
          disabled={currentStep === 1}
        >
          Prev step
        </Button>
        <Button
          variant="outline"
          className="w-32"
          onClick={() => setCurrentStep((prev) => prev + 1)}
          disabled={currentStep >= steps.length}
        >
          Next step
        </Button>
      </div>
      <p className="text-muted-foreground mt-2 text-xs" role="region" aria-live="polite">
        Progress stepper
      </p>
    </div>
  )
}

// apps/docs/registry/default/components/stepper/stepper-09.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Button } from '@timui/vue';
import { Stepper } from '@timui/vue';
import { StepperIndicator } from '@timui/vue';
import { StepperItem } from '@timui/vue';
import { StepperTrigger } from '@timui/vue';



const currentStep = ref(1);


function setCurrentStep(next: typeof currentStep.value | ((prev: typeof currentStep.value) => typeof currentStep.value)) {
  currentStep.value = typeof next === 'function'
    ? (next as (prev: typeof currentStep.value) => typeof currentStep.value)(currentStep.value)
    : next;
}


const steps = [1, 2, 3, 4]

</script>

<template>
  <div class="mx-auto max-w-xl space-y-8 text-center"><div class="space-y-3"><Stepper :value="currentStep" @update:modelValue="setCurrentStep"><StepperItem v-for="(step, index) in steps" :key="step" :step="step" class="flex-1"><StepperTrigger class="w-full flex-col items-start gap-2" as-child><StepperIndicator as-child class="bg-border h-2 w-full rounded-none"><span class="sr-only">{{ step }}</span></StepperIndicator></StepperTrigger></StepperItem></Stepper><div class="text-muted-foreground text-sm font-medium tabular-nums">Step {{ currentStep }}of {{ steps.length }}</div></div><div class="flex justify-center space-x-4"><Button variant="outline" class="w-32" @click="setCurrentStep((prev) => prev - 1)" :disabled="currentStep === 1">Prev step
        </Button><Button variant="outline" class="w-32" @click="setCurrentStep((prev) => prev + 1)" :disabled="currentStep >= steps.length">Next step
        </Button></div><p class="text-muted-foreground mt-2 text-xs" role="region" aria-live="polite">Progress stepper
      </p></div>
</template>
