// apps/docs/registry/default/components/button/button-35.tsx
'use client'

import { useState } from 'react'

import { ToggleGroup, ToggleGroupItem } from '../../ui/toggle-group'

export default function Component() {
  const [value, setValue] = useState<string>('left')

  return (
    <ToggleGroup
      type="single"
      variant="outline"
      value={value}
      onValueChange={(value) => {
        if (value) setValue(value)
      }}
    >
      <ToggleGroupItem className="flex-1" value="left">
        Left
      </ToggleGroupItem>
      <ToggleGroupItem className="flex-1" value="center">
        Center
      </ToggleGroupItem>
      <ToggleGroupItem className="flex-1" value="right">
        Right
      </ToggleGroupItem>
    </ToggleGroup>
  )
}

// apps/docs/registry/default/components/button/button-35.vue
<script setup lang="ts">
import { ToggleGroup } from '@/components/ui/toggle-group';
import { ToggleGroupItem } from '@/components/ui/toggle-group-item';



</script>

<template>
  <ToggleGroup type="single" variant="outline" :value="value" @update:modelValue="{
        if (value) setValue(value)
      }"><ToggleGroupItem class="flex-1" value="left">Left
      </ToggleGroupItem><ToggleGroupItem class="flex-1" value="center">Center
      </ToggleGroupItem><ToggleGroupItem class="flex-1" value="right">Right
      </ToggleGroupItem></ToggleGroup>
</template>
