// apps/docs/registry/default/components/button/button-34.tsx
import { ToggleGroup, ToggleGroupItem } from '@timui/react'

export default function Component() {
  return (
    <ToggleGroup variant="outline" className="inline-flex" type="single">
      <ToggleGroupItem value="left">Left</ToggleGroupItem>
      <ToggleGroupItem value="center">Center</ToggleGroupItem>
      <ToggleGroupItem value="right">Right</ToggleGroupItem>
    </ToggleGroup>
  )
}

// apps/docs/registry/default/components/button/button-34.vue
<script setup lang="ts">
import { ToggleGroup } from '@timui/vue';
import { ToggleGroupItem } from '@timui/vue';




</script>

<template>
  <ToggleGroup variant="outline" class="inline-flex" type="single"><ToggleGroupItem value="left">Left</ToggleGroupItem><ToggleGroupItem value="center">Center</ToggleGroupItem><ToggleGroupItem value="right">Right</ToggleGroupItem></ToggleGroup>
</template>
