// apps/docs/registry/default/components/button/button-26.tsx
'use client'

import { useState } from 'react'
import { MoonIcon, SunIcon } from 'lucide-react'

import { Toggle } from '../../ui/toggle'

export default function Component() {
  const [theme, setTheme] = useState<string>('light')

  return (
    <div>
      <Toggle
        variant="outline"
        className="group data-[state=on]:hover:bg-muted size-9 data-[state=on]:bg-transparent"
        pressed={theme === 'dark'}
        onPressedChange={() => setTheme((prev) => (prev === 'dark' ? 'light' : 'dark'))}
        aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}
      >
        {/* Note: After dark mode implementation, rely on dark: prefix rather than group-data-[state=on]: */}
        <MoonIcon
          size={16}
          className="shrink-0 scale-0 opacity-0 transition-all group-data-[state=on]:scale-100 group-data-[state=on]:opacity-100"
          aria-hidden="true"
        />
        <SunIcon
          size={16}
          className="absolute shrink-0 scale-100 opacity-100 transition-all group-data-[state=on]:scale-0 group-data-[state=on]:opacity-0"
          aria-hidden="true"
        />
      </Toggle>
    </div>
  )
}

// apps/docs/registry/default/components/button/button-26.vue
<script setup lang="ts">
import { MoonIcon, SunIcon } from 'lucide-vue-next';
import { Toggle } from '@/components/ui/toggle';



</script>

<template>
  <div><Toggle variant="outline" class="group data-[state=on]:hover:bg-muted size-9 data-[state=on]:bg-transparent" :pressed="theme === 'dark'" :onPressedChange="() => setTheme((prev) => (prev === 'dark' ? 'light' : 'dark'))" :aria-label="`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`"><MoonIcon :size="16" class="shrink-0 scale-0 opacity-0 transition-all group-data-[state=on]:scale-100 group-data-[state=on]:opacity-100" aria-hidden="true" /><SunIcon :size="16" class="absolute shrink-0 scale-100 opacity-100 transition-all group-data-[state=on]:scale-0 group-data-[state=on]:opacity-0" aria-hidden="true" /></Toggle></div>
</template>
