// apps/docs/registry/default/components/button/button-18.tsx
import { Avatar, AvatarFallback, AvatarImage, Button } from '@timui/react'
import { ChevronDownIcon } from 'lucide-react'

export default function Component() {
  return (
    <Button variant="ghost" className="h-auto p-0 hover:bg-transparent">
      <Avatar>
        <AvatarImage src="./avatar.jpg" alt="Profile image" />
        <AvatarFallback>KK</AvatarFallback>
      </Avatar>
      <ChevronDownIcon size={16} className="opacity-60" aria-hidden="true" />
    </Button>
  )
}

// apps/docs/registry/default/components/button/button-18.vue
<script setup lang="ts">
import { ChevronDownIcon } from 'lucide-vue-next';
import { Avatar, AvatarFallback, AvatarImage } from '@timui/vue';
import { Button } from '@timui/vue';




</script>

<template>
  <Button variant="ghost" class="h-auto p-0 hover:bg-transparent"><Avatar><AvatarImage src="./avatar.jpg" alt="Profile image" /><AvatarFallback>KK</AvatarFallback></Avatar><ChevronDownIcon :size="16" class="opacity-60" aria-hidden="true" /></Button>
</template>
