// apps/docs/registry/default/components/slider/slider-11.tsx
import { Label } from '../../ui/label'
import { Slider } from '../../ui/slider'

export default function Component() {
  return (
    <div className="*:not-first:mt-4">
      <Label>Dual range slider</Label>
      <Slider defaultValue={[25, 75]} step={10} aria-label="Dual range slider" />
    </div>
  )
}

// apps/docs/registry/default/components/slider/slider-11.vue
<script setup lang="ts">
import { Label } from '@/components/ui/label';
import { Slider } from '@/components/ui/slider';



</script>

<template>
  <div class="*:not-first:mt-4"><Label>Dual range slider</Label><Slider :default-value="[25, 75]" :step="10" aria-label="Dual range slider" /></div>
</template>
