// apps/docs/registry/default/components/slider/slider-25.tsx
'use client'

import React, { useRef } from 'react'
import { Button, Input, Label, Slider } from '@timui/react'
import { RotateCcwIcon } from 'lucide-react'

import { useSliderWithInput } from '@/registry/default/hooks/use-slider-with-input'

export default function Component() {
  // Create refs to store reset functions
  const resetFunctionsRef = useRef<(() => void)[]>([])

  // Function to reset all sliders to default
  const resetAll = () => {
    resetFunctionsRef.current.forEach((resetFn) => resetFn())
  }

  // Function to register reset functions
  const registerResetFunction = (resetFn: () => void, index: number) => {
    resetFunctionsRef.current[index] = resetFn
  }

  return (
    <div className="space-y-4">
      <legend className="text-foreground text-sm font-medium">Object position</legend>
      <div className="space-y-2">
        <SliderWithInput
          minValue={-10}
          maxValue={10}
          initialValue={[-2]}
          defaultValue={[0]}
          label="X"
          onRegisterReset={(resetFn) => registerResetFunction(resetFn, 0)}
        />
        <SliderWithInput
          minValue={-10}
          maxValue={10}
          initialValue={[4]}
          defaultValue={[0]}
          label="Y"
          onRegisterReset={(resetFn) => registerResetFunction(resetFn, 1)}
        />
        <SliderWithInput
          minValue={-10}
          maxValue={10}
          initialValue={[2]}
          defaultValue={[0]}
          label="Z"
          onRegisterReset={(resetFn) => registerResetFunction(resetFn, 2)}
        />
      </div>
      <Button className="w-full" variant="outline" onClick={resetAll}>
        <RotateCcwIcon className="-ms-1 opacity-60" size={16} aria-hidden="true" />
        Reset
      </Button>
    </div>
  )
}

function SliderWithInput({
  minValue,
  maxValue,
  initialValue,
  defaultValue,
  label,
  onRegisterReset,
}: {
  minValue: number
  maxValue: number
  initialValue: number[]
  defaultValue: number[]
  label: string
  onRegisterReset: (resetFn: () => void) => void
}) {
  const {
    sliderValue,
    inputValues,
    validateAndUpdateValue,
    handleInputChange,
    handleSliderChange,
    resetToDefault,
  } = useSliderWithInput({ minValue, maxValue, initialValue, defaultValue })

  // Register the reset function when the component mounts
  React.useEffect(() => {
    onRegisterReset(resetToDefault)
  }, [onRegisterReset, resetToDefault])

  return (
    <div className="flex items-center gap-2">
      <Label className="text-muted-foreground text-xs">{label}</Label>
      <Slider
        className="grow [&>:last-child>span]:rounded"
        value={sliderValue}
        onValueChange={handleSliderChange}
        min={minValue}
        max={maxValue}
        aria-label={label}
      />
      <Input
        className="h-8 w-12 px-2 py-1"
        type="text"
        inputMode="decimal"
        value={inputValues[0]}
        onChange={(e) => handleInputChange(e, 0)}
        onBlur={() => validateAndUpdateValue(inputValues[0], 0)}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            validateAndUpdateValue(inputValues[0], 0)
          }
        }}
        aria-label="Enter value"
      />
    </div>
  )
}

// apps/docs/registry/default/components/slider/slider-25.vue
<script setup lang="ts">
import { RotateCcwIcon } from 'lucide-vue-next';
import { Button } from '@timui/vue';
import { Input } from '@timui/vue';
import { Label } from '@timui/vue';
import { Slider } from '@timui/vue';
import { useSliderWithInput } from '@/registry/default/hooks/use-slider-with-input-vue';

const minValue = -10;
const maxValue = 10;
const defaultValue = [0];

const {
  sliderValue: xSliderValue,
  inputValues: xInputValues,
  validateAndUpdateValue: validateX,
  handleInputChange: handleXInput,
  handleSliderChange: handleXSlider,
  resetToDefault: resetX,
} = useSliderWithInput({ minValue, maxValue, initialValue: [-2], defaultValue });

const {
  sliderValue: ySliderValue,
  inputValues: yInputValues,
  validateAndUpdateValue: validateY,
  handleInputChange: handleYInput,
  handleSliderChange: handleYSlider,
  resetToDefault: resetY,
} = useSliderWithInput({ minValue, maxValue, initialValue: [4], defaultValue });

const {
  sliderValue: zSliderValue,
  inputValues: zInputValues,
  validateAndUpdateValue: validateZ,
  handleInputChange: handleZInput,
  handleSliderChange: handleZSlider,
  resetToDefault: resetZ,
} = useSliderWithInput({ minValue, maxValue, initialValue: [2], defaultValue });

function resetAll() {
  resetX();
  resetY();
  resetZ();
}
</script>

<template>
  <div class="space-y-4">
    <legend class="text-foreground text-sm font-medium">Object position</legend>

    <div class="space-y-2">
      <div class="flex items-center gap-2">
        <Label class="text-muted-foreground text-xs">X</Label>
        <Slider
          class="grow [&>:last-child>span]:rounded"
          :value="xSliderValue"
          @update:modelValue="handleXSlider"
          :min="minValue"
          :max="maxValue"
          aria-label="X"
        />
        <Input
          class="h-8 w-12 px-2 py-1"
          type="text"
          inputMode="decimal"
          :model-value="xInputValues[0] ?? ''"
          @update:modelValue="(next) => handleXInput(next, 0)"
          @blur="() => validateX(xInputValues[0] ?? '', 0)"
          @keydown.enter.prevent="validateX(xInputValues[0] ?? '', 0)"
          aria-label="Enter X value"
        />
      </div>

      <div class="flex items-center gap-2">
        <Label class="text-muted-foreground text-xs">Y</Label>
        <Slider
          class="grow [&>:last-child>span]:rounded"
          :value="ySliderValue"
          @update:modelValue="handleYSlider"
          :min="minValue"
          :max="maxValue"
          aria-label="Y"
        />
        <Input
          class="h-8 w-12 px-2 py-1"
          type="text"
          inputMode="decimal"
          :model-value="yInputValues[0] ?? ''"
          @update:modelValue="(next) => handleYInput(next, 0)"
          @blur="() => validateY(yInputValues[0] ?? '', 0)"
          @keydown.enter.prevent="validateY(yInputValues[0] ?? '', 0)"
          aria-label="Enter Y value"
        />
      </div>

      <div class="flex items-center gap-2">
        <Label class="text-muted-foreground text-xs">Z</Label>
        <Slider
          class="grow [&>:last-child>span]:rounded"
          :value="zSliderValue"
          @update:modelValue="handleZSlider"
          :min="minValue"
          :max="maxValue"
          aria-label="Z"
        />
        <Input
          class="h-8 w-12 px-2 py-1"
          type="text"
          inputMode="decimal"
          :model-value="zInputValues[0] ?? ''"
          @update:modelValue="(next) => handleZInput(next, 0)"
          @blur="() => validateZ(zInputValues[0] ?? '', 0)"
          @keydown.enter.prevent="validateZ(zInputValues[0] ?? '', 0)"
          aria-label="Enter Z value"
        />
      </div>
    </div>

    <Button class="w-full" variant="outline" @click="resetAll">
      <RotateCcwIcon class="-ms-1 opacity-60" :size="16" aria-hidden="true" />
      Reset
    </Button>
  </div>
</template>
