// apps/docs/registry/default/components/navbar/navbar-17.tsx
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
  Button,
} from '@timui/react'
import { BookmarkIcon, HomeIcon } from 'lucide-react'

import DatePicker from '@/registry/default/components/navbar-components/date-picker'
import Filters from '@/registry/default/components/navbar-components/filters'

export default function Component() {
  return (
    <header className="border-b px-4 md:px-6">
      <div className="flex h-16 items-center justify-between gap-4">
        {/* Left side */}
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="#">
                <HomeIcon size={16} aria-hidden="true" />
                <span className="sr-only">Home</span>
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbPage>Reports</BreadcrumbPage>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
        {/* Right side */}
        <div className="flex items-center gap-2">
          {/* Date picker */}
          <DatePicker />
          {/* Filters */}
          <Filters />
          {/* Saved button */}
          <Button size="sm" variant="outline" className="aspect-square text-sm max-sm:p-0">
            <BookmarkIcon
              className="text-muted-foreground/80 sm:-ms-1"
              size={16}
              aria-hidden="true"
            />
            <span className="max-sm:sr-only">Saved</span>
          </Button>
        </div>
      </div>
    </header>
  )
}

// apps/docs/registry/default/components/navbar/navbar-17.vue
<script setup lang="ts">
import { BookmarkIcon, HomeIcon } from 'lucide-vue-next';
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from '@timui/vue';
import { Button } from '@timui/vue';
import DatePicker from '@/registry/default/components/navbar-components/date-picker.vue';
import Filters from '@/registry/default/components/navbar-components/filters.vue';



</script>

<template>
  <header class="border-b px-4 md:px-6"><div class="flex h-16 items-center justify-between gap-4"><Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink href="#"><HomeIcon :size="16" aria-hidden="true" /><span class="sr-only">Home</span></BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbPage>Reports</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb><div class="flex items-center gap-2"><DatePicker /><Filters /><Button size="sm" variant="outline" class="aspect-square text-sm max-sm:p-0"><BookmarkIcon class="text-muted-foreground/80 sm:-ms-1" :size="16" aria-hidden="true" /><span class="max-sm:sr-only">Saved</span></Button></div></div></header>
</template>
