// apps/docs/registry/default/components/navbar/navbar-12.tsx
import { HouseIcon, InboxIcon, SparklesIcon, ZapIcon } from 'lucide-react'

import Logo from '@/registry/default/components/navbar-components/logo'
import UserMenu from '@/registry/default/components/navbar-components/user-menu'

import { Button } from '../../ui/button'
import {
  NavigationMenu,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
} from '../../ui/navigation-menu'
import { Popover, PopoverContent, PopoverTrigger } from '../../ui/popover'

// Navigation links array
const navigationLinks = [
  { href: '#', label: 'Home', icon: HouseIcon, active: true },
  { href: '#', label: 'Inbox', icon: InboxIcon },
  { href: '#', label: 'Insights', icon: ZapIcon },
]

export default function Component() {
  return (
    <header className="border-b px-4 md:px-6">
      <div className="flex h-16 items-center justify-between gap-4">
        {/* Left side */}
        <div className="flex flex-1 items-center gap-2">
          {/* Mobile menu trigger */}
          <Popover>
            <PopoverTrigger asChild>
              <Button className="group size-8 md:hidden" variant="ghost" size="icon">
                <svg
                  className="pointer-events-none"
                  width={16}
                  height={16}
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M4 12L20 12"
                    className="origin-center -translate-y-[7px] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.1)] group-aria-expanded:translate-x-0 group-aria-expanded:translate-y-0 group-aria-expanded:rotate-[315deg]"
                  />
                  <path
                    d="M4 12H20"
                    className="origin-center transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.8)] group-aria-expanded:rotate-45"
                  />
                  <path
                    d="M4 12H20"
                    className="origin-center translate-y-[7px] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.1)] group-aria-expanded:translate-y-0 group-aria-expanded:rotate-[135deg]"
                  />
                </svg>
              </Button>
            </PopoverTrigger>
            <PopoverContent align="start" className="w-36 p-1 md:hidden">
              <NavigationMenu className="max-w-none *:w-full">
                <NavigationMenuList className="flex-col items-start gap-0 md:gap-2">
                  {navigationLinks.map((link, index) => {
                    const Icon = link.icon
                    return (
                      <NavigationMenuItem key={index} className="w-full">
                        <NavigationMenuLink
                          href={link.href}
                          className="flex-row items-center gap-2 py-1.5"
                          active={link.active}
                        >
                          <Icon size={16} className="text-muted-foreground/80" aria-hidden="true" />
                          <span>{link.label}</span>
                        </NavigationMenuLink>
                      </NavigationMenuItem>
                    )
                  })}
                </NavigationMenuList>
              </NavigationMenu>
            </PopoverContent>
          </Popover>

          <NavigationMenu className="max-md:hidden">
            <NavigationMenuList className="gap-2">
              {navigationLinks.map((link, index) => {
                const Icon = link.icon
                return (
                  <NavigationMenuItem key={index}>
                    <NavigationMenuLink
                      active={link.active}
                      href={link.href}
                      className="text-foreground hover:text-primary flex-row items-center gap-2 py-1.5 font-medium"
                    >
                      <Icon size={16} className="text-muted-foreground/80" aria-hidden="true" />
                      <span>{link.label}</span>
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                )
              })}
            </NavigationMenuList>
          </NavigationMenu>
        </div>

        {/* Middle side: Logo */}
        <div className="flex items-center">
          <a href="#" className="text-primary hover:text-primary/90">
            <Logo />
          </a>
        </div>

        {/* Right side: Actions */}
        <div className="flex flex-1 items-center justify-end gap-4">
          {/* User menu */}
          <UserMenu />
          {/* Upgrade button */}
          <Button size="sm" className="aspect-square text-sm">
            <SparklesIcon
              className="opacity-60 max-sm:hidden sm:-ms-1"
              size={16}
              aria-hidden="true"
            />
            Upgrade
          </Button>
        </div>
      </div>
    </header>
  )
}

// apps/docs/registry/default/components/navbar/navbar-12.vue
<script setup lang="ts">
import { HouseIcon, InboxIcon, SparklesIcon, ZapIcon } from 'lucide-vue-next';
import { Button } from '@/components/ui/button';
import { NavigationMenu, NavigationMenuItem, NavigationMenuLink, NavigationMenuList } from '@/components/ui/navigation-menu';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import Logo from '@/registry/default/components/navbar-components/logo.vue';
import UserMenu from '@/registry/default/components/navbar-components/user-menu.vue';

const navigationLinks = [
  { href: '#', label: 'Home', icon: HouseIcon, active: true },
  { href: '#', label: 'Inbox', icon: InboxIcon },
  { href: '#', label: 'Insights', icon: ZapIcon },
];
</script>

<template>
  <header class="border-b px-4 md:px-6"><div class="flex h-16 items-center justify-between gap-4"><div class="flex flex-1 items-center gap-2"><Popover><PopoverTrigger as-child><Button class="group size-8 md:hidden" variant="ghost" size="icon"><svg class="pointer-events-none" :width="16" :height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" xmlns="http://www.w3.org/2000/svg"><path d="M4 12L20 12" class="origin-center -translate-y-[7px] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.1)] group-aria-expanded:translate-x-0 group-aria-expanded:translate-y-0 group-aria-expanded:rotate-[315deg]" /><path d="M4 12H20" class="origin-center transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.8)] group-aria-expanded:rotate-45" /><path d="M4 12H20" class="origin-center translate-y-[7px] transition-all duration-300 ease-[cubic-bezier(.5,.85,.25,1.1)] group-aria-expanded:translate-y-0 group-aria-expanded:rotate-[135deg]" /></svg></Button></PopoverTrigger><PopoverContent align="start" class="w-36 p-1 md:hidden"><NavigationMenu class="max-w-none *:w-full"><NavigationMenuList class="flex-col items-start gap-0 md:gap-2">{{ navigationLinks.map((link, index) => {
                    const Icon = link.icon
                    return (
                      <NavigationMenuItem key={index} className="w-full">
                        <NavigationMenuLink
                          href={link.href}
                          className="flex-row items-center gap-2 py-1.5"
                          active={link.active}
                        >
                          <Icon size={16} className="text-muted-foreground/80" aria-hidden="true" />
                          <span>{link.label}</span>
                        </NavigationMenuLink>
                      </NavigationMenuItem>
                    )
                  }) }}</NavigationMenuList></NavigationMenu></PopoverContent></Popover><NavigationMenu class="max-md:hidden"><NavigationMenuList class="gap-2">{{ navigationLinks.map((link, index) => {
                const Icon = link.icon
                return (
                  <NavigationMenuItem key={index}>
                    <NavigationMenuLink
                      active={link.active}
                      href={link.href}
                      className="text-foreground hover:text-primary flex-row items-center gap-2 py-1.5 font-medium"
                    >
                      <Icon size={16} className="text-muted-foreground/80" aria-hidden="true" />
                      <span>{link.label}</span>
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                )
              }) }}</NavigationMenuList></NavigationMenu></div><div class="flex items-center"><a href="#" class="text-primary hover:text-primary/90"><Logo /></a></div><div class="flex flex-1 items-center justify-end gap-4"><UserMenu /><Button size="sm" class="aspect-square text-sm"><SparklesIcon class="opacity-60 max-sm:hidden sm:-ms-1" :size="16" aria-hidden="true" />Upgrade
          </Button></div></div></header>
</template>
