// registry/react/ui/multiselect.tsx
'use client'

import * as React from 'react'
import { Command as CommandPrimitive, useCommandState } from 'cmdk'

import { cva } from '../lib/cva'
import { cn } from '../lib/utils'
import { Command, CommandGroup, CommandItem, CommandList } from './command'

// Variants
const multiselectCommandVariants = cva('h-auto overflow-visible bg-transparent')
const multiselectContainerVariants = cva(
  'border-input focus-within:border-ring focus-within:ring-ring/50 has-aria-invalid:ring-destructive/20 dark:has-aria-invalid:ring-destructive/40 has-aria-invalid:border-destructive relative min-h-[38px] rounded-md border text-sm transition-[color,box-shadow] outline-none focus-within:ring-[3px] has-disabled:pointer-events-none has-disabled:cursor-not-allowed has-disabled:opacity-50'
)
const multiselectTagVariants = cva(
  'animate-fadeIn bg-background text-secondary-foreground hover:bg-background relative inline-flex h-7 cursor-default items-center rounded-md border ps-2 pe-7 pl-2 text-xs font-medium transition-all disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 data-fixed:pe-2'
)
const multiselectTagRemoveVariants = cva(
  'text-muted-foreground/80 hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 absolute -inset-y-px -end-px flex size-7 items-center justify-center rounded-e-md border border-transparent p-0 outline-hidden transition-[color,box-shadow] outline-none focus-visible:ring-[3px]'
)
const multiselectInputVariants = cva(
  'placeholder:text-muted-foreground/70 flex-1 bg-transparent outline-hidden disabled:cursor-not-allowed'
)
const multiselectClearButtonVariants = cva(
  'text-muted-foreground/80 hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 absolute end-0 top-0 flex size-9 items-center justify-center rounded-md border border-transparent transition-[color,box-shadow] outline-none focus-visible:ring-[3px]'
)
const multiselectDropdownVariants = cva(
  'border-input absolute top-2 z-10 w-full overflow-hidden rounded-md border'
)
const multiselectListVariants = cva('bg-popover text-popover-foreground shadow-lg outline-hidden')
const multiselectEmptyVariants = cva('px-2 py-4 text-center text-sm')
const multiselectGroupVariants = cva('h-full overflow-auto')

export interface Option {
  value: string
  label: string
  disable?: boolean
  fixed?: boolean
  [key: string]: string | boolean | undefined
}

interface GroupOption {
  [key: string]: Option[]
}

interface MultipleSelectorProps {
  value?: Option[]
  defaultOptions?: Option[]
  options?: Option[]
  placeholder?: string
  loadingIndicator?: React.ReactNode
  emptyIndicator?: React.ReactNode
  delay?: number
  triggerSearchOnFocus?: boolean
  onSearch?: (value: string) => Promise<Option[]>
  onSearchSync?: (value: string) => Option[]
  onChange?: (options: Option[]) => void
  onValueChange?: (options: Option[]) => void // Duplicate of onChange for consistency?
  maxSelected?: number
  onMaxSelected?: (maxLimit: number) => void
  hidePlaceholderWhenSelected?: boolean
  disabled?: boolean
  groupBy?: string
  className?: string
  badgeClassName?: string
  selectFirstItem?: boolean
  creatable?: boolean
  commandProps?: React.ComponentPropsWithoutRef<typeof Command>
  inputProps?: Omit<
    React.ComponentPropsWithoutRef<typeof CommandPrimitive.Input>,
    'value' | 'placeholder' | 'disabled'
  >
  hideClearAllButton?: boolean
}

export interface MultipleSelectorRef {
  selectedValue: Option[]
  input: HTMLInputElement
  focus: () => void
  reset: () => void
}

function useDebounce<T>(value: T, delay?: number): T {
  const [debouncedValue, setDebouncedValue] = React.useState<T>(value)

  React.useEffect(() => {
    const timer = setTimeout(() => setDebouncedValue(value), delay || 500)

    return () => {
      clearTimeout(timer)
    }
  }, [value, delay])

  return debouncedValue
}

function transToGroupOption(options: Option[], groupBy?: string) {
  if (options.length === 0) {
    return {}
  }
  if (!groupBy) {
    return {
      '': options,
    }
  }

  const groupOption: GroupOption = {}
  options.forEach((option) => {
    const key = (option[groupBy] as string) || ''
    if (!groupOption[key]) {
      groupOption[key] = []
    }
    groupOption[key].push(option)
  })
  return groupOption
}

function removePickedOption(groupOption: GroupOption, picked: Option[]) {
  const cloneOption = JSON.parse(JSON.stringify(groupOption)) as GroupOption

  for (const [key, value] of Object.entries(cloneOption)) {
    cloneOption[key] = value.filter((val) => !picked.find((p) => p.value === val.value))
  }
  return cloneOption
}

function isOptionsExist(groupOption: GroupOption, targetOption: Option[]) {
  for (const [, value] of Object.entries(groupOption)) {
    if (value.some((option) => targetOption.find((p) => p.value === option.value))) {
      return true
    }
  }
  return false
}

const CommandEmpty = ({
  className,
  ...props
}: React.ComponentProps<typeof CommandPrimitive.Empty>) => {
  const render = useCommandState((state) => state.filtered.count === 0)

  if (!render) return null

  return (
    <div
      className={cn(multiselectEmptyVariants(), className)}
      cmdk-empty=""
      role="presentation"
      {...props}
    />
  )
}
CommandEmpty.displayName = 'CommandEmpty'

const MultipleSelector = React.forwardRef<MultipleSelectorRef, MultipleSelectorProps>(
  (
    {
      value,
      onChange,
      onValueChange,
      placeholder,
      defaultOptions: arrayDefaultOptions = [],
      options: arrayOptions,
      delay,
      onSearch,
      onSearchSync,
      loadingIndicator,
      emptyIndicator,
      maxSelected = Number.MAX_SAFE_INTEGER,
      onMaxSelected,
      hidePlaceholderWhenSelected,
      disabled,
      groupBy,
      className,
      badgeClassName,
      selectFirstItem = true,
      creatable = false,
      triggerSearchOnFocus = false,
      commandProps,
      inputProps,
      hideClearAllButton = false,
    },
    ref
  ) => {
    const emitValueChange = React.useCallback(
      (next: Option[]) => {
        onValueChange?.(next)
        onChange?.(next)
      },
      [onChange, onValueChange]
    )

    const inputRef = React.useRef<HTMLInputElement>(null)
    const [open, setOpen] = React.useState(false)
    const [onScrollbar, setOnScrollbar] = React.useState(false)
    const [isLoading, setIsLoading] = React.useState(false)
    const dropdownRef = React.useRef<HTMLDivElement>(null)

    const [selected, setSelected] = React.useState<Option[]>(value || [])
    const [options, setOptions] = React.useState<GroupOption>(
      transToGroupOption(arrayDefaultOptions, groupBy)
    )
    const [inputValue, setInputValue] = React.useState('')
    const debouncedSearchTerm = useDebounce(inputValue, delay || 500)

    React.useImperativeHandle(
      ref,
      () => ({
        selectedValue: [...selected],
        input: inputRef.current as HTMLInputElement,
        focus: () => inputRef.current?.focus(),
        reset: () => {
          setSelected([])
          emitValueChange([])
        },
      }),
      [selected, emitValueChange]
    )

    const handleClickOutside = (event: MouseEvent | TouchEvent) => {
      if (
        dropdownRef.current &&
        !dropdownRef.current.contains(event.target as Node) &&
        inputRef.current &&
        !inputRef.current.contains(event.target as Node)
      ) {
        setOpen(false)
        inputRef.current.blur()
      }
    }

    const handleUnselect = React.useCallback(
      (option: Option) => {
        const newOptions = selected.filter((s) => s.value !== option.value)
        setSelected(newOptions)
        emitValueChange(newOptions)
      },
      [emitValueChange, selected]
    )

    const handleKeyDown = React.useCallback(
      (e: React.KeyboardEvent<HTMLDivElement>) => {
        const input = inputRef.current
        if (input) {
          if (e.key === 'Delete' || e.key === 'Backspace') {
            if (input.value === '' && selected.length > 0) {
              const lastSelectOption = selected[selected.length - 1]
              if (!lastSelectOption.fixed) {
                handleUnselect(selected[selected.length - 1])
              }
            }
          }
          if (e.key === 'Escape') {
            input.blur()
          }
        }
      },
      [handleUnselect, selected]
    )

    React.useEffect(() => {
      if (open) {
        document.addEventListener('mousedown', handleClickOutside)
        document.addEventListener('touchend', handleClickOutside)
      } else {
        document.removeEventListener('mousedown', handleClickOutside)
        document.removeEventListener('touchend', handleClickOutside)
      }

      return () => {
        document.removeEventListener('mousedown', handleClickOutside)
        document.removeEventListener('touchend', handleClickOutside)
      }
    }, [open])

    React.useEffect(() => {
      if (value) {
        setSelected(value)
      }
    }, [value])

    React.useEffect(() => {
      if (!arrayOptions || onSearch) {
        return
      }
      const newOption = transToGroupOption(arrayOptions || [], groupBy)
      if (JSON.stringify(newOption) !== JSON.stringify(options)) {
        setOptions(newOption)
      }
    }, [arrayDefaultOptions, arrayOptions, groupBy, onSearch, options])

    React.useEffect(() => {
      const doSearchSync = () => {
        const res = onSearchSync?.(debouncedSearchTerm)
        setOptions(transToGroupOption(res || [], groupBy))
      }

      const exec = async () => {
        if (!onSearchSync || !open) return

        if (triggerSearchOnFocus) {
          doSearchSync()
        }

        if (debouncedSearchTerm) {
          doSearchSync()
        }
      }

      void exec()
    }, [debouncedSearchTerm, groupBy, open, triggerSearchOnFocus, onSearchSync])

    React.useEffect(() => {
      const doSearch = async () => {
        setIsLoading(true)
        const res = await onSearch?.(debouncedSearchTerm)
        setOptions(transToGroupOption(res || [], groupBy))
        setIsLoading(false)
      }

      const exec = async () => {
        if (!onSearch || !open) return

        if (triggerSearchOnFocus) {
          await doSearch()
        }

        if (debouncedSearchTerm) {
          await doSearch()
        }
      }

      void exec()
    }, [debouncedSearchTerm, groupBy, open, triggerSearchOnFocus, onSearch])

    const CreatableItem = () => {
      if (!creatable) return undefined
      if (
        isOptionsExist(options, [{ value: inputValue, label: inputValue }]) ||
        selected.find((s) => s.value === inputValue)
      ) {
        return undefined
      }

      const Item = (
        <CommandItem
          value={inputValue}
          className="cursor-pointer"
          onMouseDown={(e) => {
            e.preventDefault()
            e.stopPropagation()
          }}
          onSelect={(value: string) => {
            if (selected.length >= maxSelected) {
              onMaxSelected?.(selected.length)
              return
            }
            setInputValue('')
            const newOptions = [...selected, { value, label: value }]
            setSelected(newOptions)
            emitValueChange(newOptions)
          }}
        >
          {`Create "${inputValue}"`}
        </CommandItem>
      )

      if (!onSearch && inputValue.length > 0) {
        return Item
      }

      if (onSearch && debouncedSearchTerm.length > 0 && !isLoading) {
        return Item
      }

      return undefined
    }

    const EmptyItem = React.useCallback(() => {
      if (!emptyIndicator) return undefined

      if (onSearch && !creatable && Object.keys(options).length === 0) {
        return (
          <CommandItem value="-" disabled>
            {emptyIndicator}
          </CommandItem>
        )
      }

      return <CommandEmpty>{emptyIndicator}</CommandEmpty>
    }, [creatable, emptyIndicator, onSearch, options])

    const selectables = React.useMemo<GroupOption>(
      () => removePickedOption(options, selected),
      [options, selected]
    )

    const commandFilter = React.useCallback(() => {
      if (commandProps?.filter) {
        return commandProps.filter
      }

      if (creatable) {
        return (value: string, search: string) => {
          return value.toLowerCase().includes(search.toLowerCase()) ? 1 : -1
        }
      }
      return undefined
    }, [creatable, commandProps?.filter])

    return (
      <Command
        ref={dropdownRef}
        {...commandProps}
        onKeyDown={(e) => {
          handleKeyDown(e)
          commandProps?.onKeyDown?.(e)
        }}
        className={cn(multiselectCommandVariants(), commandProps?.className)}
        shouldFilter={
          commandProps?.shouldFilter !== undefined ? commandProps.shouldFilter : !onSearch
        }
        filter={commandFilter()}
      >
        <div
          className={cn(
            multiselectContainerVariants(),
            {
              'p-1': selected.length !== 0,
              'cursor-text': !disabled && selected.length !== 0,
            },
            !hideClearAllButton && 'pe-9',
            className
          )}
          onClick={() => {
            if (disabled) return
            inputRef?.current?.focus()
          }}
        >
          <div className="flex flex-wrap gap-1">
            {selected.map((option) => {
              return (
                <div
                  key={option.value}
                  className={cn(multiselectTagVariants(), badgeClassName)}
                  data-fixed={option.fixed}
                  data-disabled={disabled || undefined}
                >
                  {option.label}
                  <button
                    className={multiselectTagRemoveVariants()}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter') {
                        handleUnselect(option)
                      }
                    }}
                    onMouseDown={(e) => {
                      e.preventDefault()
                      e.stopPropagation()
                    }}
                    onClick={() => handleUnselect(option)}
                    aria-label="Remove"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="14"
                      height="14"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      aria-hidden="true"
                    >
                      <path d="M18 6 6 18" />
                      <path d="m6 6 12 12" />
                    </svg>
                  </button>
                </div>
              )
            })}
            <CommandPrimitive.Input
              {...inputProps}
              ref={inputRef}
              value={inputValue}
              disabled={disabled}
              onValueChange={(value) => {
                setInputValue(value)
                inputProps?.onValueChange?.(value)
              }}
              onBlur={(event) => {
                if (!onScrollbar) {
                  setOpen(false)
                }
                inputProps?.onBlur?.(event)
              }}
              onFocus={(event) => {
                setOpen(true)
                if (triggerSearchOnFocus) {
                  onSearch?.(debouncedSearchTerm)
                }
                inputProps?.onFocus?.(event)
              }}
              placeholder={hidePlaceholderWhenSelected && selected.length !== 0 ? '' : placeholder}
              className={cn(
                multiselectInputVariants(),
                {
                  'w-full': hidePlaceholderWhenSelected,
                  'px-3 py-2': selected.length === 0,
                  'ml-1': selected.length !== 0,
                },
                inputProps?.className
              )}
            />
            <button
              type="button"
              onClick={() => {
                setSelected(selected.filter((s) => s.fixed))
                emitValueChange(selected.filter((s) => s.fixed))
              }}
              className={cn(
                multiselectClearButtonVariants(),
                (hideClearAllButton ||
                  disabled ||
                  selected.length < 1 ||
                  selected.filter((s) => s.fixed).length === selected.length) &&
                  'hidden'
              )}
              aria-label="Clear all"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <path d="M18 6 6 18" />
                <path d="m6 6 12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div className="relative">
          <div
            className={cn(
              multiselectDropdownVariants(),
              'data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
              !open && 'hidden'
            )}
            data-state={open ? 'open' : 'closed'}
          >
            {open && (
              <CommandList
                className={multiselectListVariants()}
                onMouseLeave={() => {
                  setOnScrollbar(false)
                }}
                onMouseEnter={() => {
                  setOnScrollbar(true)
                }}
                onMouseUp={() => {
                  inputRef?.current?.focus()
                }}
              >
                {isLoading ? (
                  <>{loadingIndicator}</>
                ) : (
                  <>
                    {EmptyItem()}
                    {CreatableItem()}
                    {!selectFirstItem && <CommandItem value="-" className="hidden" />}
                    {Object.entries(selectables).map(([key, dropdowns]) => (
                      <CommandGroup key={key} heading={key} className={multiselectGroupVariants()}>
                        <>
                          {dropdowns.map((option) => {
                            return (
                              <CommandItem
                                key={option.value}
                                value={option.value}
                                disabled={option.disable}
                                onMouseDown={(e) => {
                                  e.preventDefault()
                                  e.stopPropagation()
                                }}
                                onSelect={() => {
                                  if (selected.length >= maxSelected) {
                                    onMaxSelected?.(selected.length)
                                    return
                                  }
                                  setInputValue('')
                                  const newOptions = [...selected, option]
                                  setSelected(newOptions)
                                  emitValueChange(newOptions)
                                }}
                                className={cn(
                                  'cursor-pointer',
                                  option.disable &&
                                    'pointer-events-none cursor-not-allowed opacity-50'
                                )}
                              >
                                {option.label}
                              </CommandItem>
                            )
                          })}
                        </>
                      </CommandGroup>
                    ))}
                  </>
                )}
              </CommandList>
            )}
          </div>
        </div>
      </Command>
    )
  }
)

MultipleSelector.displayName = 'MultipleSelector'
export default MultipleSelector

// registry/vue/ui/multiselect/multiselect.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch, type Component, type VNodeChild, type HTMLAttributes } from "vue";
import { cva } from "class-variance-authority";
import { cn } from "../../lib/utils";
import Command from "../command/command.vue";
import CommandEmpty from "../command/command-empty.vue";
import CommandGroup from "../command/command-group.vue";
import CommandItem from "../command/command-item.vue";
import CommandList from "../command/command-list.vue";
import CommandInput from "../command/command-input.vue";

const multiselectVariants = cva('')
const multiselectCommandVariants = cva('h-auto overflow-visible bg-transparent')
const multiselectContainerVariants = cva(
    'border-input focus-within:border-ring focus-within:ring-ring/50 has-aria-invalid:ring-destructive/20 dark:has-aria-invalid:ring-destructive/40 has-aria-invalid:border-destructive relative min-h-[38px] rounded-md border text-sm transition-[color,box-shadow] outline-none focus-within:ring-[3px] has-disabled:pointer-events-none has-disabled:cursor-not-allowed has-disabled:opacity-50'
)
const multiselectTagVariants = cva(
    'animate-fadeIn bg-background text-secondary-foreground hover:bg-background relative inline-flex h-7 cursor-default items-center rounded-md border ps-2 pe-7 pl-2 text-xs font-medium transition-all disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 data-fixed:pe-2'
)
const multiselectTagRemoveVariants = cva(
    'text-muted-foreground/80 hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 absolute -inset-y-px -end-px flex size-7 items-center justify-center rounded-e-md border border-transparent p-0 outline-hidden transition-[color,box-shadow] outline-none focus-visible:ring-[3px]'
)
const multiselectInputVariants = cva(
    'placeholder:text-muted-foreground/70 flex-1 bg-transparent outline-none disabled:cursor-not-allowed px-3 py-2'
)
const multiselectClearButtonVariants = cva(
    'text-muted-foreground/80 hover:text-foreground focus-visible:border-ring focus-visible:ring-ring/50 absolute end-0 top-0 flex size-9 items-center justify-center rounded-md border border-transparent transition-[color,box-shadow] outline-none focus-visible:ring-[3px]'
)
const multiselectDropdownVariants = cva(
    'border-input absolute top-2 z-10 w-full overflow-hidden rounded-md border text-popover-foreground bg-popover shadow-md'
)
const multiselectListVariants = cva('bg-popover text-popover-foreground shadow-lg outline-hidden')
const multiselectGroupVariants = cva('h-full overflow-auto')

export type Option = {
  value: string;
  label: string;
  disable?: boolean;
  fixed?: boolean;
  [key: string]: any;
}

interface GroupOption {
  [key: string]: Option[];
}

const props = withDefaults(defineProps<{
  modelValue?: Option[];
  options?: Option[];
  defaultOptions?: Option[];
  variant?: string;
  defaultValue?: Option[];
  onSearch?: (term: string) => Promise<Option[]>;
  onSearchSync?: (term: string) => Option[];
  placeholder?: string;
  maxSelected?: number;
  hideClearAllButton?: boolean;
  hidePlaceholderWhenSelected?: boolean;
  emptyIndicator?: any;
  loadingIndicator?: any;
  delay?: number;
  triggerSearchOnFocus?: boolean;
  creatable?: boolean;
  groupBy?: string;
  selectFirstItem?: boolean;
  class?: HTMLAttributes['class'];
  badgeClass?: string;
  disabled?: boolean;
  onMaxSelected?: (count: number) => void;
}>(), {
  modelValue: () => [],
  options: () => [],
  maxSelected: Number.MAX_SAFE_INTEGER,
  selectFirstItem: true,
  placeholder: "Select...",
  delay: 500
});

const emit = defineEmits(["update:modelValue", "change", "search-change"]);

const commandRef = ref<any>(null);
const open = ref(false);
const isLoading = ref(false);
const selected = ref<Option[]>(props.modelValue || []);
const activeOptions = ref<GroupOption>({});
const inputValue = ref("");

const transToGroupOption = (list: Option[] = [], groupBy?: string): GroupOption => {
  if (list.length === 0) return {};
  if (!groupBy) return { "": list };
  const groupOption: GroupOption = {};
  list.forEach((option) => {
    const key = (option[groupBy] as string) || "";
    if (!groupOption[key]) groupOption[key] = [];
    groupOption[key].push(option);
  });
  return groupOption;
};

// Sync selected with modelValue
watch(() => props.modelValue, (val) => {
  selected.value = val || [];
}, { deep: true });

// Sync options to local state
watch(() => props.options, (val) => {
  if (!val || props.onSearch) return;
  activeOptions.value = transToGroupOption(val, props.groupBy);
}, { deep: true, immediate: true });

// Debounced search logic
let debounceTimer: ReturnType<typeof setTimeout> | null = null;
const debouncedSearchTerm = ref("");

watch(inputValue, (val) => {
  if (debounceTimer) clearTimeout(debounceTimer);
  debounceTimer = setTimeout(() => {
    debouncedSearchTerm.value = val;
  }, props.delay);
});

watch([debouncedSearchTerm, open, () => props.groupBy], async ([term, isOpen]) => {
   if (!isOpen) return;
   if (props.onSearch) {
     isLoading.value = true;
     const res = await props.onSearch(term);
     activeOptions.value = transToGroupOption(res, props.groupBy);
     isLoading.value = false;
   } else if (props.onSearchSync) {
     const res = props.onSearchSync(term);
     activeOptions.value = transToGroupOption(res, props.groupBy);
   } else {
     // Local filtering
     const filtered = props.options.filter(opt => 
        opt.label.toLowerCase().includes(term.toLowerCase())
     );
     activeOptions.value = transToGroupOption(filtered, props.groupBy);
   }
});

const handleUnselect = (option: Option) => {
  const next = selected.value.filter(s => s.value !== option.value);
  selected.value = next;
  emit("update:modelValue", next);
  emit("change", next);
};

const handleSelect = (option: Option) => {
    if (selected.value.length >= props.maxSelected) {
        props.onMaxSelected?.(selected.value.length);
        return;
    }
    // Prevent duplicate selection
    if (selected.value.find(s => s.value === option.value)) return;
    
    // Clear input
    inputValue.value = "";
    if (commandRef.value?.api) commandRef.value.api.value.setInputValue("");

    const next = [...selected.value, option];
    selected.value = next;
    emit("update:modelValue", next);
    emit("change", next);
};

// Use Command's API to detect input changes if we can't bind directly?
// CommandInput (Zig) uses api.inputProps. 
// We need to capture input. We can use `watch` on commandRef.api.value.inputValue if exposed.
// My Command component exposes `api`.
watch(() => commandRef.value?.api?.value?.inputValue, (val) => {
    if (val !== undefined) inputValue.value = val;
});

// Handling open state
const handleFocus = () => {
    if (!props.disabled) open.value = true;
};
const handleBlur = () => {
    // Check if clicking inside? Zig handles outside click for Combobox via Popover logic?
    // My Command is typically open=true always (inline) or Dialog.
    // Multiselect here creates a Dropdown manually.
    // If Command component has `open: true` internally, it renders.
    // Here we wrap CommandList in `multiselectDropdownVariants` div which is conditioned on `open`.
    // We need to handle outside click.
    setTimeout(() => { open.value = false; }, 200); // Simple delay for click to register
};

</script>

<template>
  <Command
    ref="commandRef"
    :class="multiselectCommandVariants()"
    multiple
    v-model:modelValue="selected"
  >
    <div :class="cn(multiselectContainerVariants(), props.class)">
       <div class="flex flex-wrap gap-1 p-1">
          <!-- Tags -->
          <div v-for="option in selected" :key="option.value" :class="cn(multiselectTagVariants(), props.badgeClass)">
             {{ option.label }}
             <button :class="multiselectTagRemoveVariants()" type="button" @click.stop="handleUnselect(option)">
                <svg class="h-3 w-3" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
             </button>
          </div>
          
          <!-- Input -->
          <CommandInput
            :class="cn(multiselectInputVariants(), { 'ml-1': selected.length > 0 })"
            :placeholder="selected.length > 0 && props.hidePlaceholderWhenSelected ? '' : props.placeholder"
            @focus="handleFocus"
            @blur="handleBlur"
          />
          
          <!-- Clear Button -->
           <button
              v-if="!props.hideClearAllButton && !props.disabled && selected.length > 0"
              type="button"
              :class="multiselectClearButtonVariants()"
              @click.stop="selected = []; emit('update:modelValue', []); emit('change', [])"
           >
              <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
           </button>
       </div>
    </div>
    
    <div class="relative">
      <div v-if="open" :class="multiselectDropdownVariants()">
        <CommandList :class="multiselectListVariants()">
           <CommandEmpty v-if="Object.keys(activeOptions).length === 0 && !isLoading">
              {{ props.emptyIndicator || "No results found." }}
           </CommandEmpty>
           
           <template v-for="(options, group) in activeOptions" :key="group">
              <CommandGroup :heading="group || undefined" :class="multiselectGroupVariants()">
                 <CommandItem 
                    v-for="opt in options" 
                    :key="opt.value" 
                    :value="opt.value" 
                    :label="opt.label"
                    @select="handleSelect(opt)"
                    class="cursor-pointer"
                 >
                    {{ opt.label }}
                 </CommandItem>
              </CommandGroup>
           </template>
        </CommandList>
      </div>
    </div>
  </Command>
</template>
