// apps/docs/registry/default/components/alert/alert-08.tsx
import { Alert, AlertDescription } from '@timui/react'

export default function Component() {
  return (
    <Alert className="rounded-md border border-blue-500/50 px-4 py-3 text-blue-600">
      <div className="flex gap-3">
        <span className="me-3 -mt-0.5 inline-flex opacity-60" aria-hidden="true">
          !
        </span>
        <AlertDescription className="text-sm text-current">Just a quick note!</AlertDescription>
      </div>
    </Alert>
  )
}

// apps/docs/registry/default/components/alert/alert-08.vue
<script setup lang="ts">
import { Alert } from '@timui/vue';
import { AlertDescription } from '@timui/vue';




</script>

<template>
  <Alert class="rounded-md border border-blue-500/50 px-4 py-3 text-blue-600"><div class="flex gap-3"><span class="me-3 -mt-0.5 inline-flex opacity-60" aria-hidden="true">!
        </span><AlertDescription class="text-sm text-current">Just a quick note!</AlertDescription></div></Alert>
</template>
